/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.administracion;

import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.text.NumberFormat;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import models.*;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Manuel Rodriguez
 */
public class frmDetalleVenta extends javax.swing.JFrame {

    /**
     * Creates new form frmDetalleVenta
     */
    
    public frmPedidos parent;
    public Ventas venta;
    public Usuarios usuario;
    private boolean propina = false;
    private double valorServicio = 0;
    
    private models.DisenoFormularios desing;
    
    public frmDetalleVenta(frmPedidos p,Ventas v) {
        initComponents();
        this.parent = p;
        this.venta = v;
        
        desing.mtdDisenoPantalla(this);
        
        
        ImageIcon img = new ImageIcon(getClass().getResource("/images/icon_app.png"));
        this.setIconImage(img.getImage().getScaledInstance(180,180, Image.SCALE_SMOOTH));
        
        // 1. Le pones la fuente grande que necesitas en tu UI
        btnIncluirServicio.setFont(new Font("Segoe UI", Font.PLAIN, 26)); 

        // 2. Usas tu nueva función pasándole el componente y el tamaño en píxeles (ej: 26)
        models.DisenoFormularios.mtdAgrandarCheckBox(btnIncluirServicio, 26);
        
        
        mtdInformacionGeneral();
        mtdCargarPedidos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnInferior = new javax.swing.JPanel();
        jpnIzquierda = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        btnConfirmarVenta = new javax.swing.JButton();
        btnIncluirServicio = new javax.swing.JCheckBox();
        PanelInformacion = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblMesero = new javax.swing.JLabel();
        lblUbicacion = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        lblPedidos = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();
        jpnDerecha = new javax.swing.JPanel();
        ScrollPedidos = new javax.swing.JScrollPane();
        PanelPedidos = new javax.swing.JPanel();
        jpnDerInf = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lblTotalVenta = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblPropina = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        jpnSuperior = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblDetalle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 800));
        setMinimumSize(new java.awt.Dimension(1024, 800));
        setPreferredSize(new java.awt.Dimension(1024, 800));

        jpnInferior.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jpnInferior.setLayout(new java.awt.GridLayout(1, 0));

        jpnIzquierda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/exit.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jpnIzquierda.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 103, 87));

        btnConfirmarVenta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnConfirmarVenta.setText("Confirmar Pago");
        btnConfirmarVenta.setFocusPainted(false);
        btnConfirmarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarVentaActionPerformed(evt);
            }
        });
        jpnIzquierda.add(btnConfirmarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 270, 90));

        btnIncluirServicio.setFont(new java.awt.Font("Leelawadee", 0, 36)); // NOI18N
        btnIncluirServicio.setText("Desea Incluir Servicio");
        btnIncluirServicio.setToolTipText("");
        btnIncluirServicio.setContentAreaFilled(false);
        btnIncluirServicio.setPreferredSize(new java.awt.Dimension(600, 100));
        btnIncluirServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirServicioActionPerformed(evt);
            }
        });
        jpnIzquierda.add(btnIncluirServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 490, 62));

        PanelInformacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Información General");
        PanelInformacion.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 6, 330, 41));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Ubicación:");
        PanelInformacion.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 129, 122, 40));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Barista:");
        PanelInformacion.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 69, 122, 40));

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Valor Total:");
        PanelInformacion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 189, 122, 40));

        jLabel8.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("# de Pedidos:");
        PanelInformacion.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 249, 154, 40));

        lblMesero.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        lblMesero.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMesero.setText("Mesero:");
        PanelInformacion.add(lblMesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 71, 168, 40));

        lblUbicacion.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        lblUbicacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUbicacion.setText("Mesero:");
        PanelInformacion.add(lblUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 131, 168, 40));

        lblValorTotal.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        lblValorTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblValorTotal.setText("Mesero:");
        PanelInformacion.add(lblValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 191, 168, 40));

        lblPedidos.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        lblPedidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPedidos.setText("Mesero:");
        PanelInformacion.add(lblPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 251, 168, 40));

        jpnIzquierda.add(PanelInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 640, 340));

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/print.png"))); // NOI18N
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        jpnIzquierda.add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, -1, -1));

        jpnInferior.add(jpnIzquierda);

        jpnDerecha.setLayout(new java.awt.GridLayout(2, 0));

        ScrollPedidos.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ScrollPedidos.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        PanelPedidos.setLayout(new java.awt.GridLayout(0, 1));
        ScrollPedidos.setViewportView(PanelPedidos);

        jpnDerecha.add(ScrollPedidos);

        jpnDerInf.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Total Venta:");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jpnDerInf.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, 40));

        lblTotalVenta.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        lblTotalVenta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotalVenta.setText("$50.000");
        lblTotalVenta.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblTotalVenta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jpnDerInf.add(lblTotalVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 168, 40));

        jLabel14.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Valor Servicio:");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jpnDerInf.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 150, 40));

        lblPropina.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        lblPropina.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPropina.setText("$0.0");
        lblPropina.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblPropina.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jpnDerInf.add(lblPropina, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 168, 40));

        jLabel15.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Sub Total:");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jpnDerInf.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 150, 40));

        lblSubtotal.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        lblSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSubtotal.setText("$50.000");
        lblSubtotal.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblSubtotal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jpnDerInf.add(lblSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 168, 40));

        jpnDerecha.add(jpnDerInf);

        jpnInferior.add(jpnDerecha);

        getContentPane().add(jpnInferior, java.awt.BorderLayout.CENTER);

        jpnSuperior.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jpnSuperior.setLayout(new java.awt.GridLayout(1, 2));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logotipo_cliente_small.png"))); // NOI18N
        lblLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jpnSuperior.add(lblLogo);

        lblDetalle.setFont(new java.awt.Font("Leelawadee", 0, 36)); // NOI18N
        lblDetalle.setText("Detalles de Venta");
        lblDetalle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jpnSuperior.add(lblDetalle);

        getContentPane().add(jpnSuperior, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose(); 
        new Home_Administracion(usuario).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnConfirmarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarVentaActionPerformed
        
        btnConfirmarVenta.setVisible(false);
        this.dispose();
        if(this.venta.getEstado().equalsIgnoreCase("Pagada")){
            JOptionPane.showMessageDialog(null, "Esta Factura Ya se Cobro");
        }else{
            frmModoPago formPago = new frmModoPago(this, this.venta) ;
            formPago.setVisible(true);// TODO add your handling code here:
        }
        
        
        
    }//GEN-LAST:event_btnConfirmarVentaActionPerformed

    private void btnIncluirServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirServicioActionPerformed
            
        double SubTotal = this.venta.getTotal();
        
        if(propina){
            propina = false;
            valorServicio = 0;
            lblPropina.setText(String.valueOf(NumberFormat.getCurrencyInstance(new Locale("es", "CO")).format(valorServicio)));
            lblValorTotal.setText(String.valueOf(NumberFormat.getCurrencyInstance(new Locale("es", "CO")).format(this.venta.getTotal())));
            lblTotalVenta.setText(String.valueOf(NumberFormat.getCurrencyInstance(new Locale("es", "CO")).format(this.venta.getTotal())));
            this.venta.setValor_propina(valorServicio);
        }else{
            propina = true;
            
           valorServicio = this.venta.calcularPropina();
           this.venta.setValor_propina(valorServicio);
           
           lblPropina.setText(String.valueOf(NumberFormat.getCurrencyInstance(new Locale("es", "CO")).format(valorServicio)));
           lblValorTotal.setText(String.valueOf(NumberFormat.getCurrencyInstance(new Locale("es", "CO")).format(this.venta.getTotalConServicio(valorServicio, this.venta.getTotal()))));
           lblTotalVenta.setText(String.valueOf(NumberFormat.getCurrencyInstance(new Locale("es", "CO")).format(this.venta.getTotalConServicio(valorServicio, this.venta.getTotal()))));
           
            
        }
        
        
        
        
        


    }//GEN-LAST:event_btnIncluirServicioActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
                        // TODO add your handling code here:
                        
                        
                   Map<String,Object> params = new HashMap<String,Object>();
                        params.put("Venta", this.venta);
                        
                        try{
                        
                        JasperPrint jasperPrint = JasperFillManager.fillReport("src\\reports\\venta.jasper",params,new JREmptyDataSource());
                        
                        //JasperViewer.viewReport(jasperPrint, false);
                        JasperPrintManager.printReport(jasperPrint, false);   
                            
                        }catch (JRException ex){
                        JOptionPane.showMessageDialog(rootPane, "Error iReport: " + ex.getMessage());
                        System.err.println( "Error iReport: " + ex.getMessage() );
                        }
                        
                        
    }//GEN-LAST:event_btnImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public void mtdInformacionGeneral(){
        lblMesero.setText(this.venta.getUsuarios().getNombres()+" "+this.venta.getUsuarios().getApellidos());
        lblUbicacion.setText(this.venta.getMesas().getTipo()+" "+this.venta.getMesas().getNumero());
        lblValorTotal.setText(String.valueOf(NumberFormat.getCurrencyInstance(new Locale("es", "CO")).format(this.venta.getTotal())));
        lblPedidos.setText(String.valueOf(this.venta.getPedidoses().size()));
        lblTotalVenta.setText(String.valueOf(NumberFormat.getCurrencyInstance(new Locale("es", "CO")).format(this.venta.getTotal())));
        lblSubtotal.setText(String.valueOf(NumberFormat.getCurrencyInstance(new Locale("es", "CO")).format(this.venta.getTotal())));
    }
    
    public void mtdCargarPedidos(){
        
        
          
        
        for (Object pedidos: this.venta.getPedidoses()) {
            Pedidos dataPedido = (Pedidos) pedidos;
            
            frmDetallePedido formDetallePedido = new frmDetallePedido(this);
            formDetallePedido.mtdUbicarInformacion(dataPedido);
           
           PanelPedidos.add(formDetallePedido);
           PanelPedidos.revalidate();
           PanelPedidos.repaint();
            
        }
        
    }
    
    public static void agrandarCheckBox(JCheckBox checkBox, int ancho, int alto) {
        // 1. Obtener el icono que viene por defecto en el Look and Feel
        Icon iconoPorDefecto = UIManager.getIcon("CheckBox.icon");
        
        if (iconoPorDefecto != null) {
            // 2. Crear una imagen del tamaño que queremos
            BufferedImage img = new BufferedImage(ancho, alto, BufferedImage.TYPE_INT_ARGB);
            Graphics2D g2d = img.createGraphics();
            
            // Habilitar anti-aliasing para que no se vea pixelado al estirarse
            g2d.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR); 
            
            // 3. Dibujar el icono original escalado dentro de la nueva imagen
            iconoPorDefecto.paintIcon(checkBox, g2d, 0, 0);
            g2d.dispose();
            
            // 4. Asignar el nuevo icono escalado al CheckBox
            Icon iconoGrande = new ImageIcon(img.getScaledInstance(ancho, alto, Image.SCALE_SMOOTH));
            checkBox.setIcon(iconoGrande);
            
            // Opcional: También puedes definir el icono para cuando esté seleccionado
            // si notas que no cambia visualmente al hacer clic
            checkBox.setSelectedIcon(iconoGrande); 
        }
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelInformacion;
    private javax.swing.JPanel PanelPedidos;
    private javax.swing.JScrollPane ScrollPedidos;
    private javax.swing.JButton btnConfirmarVenta;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JCheckBox btnIncluirServicio;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jpnDerInf;
    private javax.swing.JPanel jpnDerecha;
    private javax.swing.JPanel jpnInferior;
    private javax.swing.JPanel jpnIzquierda;
    private javax.swing.JPanel jpnSuperior;
    private javax.swing.JLabel lblDetalle;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMesero;
    private javax.swing.JLabel lblPedidos;
    private javax.swing.JLabel lblPropina;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotalVenta;
    private javax.swing.JLabel lblUbicacion;
    private javax.swing.JLabel lblValorTotal;
    // End of variables declaration//GEN-END:variables
}
