/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.administracion;

import static java.awt.image.ImageObserver.WIDTH;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
//import models.TmUsuarios;

import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.NumberFormat;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import models.Facturas;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
//import models.TmProductos;
/**
 *
 * @author bcristan
 */
public class frmDetallePedidoProveedor extends javax.swing.JFrame {
   
    private List<models.Facturas> listFacturas;
    private Facturas facturaDetalle;
    //private TmProductos modelo;
    
    models.Facturas clFactura = new models.Facturas();
    //
    private Home_Administracion Parent;
    
    /**
     * Creates new form Usuarios
     */
    public frmDetallePedidoProveedor(Home_Administracion P,Facturas f) {
        
        initComponents();
        this.Parent = P;
        this.setLocationRelativeTo(this);
        ImageIcon img = new ImageIcon(getClass().getResource("/images/icon_app.png"));
        this.setIconImage(img.getImage().getScaledInstance(180,180, Image.SCALE_SMOOTH));
        this.setTitle("POSystem - Powered by &Source Ltda");
        this.facturaDetalle = f;
        
        listFacturas = new ArrayList<>();
        listFacturas = clFactura.listarFacturas();
        lblInfoFactura.setText("<html>Factura N°. "+facturaDetalle.getCodigo()+" <br> Proveedor: "+facturaDetalle.getNombreProveedor()+"</html>");
        DefaultTableModel df = (DefaultTableModel) TablaProductos.getModel();
            
        for (models.Ingresoproductos dataPed:facturaDetalle.getPedidos()) {
            double totalFactura = dataPed.getCostoIngreso() * dataPed.getCantidad();
          df.addRow(new Object[]{dataPed,dataPed.getIdIngresoProducto(),dataPed.getProductos().getNombre(),dataPed.getCantidad(),String.valueOf(NumberFormat.getCurrencyInstance(new Locale("es", "CO")).format(dataPed.getCostoIngreso())),String.valueOf(NumberFormat.getCurrencyInstance(new Locale("es", "CO")).format(totalFactura)),dataPed.getFecha()  });
        }
        TablaProductos.setModel(df);
        
        /*Home_Administracion form = Parent;
        frmListadoPedidosProveedores listForm = this;
        
            jTProductos.addMouseListener(new java.awt.event.MouseAdapter(){
            public void mousePressed(MouseEvent me) {
            
                if (me.getClickCount() == 2) {
                        int fila = jTProductos.getSelectedRow();
                      
                        models.Productos p = (models.Productos) jTProductos.getValueAt(fila, 0);
                        
                        if(p.getTipoVenta().equalsIgnoreCase("Unidad")){
                         new frmUpdateProducto(form, p).setVisible(true);
                         listForm.dispose();
                         //JOptionPane.showMessageDialog(null, "algo esta pasando"); 
                         
                        }
                }
             }
            });
 */        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBExit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        lblInfoFactura = new javax.swing.JLabel();

        jPopupMenu1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPopupMenu1.setToolTipText("Modificar");
        jPopupMenu1.setName("Modificar"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logotipo_cliente_small.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 250, 179));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("PRODUCTOS INGRESADOS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 520, -1));

        jBExit.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jBExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/exit.png"))); // NOI18N
        jBExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitActionPerformed(evt);
            }
        });
        getContentPane().add(jBExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 518, 160, 61));

        TablaProductos.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Modelo", "Codigo", "Nombre Producto", "Cantidad", "Valor Individual", "", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaProductos);
        if (TablaProductos.getColumnModel().getColumnCount() > 0) {
            TablaProductos.getColumnModel().getColumn(0).setMinWidth(0);
            TablaProductos.getColumnModel().getColumn(0).setPreferredWidth(0);
            TablaProductos.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 800, 250));

        lblInfoFactura.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        lblInfoFactura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblInfoFactura.setText("jLabel3");
        getContentPane().add(lblInfoFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 88, 430, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitActionPerformed
       this.dispose();
       new Home_Administracion().setVisible(true);
    }//GEN-LAST:event_jBExitActionPerformed

    private void TablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaProductosMouseClicked
   
// TODO add your handling code here:
    }//GEN-LAST:event_TablaProductosMouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaProductos;
    private javax.swing.JButton jBExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblInfoFactura;
    // End of variables declaration//GEN-END:variables
}
