/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.administracion;

import static java.awt.image.ImageObserver.WIDTH;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
//import models.TmUsuarios;

import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.NumberFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import models.Operaciones;
import models.*;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
//import models.TmProductos;
/**
 *
 * @author bcristan
 */
public class frmListadoOperaciones extends javax.swing.JFrame {
   
    private List<models.Operaciones> listOperaciones;
    //private TmProductos modelo;
    public static Boolean Actualizar;
    public static String idproductoactualizar;
    models.Operaciones clOperaciones = new models.Operaciones();
    //
    private Home_Administracion Parent;
    private Turnos turno;
    
    public static models.Usuarios admin;
    
    /**
     * Creates new form Usuarios
     */
    public frmListadoOperaciones(Home_Administracion P,Turnos turn) {
        
        
        
        initComponents();
        
        this.pack(); // Calcula tamaños
        this.setLocationRelativeTo(null);
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        
        
        this.Parent = P;
        this.turno = turn;
        this.setLocationRelativeTo(this);
        ImageIcon img = new ImageIcon(getClass().getResource("/images/icon_app.png"));
        this.setIconImage(img.getImage().getScaledInstance(180,180, Image.SCALE_SMOOTH));
        this.setTitle("POSystem - Powered by KIM-Solutions");
        
        
        listOperaciones = new ArrayList<>();
        listOperaciones = clOperaciones.mtdListOperaciones(turno.getIdTurno());
      
        DefaultTableModel df = (DefaultTableModel) TablaOperaciones.getModel();
         
            
        for (Operaciones dataOperacion:listOperaciones) {
            
           df.addRow(new Object[]{dataOperacion,dataOperacion.getIdOperacion(),dataOperacion.getTipo(),dataOperacion.getConceptosOperaciones().getNombre(),dataOperacion.getFecha(),dataOperacion.getValor(),dataOperacion.getConcepto()});
        }
        
        
        TablaOperaciones.setRowHeight(TablaOperaciones.getFontMetrics(TablaOperaciones.getFont()).getHeight() + 2);
        TablaOperaciones.getColumnModel().getColumn(1).setPreferredWidth(15);
        TablaOperaciones.revalidate(); // Fuerza a la interfaz a recalcular el diseño
        TablaOperaciones.repaint();   // Fuerza el repintado visual
        
        TablaOperaciones.setModel(df);
        
       /* Home_Administracion form = Parent;
        frmListadoOperaciones listForm = this;
        
            TablaOperaciones.addMouseListener(new java.awt.event.MouseAdapter(){
            public void mousePressed(MouseEvent me) {
            
                if (me.getClickCount() == 2) {
                        int fila = TablaOperaciones.getSelectedRow();
                      
                        Operaciones p = (Operaciones) TablaOperaciones.getValueAt(fila, 0);
                        
                       
                }
             }
            });
        */
        

    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBExit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaOperaciones = new javax.swing.JTable();
        btnIngresar = new javax.swing.JButton();
        txtFiltro = new javax.swing.JTextField();
        btnFiltro = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnConceptos = new javax.swing.JButton();

        jPopupMenu1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPopupMenu1.setToolTipText("Modificar");
        jPopupMenu1.setName("Modificar"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logotipo_cliente_small.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 13, 170, 179));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel2.setText("Gestion de Operaciones");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, 430, 50));

        jBExit.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jBExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/exit.png"))); // NOI18N
        jBExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitActionPerformed(evt);
            }
        });
        getContentPane().add(jBExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 570, 160, 90));

        TablaOperaciones.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        TablaOperaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Modelo", "Codigo", "Tipo", "Concepto", "Fecha", "Valor", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaOperaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaOperacionesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaOperaciones);
        if (TablaOperaciones.getColumnModel().getColumnCount() > 0) {
            TablaOperaciones.getColumnModel().getColumn(0).setMinWidth(0);
            TablaOperaciones.getColumnModel().getColumn(0).setPreferredWidth(0);
            TablaOperaciones.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 1100, 300));

        btnIngresar.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        btnIngresar.setText("Registrar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 560, 190, 110));

        txtFiltro.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        getContentPane().add(txtFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, 370, 50));

        btnFiltro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/reload.png"))); // NOI18N
        btnFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroActionPerformed(evt);
            }
        });
        getContentPane().add(btnFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 180, 90, 50));

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/print.png"))); // NOI18N
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 570, -1, -1));

        btnConceptos.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        btnConceptos.setText("Conceptos");
        btnConceptos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConceptosActionPerformed(evt);
            }
        });
        getContentPane().add(btnConceptos, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 560, 190, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitActionPerformed
       this.dispose();
       new Home_Administracion(admin).setVisible(true);
    }//GEN-LAST:event_jBExitActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        frmRegistrarOperacion.turno = turno ;
        frmRegistrarOperacion.admin = admin;
         this.setVisible(false);
        new frmRegistrarOperacion(Parent).setVisible(true);           // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void TablaOperacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaOperacionesMouseClicked
   
// TODO add your handling code here:
    }//GEN-LAST:event_TablaOperacionesMouseClicked

    private void btnFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroActionPerformed
       
       DefaultTableModel model = (DefaultTableModel) TablaOperaciones.getModel();
       model.setRowCount(0);  
       TablaOperaciones.setModel(model);
       
       
        listOperaciones = new ArrayList<>();
         listOperaciones = clOperaciones.mtdFiltro(txtFiltro.getText(),turno.getIdTurno());
      
         if(listOperaciones.size() <= 0){
        
                JOptionPane.showMessageDialog(null, " No se Encontraron Resultados para "+txtFiltro.getText(),"Informacion",JOptionPane.INFORMATION_MESSAGE);
                listOperaciones = clOperaciones.mtdListOperaciones(turno.getIdTurno());
        }
         
         
        DefaultTableModel df = (DefaultTableModel) TablaOperaciones.getModel();
            
        for (Operaciones dataOperacion:listOperaciones) {
            
           df.addRow(new Object[]{dataOperacion,dataOperacion.getIdOperacion(),dataOperacion.getTipo(),dataOperacion.getConceptosOperaciones().getNombre(),dataOperacion.getFecha(),dataOperacion.getValor(),dataOperacion.getConcepto()});
        }
        TablaOperaciones.setModel(df);       // TODO add your handling code here: 
     
    }//GEN-LAST:event_btnFiltroActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
           Calendar calendario = Calendar.getInstance();
            Date date = calendario.getTime(); 
            
            int fila = TablaOperaciones.getSelectedRow();
            
           if(fila < 0){
                 JOptionPane.showMessageDialog(null, " Seleccione un Operacion Para Imprimir","Informacion",JOptionPane.INFORMATION_MESSAGE);
           }else{
               
                
                Operaciones p = (Operaciones) TablaOperaciones.getValueAt(fila, 0);
            
            Map<String,Object> params = new HashMap<String,Object>();
            params.put("fecha", date);
            params.put("operacion", p);
                
            JasperPrint jasperPrint;
            try {
                jasperPrint = JasperFillManager.fillReport("src/reports/operaciones.jasper",params,new JREmptyDataSource());
                JasperPrintManager.printReport(jasperPrint, false); 
            } catch (JRException ex) {
                Logger.getLogger(frmRegistrarProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
           }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnConceptosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConceptosActionPerformed
            
            frmListadoConceptosOperacion.usuario = admin;
            this.dispose();
            new frmListadoConceptosOperacion(Parent).setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnConceptosActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       this.dispose();
       new Home_Administracion(admin).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaOperaciones;
    private javax.swing.JButton btnConceptos;
    private javax.swing.JButton btnFiltro;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton jBExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
