/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.administracion;

import static java.awt.image.ImageObserver.WIDTH;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
//import models.TmUsuarios;

import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.NumberFormat;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import models.Facturas;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
//import models.TmProductos;
/**
 *
 * @author bcristan
 */
public class frmListadoPedidosProveedores extends javax.swing.JFrame {
   
    private List<models.Facturas> listFacturas;
    //private TmProductos modelo;
    
    models.Facturas clFactura = new models.Facturas();
    //
    private Home_Administracion Parent;
    
    /**
     * Creates new form Usuarios
     */
    public frmListadoPedidosProveedores(Home_Administracion P) {
        
        initComponents();
        this.Parent = P;
        this.setLocationRelativeTo(this);
        ImageIcon img = new ImageIcon(getClass().getResource("/images/icon_app.png"));
        this.setIconImage(img.getImage().getScaledInstance(180,180, Image.SCALE_SMOOTH));
        this.setTitle("POSystem - Powered by &Source Ltda");
        
        
        listFacturas = new ArrayList<>();
        listFacturas = clFactura.listarFacturas();
      
        DefaultTableModel df = (DefaultTableModel) TablaFacturas.getModel();
            
        for (models.Facturas dataPed:listFacturas) {
            
          df.addRow(new Object[]{dataPed,dataPed.getIdFactura(),dataPed.getCodigo(),dataPed.getNombreProveedor(),String.valueOf(NumberFormat.getCurrencyInstance(new Locale("es", "CO")).format(dataPed.getTotal())),dataPed.getFecha()  });
        }
        TablaFacturas.setModel(df);
        
        Home_Administracion form = Parent;
        frmListadoPedidosProveedores listForm = this;
        
            TablaFacturas.addMouseListener(new java.awt.event.MouseAdapter(){
            public void mousePressed(MouseEvent me) {
            
                if (me.getClickCount() == 2) {
                        int fila = TablaFacturas.getSelectedRow();
                      
                        models.Facturas p = (models.Facturas) TablaFacturas.getValueAt(fila, 0);
                        
                       listForm.dispose();
                       new frmDetallePedidoProveedor(Parent, p).setVisible(true);
                }
             }
            });
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBExit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaFacturas = new javax.swing.JTable();
        btnImprimir = new javax.swing.JButton();
        txtFiltro = new javax.swing.JTextField();
        btnFiltro = new javax.swing.JButton();

        jPopupMenu1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPopupMenu1.setToolTipText("Modificar");
        jPopupMenu1.setName("Modificar"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logotipo_cliente_small.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 250, 179));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel2.setText("Gestión de Facturas de Compra");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 560, -1));

        jBExit.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jBExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/exit.png"))); // NOI18N
        jBExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitActionPerformed(evt);
            }
        });
        getContentPane().add(jBExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 518, 160, 61));

        TablaFacturas.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        TablaFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Modelo", "Codigo", "Factura N°", "Proveedor", "Valor Total", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaFacturasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaFacturas);
        if (TablaFacturas.getColumnModel().getColumnCount() > 0) {
            TablaFacturas.getColumnModel().getColumn(0).setMinWidth(0);
            TablaFacturas.getColumnModel().getColumn(0).setPreferredWidth(0);
            TablaFacturas.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 800, 250));

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/print.png"))); // NOI18N
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, -1, -1));

        txtFiltro.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        getContentPane().add(txtFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 370, 50));

        btnFiltro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/reload.png"))); // NOI18N
        btnFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroActionPerformed(evt);
            }
        });
        getContentPane().add(btnFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, 90, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitActionPerformed
       this.dispose();
       new Home_Administracion().setVisible(true);
    }//GEN-LAST:event_jBExitActionPerformed

    private void TablaFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaFacturasMouseClicked
   
// TODO add your handling code here:
    }//GEN-LAST:event_TablaFacturasMouseClicked

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
              
       
              int fila = TablaFacturas.getSelectedRow();
            
           if(fila < 0){
                 JOptionPane.showMessageDialog(null, " Seleccione un Operacion Para Imprimir","Informacion",JOptionPane.INFORMATION_MESSAGE);
           }else{
               
                
                Facturas p = (Facturas) TablaFacturas.getValueAt(fila, 0);
            
           Map<String,Object> params = new HashMap<String,Object>();
                 params.put("factura", p);
                 
                 
                 
                JasperPrint jasperPrint;
                
                
        try {
            jasperPrint = JasperFillManager.fillReport("src/reports/ingreso_pedido.jasper",params,new JREmptyDataSource());
            JasperPrintManager.printReport(jasperPrint, false); 
        } catch (JRException ex) {
            Logger.getLogger(frmRegistrarProductos.class.getName()).log(Level.SEVERE, null, ex);
        }finally{ this.dispose(); Parent.setVisible(true);}
           }
        
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroActionPerformed
       
       DefaultTableModel model = (DefaultTableModel) TablaFacturas.getModel();
       model.setRowCount(0);  
       TablaFacturas.setModel(model);
        listFacturas = new ArrayList<>();
        listFacturas = clFactura.mtdFiltro(txtFiltro.getText());
      
        if(listFacturas.size() <= 0){
        
                JOptionPane.showMessageDialog(null, " No se Encontraron Resultados para "+txtFiltro.getText(),"Informacion",JOptionPane.INFORMATION_MESSAGE);
                listFacturas = clFactura.listarFacturas();
        }
        
         DefaultTableModel df = (DefaultTableModel) TablaFacturas.getModel();
            
        for (models.Facturas dataPed:listFacturas) {
            
          df.addRow(new Object[]{dataPed,dataPed.getIdFactura(),dataPed.getCodigo(),dataPed.getNombreProveedor(),dataPed.getFecha()  });
        }
        TablaFacturas.setModel(df);   // TODO add your handling code here: 
     
    }//GEN-LAST:event_btnFiltroActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaFacturas;
    private javax.swing.JButton btnFiltro;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton jBExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
