/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.administracion;

import static java.awt.image.ImageObserver.WIDTH;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
//import models.TmUsuarios;

import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import models.Usuarios;
//import models.TmMesas;
/**
 *
 * @author bcristan
 */
public class frmListarMesas extends javax.swing.JFrame {
    private List<models.Mesas> lisMesas;
    //private TmMesas modelomesas;
        private Home_Administracion Parent;
         private Usuarios usuario;
    /**
     * Creates new form Usuarios
     */
    public frmListarMesas(Home_Administracion p) {
        initComponents();
        this.Parent = p;
         this.setLocationRelativeTo(this);
        ImageIcon img = new ImageIcon(getClass().getResource("/images/icon_app.png"));
        this.setIconImage(img.getImage().getScaledInstance(180,180, Image.SCALE_SMOOTH));
        this.setTitle("POSystem - Powered by KIM-Solutions");
        

        models.Mesas mesa = new models.Mesas();
        lisMesas = new ArrayList<>();
        lisMesas = mesa.listarmesas();
       
        DefaultTableModel df = (DefaultTableModel) TablaMesas.getModel();
        
        TablaMesas.removeColumn(TablaMesas.getColumnModel().getColumn(1));
            
            for (models.Mesas dataMesa:lisMesas) {
                
                df.addRow(new Object[]{dataMesa, dataMesa.getIdMesa(),dataMesa.getTipo(),dataMesa.getNumero(),dataMesa.getEstado() });
                
            }
            
                    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
                    centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

                    // Aplicamos a las columnas que el usuario sí ve (2, 3 y 4)
                    TablaMesas.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
                    TablaMesas.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
                    TablaMesas.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
            
            Home_Administracion form = Parent;
        frmListarMesas listForm = this;
        
             TablaMesas.addMouseListener(new java.awt.event.MouseAdapter(){
            public void mousePressed(MouseEvent me) {
            
                if (me.getClickCount() == 2) {
                        int fila = TablaMesas.getSelectedRow();
                      
                        models.Mesas p = (models.Mesas) TablaMesas.getValueAt(fila, 0);
                        
                        
                         new frmRegistrarMesa(form,"Update",p).setVisible(true);
                         listForm.dispose();
                         //JOptionPane.showMessageDialog(null, "algo esta pasando"); 
                         
                        
                }
             }
            });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMesas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jBDelete12 = new javax.swing.JButton();
        jBExit = new javax.swing.JButton();

        jPopupMenu1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPopupMenu1.setToolTipText("Modificar");
        jPopupMenu1.setName("Modificar"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 800));
        setMinimumSize(new java.awt.Dimension(1024, 800));
        setPreferredSize(new java.awt.Dimension(1024, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logotipo_cliente_small.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 11, 250, 179));

        TablaMesas.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        TablaMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "modelo", "Codigo", "Tipo", "Número", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaMesas.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(TablaMesas);
        if (TablaMesas.getColumnModel().getColumnCount() > 0) {
            TablaMesas.getColumnModel().getColumn(0).setMinWidth(0);
            TablaMesas.getColumnModel().getColumn(0).setPreferredWidth(0);
            TablaMesas.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 800, 308));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel2.setText("Gestion Mesas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 265, 32));

        jBDelete12.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        jBDelete12.setText(" Nueva");
        jBDelete12.setToolTipText("");
        jBDelete12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDelete12ActionPerformed(evt);
            }
        });
        getContentPane().add(jBDelete12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 150, 39));

        jBExit.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jBExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/exit.png"))); // NOI18N
        jBExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitActionPerformed(evt);
            }
        });
        getContentPane().add(jBExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 550, 160, 61));

        pack();
    }// </editor-fold>//GEN-END:initComponents
     /* Funcion : Abrir frame CMesas
    Nota :   toma  la fila selccionada  y envia los datos al frame CUsuarios
  * Desarrollador :(Brayan cristancho) 
  * Fecha de creacion : 04/08/2018**/
    private void jBDelete12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDelete12ActionPerformed
        this.dispose();
        new frmRegistrarMesa(Parent,"Create",new models.Mesas()).setVisible(true);
       
    }//GEN-LAST:event_jBDelete12ActionPerformed

    private void jBExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitActionPerformed
        this.dispose();
        new Home_Administracion(usuario).setVisible(true);
    }//GEN-LAST:event_jBExitActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaMesas;
    private javax.swing.JButton jBDelete12;
    private javax.swing.JButton jBExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
