/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.administracion;

import java.awt.Image;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import models.Usuarios;

/**
 *
 * @author Usuario
 */
public class frmListadoUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form frmListadoUsuarios
     */
    
    private  Home_Administracion Parent;
    private List<models.Usuarios> ListUsuarios;
     private Usuarios usuario;
    
    
    public frmListadoUsuarios(Home_Administracion P) {
        initComponents();
         this.Parent = P;
        this.setLocationRelativeTo(this);
        ImageIcon img = new ImageIcon(getClass().getResource("/images/icon_app.png"));
        this.setIconImage(img.getImage().getScaledInstance(180,180, Image.SCALE_SMOOTH));
        this.setTitle("POSystem - Powered by KIM-Solutions");
        
        models.Usuarios user = new models.Usuarios();
            ListUsuarios = new ArrayList<>();
            ListUsuarios = user.listarusuarios();
            
            DefaultTableModel df = (DefaultTableModel) TblUsuarios.getModel();
            
            for (models.Usuarios dataUsuario:ListUsuarios) {
                
                df.addRow(new Object[]{dataUsuario, dataUsuario.getIdUsuario(),dataUsuario.getNombres(),dataUsuario.getApellidos(),dataUsuario.getPerfil(),dataUsuario.getEstado() });
                
            }
            
        Home_Administracion form = Parent;
        frmListadoUsuarios listForm = this;
        
             TblUsuarios.addMouseListener(new java.awt.event.MouseAdapter(){
            public void mousePressed(MouseEvent me) {
            
                if (me.getClickCount() == 2) {
                        int fila = TblUsuarios.getSelectedRow();
                      
                        models.Usuarios p = (models.Usuarios) TblUsuarios.getValueAt(fila, 0);
                        
                        
                         new frmRegistrarUsuario(form,"Update",p).setVisible(true);
                         listForm.dispose();
                         //JOptionPane.showMessageDialog(null, "algo esta pasando"); 
                         
                        
                }
             }
            });
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblUsuarios = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        jBExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 800));
        setMinimumSize(new java.awt.Dimension(1024, 800));
        setPreferredSize(new java.awt.Dimension(1024, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logotipo_cliente_small.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 13, 250, 179));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel2.setText("Gestion de Usuarios");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 108, 382, 32));

        TblUsuarios.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        TblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Modelo", "Codigo", "Nombres", "Apellidos", "Perfil", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TblUsuarios);
        if (TblUsuarios.getColumnModel().getColumnCount() > 0) {
            TblUsuarios.getColumnModel().getColumn(0).setMinWidth(0);
            TblUsuarios.getColumnModel().getColumn(0).setPreferredWidth(0);
            TblUsuarios.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 800, 250));

        btnNuevo.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        btnNuevo.setText("Nuevo ");
        btnNuevo.setToolTipText("");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 240, 39));

        jBExit.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jBExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/exit.png"))); // NOI18N
        jBExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitActionPerformed(evt);
            }
        });
        getContentPane().add(jBExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 518, 160, 61));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblUsuariosMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_TblUsuariosMouseClicked

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        this.dispose();
        new frmRegistrarUsuario(Parent,"Create",new models.Usuarios()).setVisible(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void jBExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitActionPerformed
        this.dispose();
       new Home_Administracion(usuario).setVisible(true);
    }//GEN-LAST:event_jBExitActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblUsuarios;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton jBExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
