/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.administracion;

import static java.awt.image.ImageObserver.WIDTH;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
//import models.TmUsuarios;

import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.NumberFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import models.Operaciones;
import models.*;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
//import models.TmProductos;
/**
 *
 * @author bcristan
 */
public class frmListadoConceptosOperacion extends javax.swing.JFrame {
   
    private List<models.ConceptosOperaciones> listConceptos;
    //private TmProductos modelo;
    models.ConceptosOperaciones clConceptosOperaciones = new models.ConceptosOperaciones();
    //
    private Home_Administracion Parent;
     public static Usuarios usuario;
    
    /**
     * Creates new form Usuarios
     */
    public frmListadoConceptosOperacion(Home_Administracion P) {
        
        
        
        initComponents();
        
        this.pack(); // Calcula tamaños
        this.setLocationRelativeTo(null);
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.Parent = P;
       
        ImageIcon img = new ImageIcon(getClass().getResource("/images/icon_app.png"));
        this.setIconImage(img.getImage().getScaledInstance(180,180, Image.SCALE_SMOOTH));
        this.setTitle("POSystem - Powered by KIM-Solutions");
        
        
        listConceptos = new ArrayList<>();
        listConceptos = clConceptosOperaciones.listarConceptos();
      
        DefaultTableModel df = (DefaultTableModel) TablaConceptoOperaciones.getModel();
            
        for (ConceptosOperaciones dataConcepto:listConceptos) {
            
           df.addRow(new Object[]{dataConcepto,dataConcepto.getIdConceptoOperacion(),dataConcepto.getNombre(),dataConcepto.getDescripcion()});
        }
        
        TablaConceptoOperaciones.setRowHeight(TablaConceptoOperaciones.getFontMetrics(TablaConceptoOperaciones.getFont()).getHeight() + 2);
        TablaConceptoOperaciones.getColumnModel().getColumn(1).setPreferredWidth(15);
        TablaConceptoOperaciones.revalidate(); // Fuerza a la interfaz a recalcular el diseño
        TablaConceptoOperaciones.repaint();   // Fuerza el repintado visual
        
        TablaConceptoOperaciones.setModel(df);
        
        Home_Administracion form = Parent;
        frmListadoConceptosOperacion listForm = this;
        
            TablaConceptoOperaciones.addMouseListener(new java.awt.event.MouseAdapter(){
            public void mousePressed(MouseEvent me) {
            
                if (me.getClickCount() == 2) {
                        int fila = TablaConceptoOperaciones.getSelectedRow();
                      
                        ConceptosOperaciones p = (ConceptosOperaciones) TablaConceptoOperaciones.getValueAt(fila, 0);
                        
                        frmRegistrarConceptoOperacion.usuario = usuario;
                        listForm.dispose();
                        new frmRegistrarConceptoOperacion(Parent, "update", p).setVisible(true);
                       
                }
             }
            });
        
        

    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBExit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaConceptoOperaciones = new javax.swing.JTable();
        btnIngresar = new javax.swing.JButton();
        txtFiltro = new javax.swing.JTextField();
        btnFiltro = new javax.swing.JButton();

        jPopupMenu1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPopupMenu1.setToolTipText("Modificar");
        jPopupMenu1.setName("Modificar"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1900, 1020));
        setMinimumSize(new java.awt.Dimension(1900, 1020));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logotipo_cliente_small.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 164, 193));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel2.setText("Gestion de Operaciones");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, 430, 50));

        jBExit.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jBExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/exit.png"))); // NOI18N
        jBExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitActionPerformed(evt);
            }
        });
        getContentPane().add(jBExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 820, 120, 80));

        TablaConceptoOperaciones.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        TablaConceptoOperaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Modelo", "Codigo", "Nombre", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaConceptoOperaciones.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        TablaConceptoOperaciones.setAutoscrolls(false);
        TablaConceptoOperaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaConceptoOperacionesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaConceptoOperaciones);
        if (TablaConceptoOperaciones.getColumnModel().getColumnCount() > 0) {
            TablaConceptoOperaciones.getColumnModel().getColumn(0).setMinWidth(0);
            TablaConceptoOperaciones.getColumnModel().getColumn(0).setPreferredWidth(0);
            TablaConceptoOperaciones.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 320, 1480, 469));

        btnIngresar.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        btnIngresar.setText("Nuevo");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 820, 150, 90));

        txtFiltro.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        getContentPane().add(txtFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 230, 370, 50));

        btnFiltro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/reload.png"))); // NOI18N
        btnFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroActionPerformed(evt);
            }
        });
        getContentPane().add(btnFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 230, 90, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitActionPerformed
       this.dispose();
       new Home_Administracion(usuario).setVisible(true);
    }//GEN-LAST:event_jBExitActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
       
        
        frmRegistrarConceptoOperacion.usuario = usuario;
         this.setVisible(false);
        new frmRegistrarConceptoOperacion(Parent,"Create",new ConceptosOperaciones()).setVisible(true);           // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void TablaConceptoOperacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaConceptoOperacionesMouseClicked
   
// TODO add your handling code here:
    }//GEN-LAST:event_TablaConceptoOperacionesMouseClicked

    private void btnFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroActionPerformed
       
       DefaultTableModel model = (DefaultTableModel) TablaConceptoOperaciones.getModel();
       model.setRowCount(0);  
       TablaConceptoOperaciones.setModel(model);
       
       
        listConceptos = new ArrayList<>();
         listConceptos = clConceptosOperaciones.mtdFiltro(txtFiltro.getText());
      
         if(listConceptos.size() <= 0){
        
                JOptionPane.showMessageDialog(null, " No se Encontraron Resultados para "+txtFiltro.getText(),"Informacion",JOptionPane.INFORMATION_MESSAGE);
                listConceptos = clConceptosOperaciones.listarConceptos();
        }
         
         
        DefaultTableModel df = (DefaultTableModel) TablaConceptoOperaciones.getModel();
            
        for (ConceptosOperaciones dataConcepto:listConceptos) {
            
           df.addRow(new Object[]{dataConcepto,dataConcepto.getIdConceptoOperacion(),dataConcepto.getNombre(),dataConcepto.getDescripcion()});
        }
        TablaConceptoOperaciones.setModel(df);       // TODO add your handling code here: 
     
    }//GEN-LAST:event_btnFiltroActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       this.dispose();
       new Home_Administracion(usuario).setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaConceptoOperaciones;
    private javax.swing.JButton btnFiltro;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton jBExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
