/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.administracion;

import static java.awt.image.ImageObserver.WIDTH;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
//import models.TmUsuarios;

import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.ImageIcon;
import models.Turnos;
import models.Usuarios;
//import models.TmProductos;
/**
 *
 * @author bcristan
 */
public class frmListadoProductos extends javax.swing.JFrame {
   
    private List<models.Productos> listProductos;
    //private TmProductos modelo;
    public static Boolean Actualizar;
    public static String idproductoactualizar;
    models.Productos clProducto = new models.Productos();
    //
    private Home_Administracion Parent;
     public static Usuarios usuario;
    
    /**
     * Creates new form Usuarios
     */
    public frmListadoProductos(Home_Administracion P) {
        
        initComponents();
        this.Parent = P;
        this.setLocationRelativeTo(this);
        ImageIcon img = new ImageIcon(getClass().getResource("/images/icon_app.png"));
        this.setIconImage(img.getImage().getScaledInstance(180,180, Image.SCALE_SMOOTH));
        this.setTitle("POSystem - Powered by KIM-Solutions");
        
        
        listProductos = new ArrayList<>();
        listProductos = clProducto.mtdlistarProductos();
      
        DefaultTableModel df = (DefaultTableModel) jTProductos.getModel();
            
        for (models.Productos dataProducto:listProductos) {
            
            BigDecimal stockServicio = dataProducto.getStock();
           int stoServicio = stockServicio.setScale(0, RoundingMode.DOWN).intValueExact();
            
        df.addRow(new Object[]{dataProducto, dataProducto.getCodigoBarras(),dataProducto.getNombre(),dataProducto.getCategorias(),String.valueOf(NumberFormat.getCurrencyInstance(new Locale("es", "CO")).format(dataProducto.getCosto())),String.valueOf(NumberFormat.getCurrencyInstance(new Locale("es", "CO")).format(dataProducto.getValor(/*dataProducto.getIdProducto()*/))),stoServicio });
        }
        
        jTProductos.setRowHeight(jTProductos.getFontMetrics(jTProductos.getFont()).getHeight() + 2);
        jTProductos.getColumnModel().getColumn(1).setPreferredWidth(15);
        jTProductos.revalidate(); // Fuerza a la interfaz a recalcular el diseño
        jTProductos.repaint();   // Fuerza el repintado visual
        jTProductos.setModel(df);
        
        Home_Administracion form = Parent;
        frmListadoProductos listForm = this;
        
            jTProductos.addMouseListener(new java.awt.event.MouseAdapter(){
            public void mousePressed(MouseEvent me) {
            
                if (me.getClickCount() == 2) {
                        int fila = jTProductos.getSelectedRow();
                      
                        models.Productos p = (models.Productos) jTProductos.getValueAt(fila, 0);
                        
                        if(p.getTipoVenta().equalsIgnoreCase("Unidad")){
                            
                         frmUpdateProducto.usuario = usuario;   
                            
                         new frmUpdateProducto(form, p).setVisible(true);
                         listForm.dispose();
                         //JOptionPane.showMessageDialog(null, "algo esta pasando"); 
                         
                        }
                }
             }
            });
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBExit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTProductos = new javax.swing.JTable();
        btnIngresar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        txtFiltro = new javax.swing.JTextField();
        btnFiltro = new javax.swing.JButton();

        jPopupMenu1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPopupMenu1.setToolTipText("Modificar");
        jPopupMenu1.setName("Modificar"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 800));
        setMinimumSize(new java.awt.Dimension(1024, 800));
        setPreferredSize(new java.awt.Dimension(1024, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logotipo_cliente_small.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 13, 250, 179));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel2.setText("Gestion de Productos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 382, 32));

        jBExit.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jBExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/exit.png"))); // NOI18N
        jBExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitActionPerformed(evt);
            }
        });
        getContentPane().add(jBExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 518, 160, 61));

        jTProductos.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        jTProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Modelo", "Codigo", "Producto", "Categoria", "V. Compra", "V. Venta", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTProductos);
        if (jTProductos.getColumnModel().getColumnCount() > 0) {
            jTProductos.getColumnModel().getColumn(0).setMinWidth(0);
            jTProductos.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTProductos.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 800, 250));

        btnIngresar.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 190, 40));

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/print.png"))); // NOI18N
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, -1, -1));

        txtFiltro.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        getContentPane().add(txtFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 370, 50));

        btnFiltro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/reload.png"))); // NOI18N
        btnFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroActionPerformed(evt);
            }
        });
        getContentPane().add(btnFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, 90, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitActionPerformed
       this.dispose();
      new Home_Administracion(usuario).setVisible(true);
    }//GEN-LAST:event_jBExitActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        
        frmRegistrarFactura.usuario = usuario;
        this.dispose();
        new frmRegistrarFactura(Parent).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void jTProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTProductosMouseClicked
   
// TODO add your handling code here:
    }//GEN-LAST:event_jTProductosMouseClicked

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
                
        List<Turnos> turno = new ArrayList<Turnos>();
       Turnos Objturno =  new Turnos();
       //turno = Objturno.mtdLastTurno();
        Parent.printReportInventario(Objturno.mtdLastTurno());
        
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroActionPerformed
       
       DefaultTableModel model = (DefaultTableModel) jTProductos.getModel();
       model.setRowCount(0);  
       jTProductos.setModel(model);
        listProductos = new ArrayList<>();
        listProductos = clProducto.mtdFiltro(txtFiltro.getText());
      
        if(listProductos.size() <= 0){
        
                JOptionPane.showMessageDialog(null, " No se Encontraron Resultados para "+txtFiltro.getText(),"Informacion",JOptionPane.INFORMATION_MESSAGE);
                listProductos = clProducto.mtdlistarProductos();
        }
        
        DefaultTableModel df = (DefaultTableModel) jTProductos.getModel();

        for (models.Productos dataProducto:listProductos) {

            BigDecimal stockServicio = dataProducto.getStock();
           int stoServicio = stockServicio.setScale(0, RoundingMode.DOWN).intValueExact();

        df.addRow(new Object[]{dataProducto, dataProducto.getCodigoBarras(),dataProducto.getNombre(),dataProducto.getCategorias(),String.valueOf(NumberFormat.getCurrencyInstance(new Locale("es", "CO")).format(dataProducto.getCosto())),String.valueOf(NumberFormat.getCurrencyInstance(new Locale("es", "CO")).format(dataProducto.getValor(/*dataProducto.getIdProducto()*/))),stoServicio });
        }
        jTProductos.setModel(df);        // TODO add your handling code here: 
     
    }//GEN-LAST:event_btnFiltroActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltro;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton jBExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTProductos;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
