/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.administracion;

import static java.awt.image.ImageObserver.WIDTH;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
//import models.TmUsuarios;

import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import models.Usuarios;
//import models.TmCategorias;
//import models.TmMesas;
/**
 *
 * @author bcristan
 */
public class frmListarCategorias extends javax.swing.JFrame {
    private List<models.Categorias> lisCategorias;
    //private final TmCategorias modeloCategorias;
   private Home_Administracion Parent;
    private Usuarios usuario;
    /**
     * Creates new form Usuarios
     */
    public frmListarCategorias(Home_Administracion p) {
        initComponents();
        this.Parent = p;
        this.setLocationRelativeTo(this);
        ImageIcon img = new ImageIcon(getClass().getResource("/images/icon_app.png"));
        this.setIconImage(img.getImage().getScaledInstance(180,180, Image.SCALE_SMOOTH));
        this.setTitle("POSystem - Powered by KIM-Solutions");
     
        models.Categorias categoria = new models.Categorias();
        lisCategorias = new ArrayList<>();
        lisCategorias = categoria.listarCategorias();
      
        
         DefaultTableModel df = (DefaultTableModel) TablaCategorias.getModel();
            
            for (models.Categorias dataCategoria:lisCategorias) {
                
                df.addRow(new Object[]{dataCategoria,dataCategoria.getIdCategoria(), dataCategoria.getNombre(),dataCategoria.getTipo()});
                
            }
            
            Home_Administracion form = Parent;
        frmListarCategorias listForm = this;
        
             TablaCategorias.addMouseListener(new java.awt.event.MouseAdapter(){
            public void mousePressed(MouseEvent me) {
            
                if (me.getClickCount() == 2) {
                        int fila = TablaCategorias.getSelectedRow();
                      
                        models.Categorias p = (models.Categorias) TablaCategorias.getValueAt(fila, 0);
                        
                        
                         new frmRegistrarCategoria(form,"Update",p).setVisible(true);
                         listForm.dispose();
                         //JOptionPane.showMessageDialog(null, "algo esta pasando"); 
                         
                        
                }
             }
            });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCategorias = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnNueva = new javax.swing.JButton();
        jBExit = new javax.swing.JButton();

        jPopupMenu1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPopupMenu1.setToolTipText("Modificar");
        jPopupMenu1.setName("Modificar"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 800));
        setMinimumSize(new java.awt.Dimension(1024, 800));
        setPreferredSize(new java.awt.Dimension(1024, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logotipo_cliente_small.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 5, 250, 179));

        TablaCategorias.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TablaCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "model", "Codigo", "Nombre", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaCategorias.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(TablaCategorias);
        if (TablaCategorias.getColumnModel().getColumnCount() > 0) {
            TablaCategorias.getColumnModel().getColumn(0).setMinWidth(0);
            TablaCategorias.getColumnModel().getColumn(0).setPreferredWidth(0);
            TablaCategorias.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 810, 308));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel2.setText("Gestion Categorias");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 370, -1));

        btnNueva.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        btnNueva.setText("Nueva");
        btnNueva.setToolTipText("");
        btnNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaActionPerformed(evt);
            }
        });
        getContentPane().add(btnNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, 150, 39));

        jBExit.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jBExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/exit.png"))); // NOI18N
        jBExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitActionPerformed(evt);
            }
        });
        getContentPane().add(jBExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 540, 160, 61));

        pack();
    }// </editor-fold>//GEN-END:initComponents
     /* Funcion : Abrir frame CMesas
    Nota :   toma  la fila selccionada  y envia los datos al frame CUsuarios
  * Desarrollador :(Brayan cristancho) 
  * Fecha de creacion : 04/08/2018**/
    private void btnNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaActionPerformed
        
        this.dispose();
        new frmRegistrarCategoria(Parent,"Create",new models.Categorias()).setVisible(true);
        
    }//GEN-LAST:event_btnNuevaActionPerformed

    private void jBExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitActionPerformed
        this.dispose();
       new Home_Administracion(usuario).setVisible(true);
    }//GEN-LAST:event_jBExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaCategorias;
    private javax.swing.JButton btnNueva;
    private javax.swing.JButton jBExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
