/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.administracion;

import static java.awt.image.ImageObserver.WIDTH;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
//import models.TmUsuarios;

import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.NumberFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import models.Operaciones;
import models.*;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
//import models.TmProductos;
/**
 *
 * @author bcristan
 */
public class frmListadoConceptosOperacion extends javax.swing.JFrame {
   
    private List<models.ConceptosOperaciones> listConceptos;
    //private TmProductos modelo;
    models.ConceptosOperaciones clConceptosOperaciones = new models.ConceptosOperaciones();
    //
    private Home_Administracion Parent;
     public static Usuarios usuario;
    
    /**
     * Creates new form Usuarios
     */
    public frmListadoConceptosOperacion(Home_Administracion P) {
        
        
        
        initComponents();
        
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.Parent = P;
       
        this.setLocationRelativeTo(this);
        ImageIcon img = new ImageIcon(getClass().getResource("/images/icon_app.png"));
        this.setIconImage(img.getImage().getScaledInstance(180,180, Image.SCALE_SMOOTH));
        this.setTitle("POSystem - Powered by KIM-Solutions");
        
        
        listConceptos = new ArrayList<>();
        listConceptos = clConceptosOperaciones.listarConceptos();
      
        DefaultTableModel df = (DefaultTableModel) TablaConceptoOperaciones.getModel();
            
        for (ConceptosOperaciones dataConcepto:listConceptos) {
            
           df.addRow(new Object[]{dataConcepto,dataConcepto.getIdConceptoOperacion(),dataConcepto.getNombre(),dataConcepto.getDescripcion()});
        }
        
        TablaConceptoOperaciones.setRowHeight(TablaConceptoOperaciones.getFontMetrics(TablaConceptoOperaciones.getFont()).getHeight() + 2);
        TablaConceptoOperaciones.revalidate(); // Fuerza a la interfaz a recalcular el diseño
        TablaConceptoOperaciones.repaint();   // Fuerza el repintado visual
        
        TablaConceptoOperaciones.setModel(df);
        
        Home_Administracion form = Parent;
        frmListadoConceptosOperacion listForm = this;
        
            TablaConceptoOperaciones.addMouseListener(new java.awt.event.MouseAdapter(){
            public void mousePressed(MouseEvent me) {
            
                if (me.getClickCount() == 2) {
                        int fila = TablaConceptoOperaciones.getSelectedRow();
                      
                        ConceptosOperaciones p = (ConceptosOperaciones) TablaConceptoOperaciones.getValueAt(fila, 0);
                        
                        listForm.dispose();
                        new frmRegistrarConceptoOperacion(Parent, "update", p).setVisible(true);
                       
                }
             }
            });
        
        

    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBExit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaConceptoOperaciones = new javax.swing.JTable();
        btnIngresar = new javax.swing.JButton();
        txtFiltro = new javax.swing.JTextField();
        btnFiltro = new javax.swing.JButton();

        jPopupMenu1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPopupMenu1.setToolTipText("Modificar");
        jPopupMenu1.setName("Modificar"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 800));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logotipo_cliente_small.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel2.setText("Gestion de Operaciones");

        jBExit.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jBExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/exit.png"))); // NOI18N
        jBExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitActionPerformed(evt);
            }
        });

        TablaConceptoOperaciones.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        TablaConceptoOperaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Modelo", "Codigo", "Nombre", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaConceptoOperaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaConceptoOperacionesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaConceptoOperaciones);
        if (TablaConceptoOperaciones.getColumnModel().getColumnCount() > 0) {
            TablaConceptoOperaciones.getColumnModel().getColumn(0).setMinWidth(0);
            TablaConceptoOperaciones.getColumnModel().getColumn(0).setPreferredWidth(0);
            TablaConceptoOperaciones.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        btnIngresar.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        btnIngresar.setText("Nuevo");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        txtFiltro.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N

        btnFiltro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/reload.png"))); // NOI18N
        btnFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBExit, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 951, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(btnFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(424, 424, 424)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(515, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBExit, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitActionPerformed
       this.dispose();
       new Home_Administracion(usuario).setVisible(true);
    }//GEN-LAST:event_jBExitActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
       
        
        frmRegistrarConceptoOperacion.usuario = usuario;
         this.setVisible(false);
        new frmRegistrarConceptoOperacion(Parent,"Create",new ConceptosOperaciones()).setVisible(true);           // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void TablaConceptoOperacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaConceptoOperacionesMouseClicked
   
// TODO add your handling code here:
    }//GEN-LAST:event_TablaConceptoOperacionesMouseClicked

    private void btnFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroActionPerformed
       
       DefaultTableModel model = (DefaultTableModel) TablaConceptoOperaciones.getModel();
       model.setRowCount(0);  
       TablaConceptoOperaciones.setModel(model);
       
       
        listConceptos = new ArrayList<>();
         listConceptos = clConceptosOperaciones.mtdFiltro(txtFiltro.getText());
      
         if(listConceptos.size() <= 0){
        
                JOptionPane.showMessageDialog(null, " No se Encontraron Resultados para "+txtFiltro.getText(),"Informacion",JOptionPane.INFORMATION_MESSAGE);
                listConceptos = clConceptosOperaciones.listarConceptos();
        }
         
         
        DefaultTableModel df = (DefaultTableModel) TablaConceptoOperaciones.getModel();
            
        for (ConceptosOperaciones dataConcepto:listConceptos) {
            
           df.addRow(new Object[]{dataConcepto,dataConcepto.getIdConceptoOperacion(),dataConcepto.getNombre(),dataConcepto.getDescripcion()});
        }
        TablaConceptoOperaciones.setModel(df);       // TODO add your handling code here: 
     
    }//GEN-LAST:event_btnFiltroActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaConceptoOperaciones;
    private javax.swing.JButton btnFiltro;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton jBExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
