/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.administracion;

import forms.frmConfirmacionPin;
import forms.frmMesas;
import forms.mainMesero;
import static forms.mainMesero.pedido;
import java.awt.Image;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import models.*;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.view.JasperViewer;

import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author Manuel Rodriguez
 */
public class frmModoPago extends javax.swing.JFrame {

    /**
     * Creates new form frmModoPago
     */
    
    public frmDetalleVenta parent;
    public Ventas venta;
    public frmModoPago(frmDetalleVenta p,Ventas venta){
        initComponents();
        this.parent= p;
        this.venta = venta;
        this.setResizable(false);
        this.setLocationRelativeTo(this);
        ImageIcon img = new ImageIcon(getClass().getResource("/images/icon_app.png"));
        this.setIconImage(img.getImage().getScaledInstance(180,180, Image.SCALE_SMOOTH));
        this.setTitle("POSystem - Powered by KIM-Solutions");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTarjeta = new javax.swing.JButton();
        btnEfectivo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        btnTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/qr.png"))); // NOI18N
        btnTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarjetaActionPerformed(evt);
            }
        });

        btnEfectivo.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        btnEfectivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/efectivo.png"))); // NOI18N
        btnEfectivo.setFocusPainted(false);
        btnEfectivo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEfectivoActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logotipo_cliente_small.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel2.setText("TRANSFERENCIA / QR");

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel3.setText("EFECTIVO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(btnTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEfectivoActionPerformed
            
            this.venta.setEstado("Pagada");
           
                Transaction trns = null;
                Session session = HibernateUtil.getSessionFactory().openSession();
                try {
                   trns = session.beginTransaction();
                   session.update(this.venta);
                   session.getTransaction().commit();
                   
                    int resp=JOptionPane.showConfirmDialog(null,"Operacion Exitosa! \n ¿Deseas imprimir la Factura?");

                    if (JOptionPane.OK_OPTION == resp){

                        Map<String,Object> params = new HashMap<String,Object>();
                        params.put("Venta", this.venta);
                        
                        try{
                        
                        JasperPrint jasperPrint = JasperFillManager.fillReport("src\\reports\\venta.jasper",params,new JREmptyDataSource());
                        
                        //JasperViewer.viewReport(jasperPrint, false);
                        JasperPrintManager.printReport(jasperPrint, false);   
                            new Home_Administracion().setVisible(true);
                        }catch (JRException ex){
                        JOptionPane.showMessageDialog(rootPane, "Error iReport: " + ex.getMessage());
                        System.err.println( "Error iReport: " + ex.getMessage() );
                        }finally{
                            this.parent.dispose();
                           this.dispose();
                           
                           
                        }
                    }else{
                           new Home_Administracion().setVisible(true);
                    }
                   
                 }catch (RuntimeException ex) {
                    ex.printStackTrace();
                }finally {
                    session.flush();
                    session.close();
                    this.dispose();
                }
          
            this.parent.dispose();
            this.dispose();
    }//GEN-LAST:event_btnEfectivoActionPerformed

    private void btnTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarjetaActionPerformed
           
           this.venta.setFormaPago("Transferencia");
           this.venta.setEstado("Pagada");
        
            Transaction trns = null;
            Session session = HibernateUtil.getSessionFactory().openSession();
            try {
               trns = session.beginTransaction();
               session.update(this.venta);
               session.getTransaction().commit();
               
               int resp=JOptionPane.showConfirmDialog(null,"Operacion Exitosa! \n ¿Deseas imprimir la Factura?");

                    if (JOptionPane.OK_OPTION == resp){

                        Map<String,Object> params = new HashMap<String,Object>();
                        params.put("Venta", this.venta);
                        
                        try{
                        
                        JasperPrint jasperPrint = JasperFillManager.fillReport("src\\reports\\venta.jasper",params,new JREmptyDataSource());
                        
                        JasperPrintManager.printReport(jasperPrint, false);   
                         new Home_Administracion().setVisible(true);
                        }catch (JRException ex){
                        JOptionPane.showMessageDialog(rootPane, "Error iReport: " + ex.getMessage());
                        System.err.println( "Error iReport: " + ex.getMessage() );
                        }finally{
                            this.parent.dispose();
                         this.dispose();
                        
                        }
                    }else{
                         new Home_Administracion().setVisible(true);
                    }
                    
                    
             }catch (RuntimeException ex) {
                ex.printStackTrace();
            }finally {
                session.flush();
                session.close();
                this.dispose();
            }
        
            this.parent.dispose();
            this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_btnTarjetaActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEfectivo;
    private javax.swing.JButton btnTarjeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
