/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.administracion;

import forms.frmConfirmacionPin;
import forms.frmMesas;
import forms.frmVueltas;
import forms.mainMesero;
import static forms.mainMesero.pedido;
import java.awt.Image;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import models.*;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.view.JasperViewer;

import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author Manuel Rodriguez
 */
public class frmModoPago extends javax.swing.JFrame {

    /**
     * Creates new form frmModoPago
     */
    
    public frmDetalleVenta parent;
    public Ventas venta;
    public frmModoPago(frmDetalleVenta p,Ventas venta){
        initComponents();
        this.parent= p;
        this.venta = venta;
        this.setResizable(false);
        this.setLocationRelativeTo(this);
        ImageIcon img = new ImageIcon(getClass().getResource("/images/icon_app.png"));
        this.setIconImage(img.getImage().getScaledInstance(180,180, Image.SCALE_SMOOTH));
        this.setTitle("POSystem - Powered by KIM-Solutions");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTarjeta = new javax.swing.JButton();
        btnEfectivo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCombinado = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(791, 616));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/qr.png"))); // NOI18N
        btnTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarjetaActionPerformed(evt);
            }
        });
        getContentPane().add(btnTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 140, 110));

        btnEfectivo.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        btnEfectivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/efectivo.png"))); // NOI18N
        btnEfectivo.setFocusPainted(false);
        btnEfectivo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEfectivoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 144, 108));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logotipo_cliente_small.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel2.setText("MIXTO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, -1));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel3.setText("EFECTIVO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        btnCombinado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/combinado.png"))); // NOI18N
        btnCombinado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCombinadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCombinado, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 144, 108));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel4.setText("TRANSFERENCIA / QR");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, -1, -1));

        btnSalir.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/exit.png"))); // NOI18N
        btnSalir.setFocusPainted(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 144, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEfectivoActionPerformed
            
        
            
            
           int respVueltos = JOptionPane.showConfirmDialog(null,"¿Necesitas dar Vueltas?");
        
        
            if (JOptionPane.OK_OPTION == respVueltos){
               
                
                this.setEnabled(false);
                frmVueltas.venta = this.venta;
                
               frmVueltas formVueltas = new frmVueltas(this);
               formVueltas.setVisible(true);
               
               formVueltas.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent e) {
                
                    if(frmModoPago.this.venta.getEstado() != "Pagada"){
                    
                        frmModoPago.this.toFront(); 
                        frmModoPago.this.setEnabled(true); 
                        frmModoPago.this.setVisible(true);
                    }
                
                }});
                
                
            }else{
                
                mtdConfirmarPagosEfectivo();
                this.parent.dispose();
                this.dispose();
                         
            }
        
        
        

    }//GEN-LAST:event_btnEfectivoActionPerformed

    private void btnTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarjetaActionPerformed
           
           this.venta.setFormaPago("Transferencia");
           this.venta.setEstado("Pagada");
        
            Transaction trns = null;
            Session session = HibernateUtil.getSessionFactory().openSession();
            try {
               trns = session.beginTransaction();
               session.update(this.venta);
               session.getTransaction().commit();
               
               int resp=JOptionPane.showConfirmDialog(null,"Operacion Exitosa! \n ¿Deseas imprimir la Factura?");

                    if (JOptionPane.OK_OPTION == resp){

                        Map<String,Object> params = new HashMap<String,Object>();
                        params.put("Venta", this.venta);
                        
                        try{
                        
                        JasperPrint jasperPrint = JasperFillManager.fillReport("src\\reports\\venta.jasper",params,new JREmptyDataSource());
                        //JasperViewer.viewReport(jasperPrint, false);
                        JasperPrintManager.printReport(jasperPrint, false);   
                         new Home_Administracion(venta.getUsuarios()).setVisible(true);
                        }catch (JRException ex){
                        JOptionPane.showMessageDialog(rootPane, "Error iReport: " + ex.getMessage());
                        System.err.println( "Error iReport: " + ex.getMessage() );
                        }
                    }else{
                         new Home_Administracion(venta.getUsuarios()).setVisible(true);
                    }
                    
                    
             }catch (RuntimeException ex) {
                ex.printStackTrace();
            }finally {
                session.flush();
                session.close();
                this.dispose();
            }
        
            this.parent.dispose();
            this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_btnTarjetaActionPerformed

    private void btnCombinadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCombinadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCombinadoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
            
            this.parent.setVisible(true);
            this.dispose();
            
            
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void mtdConfirmarPagosEfectivo(){
        
                this.venta.setEstado("Pagada");
           
                Transaction trns = null;
                Session session = HibernateUtil.getSessionFactory().openSession();
                try {
                   trns = session.beginTransaction();
                   session.update(this.venta);
                   session.getTransaction().commit();
                   
                    int resp=JOptionPane.showConfirmDialog(null,"Operacion Exitosa! \n ¿Deseas imprimir la Factura?");

                    if (JOptionPane.OK_OPTION == resp){

                        Map<String,Object> params = new HashMap<String,Object>();
                        params.put("Venta", this.venta);
                        
                        try{
                        
                        JasperPrint jasperPrint = JasperFillManager.fillReport("src\\reports\\venta.jasper",params,new JREmptyDataSource());
                        
                        //JasperViewer.viewReport(jasperPrint, false);
                        JasperPrintManager.printReport(jasperPrint, false);   
                            new Home_Administracion(venta.getUsuarios()).setVisible(true);
                        }catch (JRException ex){
                        JOptionPane.showMessageDialog(rootPane, "Error iReport: " + ex.getMessage());
                        System.err.println( "Error iReport: " + ex.getMessage() );
                        }finally{
                            this.parent.dispose();
                           this.dispose();
                           
                           
                        }
                    }else{
                           new Home_Administracion(venta.getUsuarios()).setVisible(true);
                    }
                   
                 }catch (RuntimeException ex) {
                    ex.printStackTrace();
                }finally {
                    session.flush();
                    session.close();
                    this.dispose();
                }
          
            this.parent.dispose();
            this.dispose();
        
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCombinado;
    private javax.swing.JButton btnEfectivo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTarjeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
