/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.administracion;



import forms.mainMesero;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import models.*;
import org.hibernate.CacheMode;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author Alejita
 */
public class frmPedidos extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form frmPedidos
     */
    public Home_Administracion parent;
    public List<Ventas> listVentas;
    public static Usuarios usuario;
    
    private models.DisenoFormularios desing;
    
    private Thread hilo;
    
    public frmPedidos(Home_Administracion p) {
        
       
        initComponents();
        
        desing.mtdDisenoPantalla(this);
        this.parent  = p;
       
        ImageIcon img = new ImageIcon(getClass().getResource("/images/icon_app.png"));
        this.setIconImage(img.getImage().getScaledInstance(180,180, Image.SCALE_SMOOTH));
        
        
        hilo = new Thread(this);
        hilo.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnSuperior = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnRecargar = new javax.swing.JButton();
        jpnCentral = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PanelPedidos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jpnSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logotipo_cliente_small.png"))); // NOI18N
        jpnSuperior.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 160, 179));

        jLabel2.setFont(new java.awt.Font("Leelawadee", 0, 36)); // NOI18N
        jLabel2.setText("Pedidos Sin Facturar");
        jpnSuperior.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 350, 70));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/exit.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jpnSuperior.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 70, 90, 70));

        btnRecargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/reload.png"))); // NOI18N
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });
        jpnSuperior.add(btnRecargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 70, 90, 70));

        getContentPane().add(jpnSuperior, java.awt.BorderLayout.NORTH);

        jpnCentral.setLayout(new java.awt.GridLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        PanelPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelPedidos.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(PanelPedidos);

        jpnCentral.add(jScrollPane1);

        getContentPane().add(jpnCentral, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        hilo.interrupt();
        this.dispose();
        new Home_Administracion(usuario).setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
       mtdFiltrarPedidosSinFacturar();
// TODO add your handling code here:
    }//GEN-LAST:event_btnRecargarActionPerformed

    /**
     * @param args the command line arguments
     */
   
    
    public void mtdFiltrarPedidosSinFacturar(){
        
        PanelPedidos.removeAll();
        
        frmPedidos p = this;
        
        Session s = HibernateUtil.getSessionFactory().openSession();
        s.setCacheMode(CacheMode.IGNORE);
        s.clear();
        Query q = s.createQuery("FROM Ventas WHERE estado = 'Abierta'");
        
        listVentas = q.list();
        
        
        for(Ventas dataVenta:listVentas) {     
            JButton btnPedido = new JButton("<html>Pedido # "+dataVenta.getIdVenta()+"<br> Ubicacion: "+dataVenta.getMesas().getTipo()+" "+dataVenta.getMesas().getNumero()+"<br>Mesero: "
                                                +dataVenta.getUsuarios().getNombres()+" "+dataVenta.getUsuarios().getApellidos()+"<br>Total Factura:"
                                                +String.valueOf(NumberFormat.getCurrencyInstance(new Locale("es", "CO")).format(dataVenta.getTotal())));
           
            btnPedido.setFont(new java.awt.Font("Leelawadee UI", 0, 18));
            
             btnPedido.addActionListener(new ActionListener() { 
                public void actionPerformed(ActionEvent e) {            
                   frmDetalleVenta formDetalle = new frmDetalleVenta(p,dataVenta);
                   formDetalle.usuario = usuario;
                   formDetalle.setVisible(true);
                   p.dispose();
                } 
            } );
            
            PanelPedidos.add(btnPedido);
            //System.out.println(dataVenta.getIdVenta());
        }
        s.clear();
        s.flush();
        s.close();
        
        PanelPedidos.revalidate();
        PanelPedidos.repaint();
        this.revalidate();
        this.repaint();
    }
    
    
    @Override
    public void run() {
 
        while(true){
            mtdFiltrarPedidosSinFacturar();
            
            try{
                Thread.sleep(5000);
            }catch(Exception e){
                Thread.currentThread().interrupt(); 
                break;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPedidos;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpnCentral;
    private javax.swing.JPanel jpnSuperior;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
}
