/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.administracion;

import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import models.Categorias;
import java.lang.Object;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import models.*;
import models.Ingresoproductos;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import org.hibernate.Session;
import org.hibernate.Transaction;
/**
 *
 * @author Manuel Rodriguez
 */
public class frmRegistrarProductos extends javax.swing.JFrame {

    /**
     * Creates new form frmRegistrarProductos
     */
    models.Productos objProducto;
    models.Productos Clproducto = new models.Productos();
    Home_Administracion parent;
    private List<models.Categorias> listCategorias;
    public  List<Ingresoproductos> arrayIngresos = new ArrayList<>();
    
    private Facturas factura;
    private Facturas ObjFactura = new Facturas();
     public static Usuarios usuario;
    
    
    public String modo_envio;
   public Ingresoproductos objetoIngreso;
    public frmRegistrarProductos(Home_Administracion p,Facturas fact) {
        
       this.factura = fact;
        
        initComponents();
        this.parent = p;
        this.setLocationRelativeTo(this);
        ImageIcon img = new ImageIcon(getClass().getResource("/images/icon_app.png"));
        this.setIconImage(img.getImage().getScaledInstance(180,180, Image.SCALE_SMOOTH));
        this.setTitle("POSystem - Powered by KIM-Solutions");
        
        // PanelAdd.setVisible(false);
         //PanelUpdate.setVisible(false);
        mtdOcultos(false);
        
        models.Categorias cate = new models.Categorias();
          listCategorias = cate.listarCategorias();
        for (int i = 0; i < listCategorias.size(); i++) {
                cmbCategoria.addItem(listCategorias.get(i));
          }
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCodigoBarras = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        PanelAdd = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        lblTipoVenta = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblValorVenta = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        txtVenta = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        cmbTipoVenta = new javax.swing.JComboBox<>();
        lblTitle = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        rdbServicio = new javax.swing.JRadioButton();
        lblTotalPedido = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        PanelInformacionProducto = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblInfoCodigo = new javax.swing.JLabel();
        lblInfoNombre = new javax.swing.JLabel();
        lblInfoCategoria = new javax.swing.JLabel();
        lblInfoValor = new javax.swing.JLabel();
        lblInfoTipoVenta = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCodigoBarras.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        txtCodigoBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoBarrasActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodigoBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, 322, 53));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logotipo_cliente_small.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 31, 250, 179));

        PanelAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        lblNombre.setText("NOMBRE");
        PanelAdd.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 114, -1));

        lblCategoria.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        lblCategoria.setText("CATEGORIA");
        PanelAdd.add(lblCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 169, -1));

        lblTipoVenta.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        lblTipoVenta.setText("TIPO VENTA");
        PanelAdd.add(lblTipoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 202, -1));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel3.setText("VALOR COMPRA");
        PanelAdd.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 190, -1));

        lblValorVenta.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        lblValorVenta.setText("VALOR VENTA");
        PanelAdd.add(lblValorVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 170, -1));

        txtNombre.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        PanelAdd.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 190, 50));

        txtCosto.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        PanelAdd.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 190, 40));

        txtVenta.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        PanelAdd.add(txtVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 190, 40));

        txtCantidad.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadKeyPressed(evt);
            }
        });
        PanelAdd.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 210, 40));

        cmbTipoVenta.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        cmbTipoVenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unidad", "Peso" }));
        cmbTipoVenta.setFocusable(false);
        cmbTipoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoVentaActionPerformed(evt);
            }
        });
        PanelAdd.add(cmbTipoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 210, 40));

        lblTitle.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Añadir Unidades");
        PanelAdd.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 270, 52));

        cmbCategoria.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cmbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriaActionPerformed(evt);
            }
        });
        PanelAdd.add(cmbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 210, -1));

        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/check.png"))); // NOI18N
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        PanelAdd.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 80, 60));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/drop.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        PanelAdd.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 80, 60));

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel2.setText("CANTIDAD");
        PanelAdd.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 100, 30));

        rdbServicio.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        rdbServicio.setText("Servicio");
        rdbServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbServicioActionPerformed(evt);
            }
        });
        PanelAdd.add(rdbServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 140, 40));

        lblTotalPedido.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        PanelAdd.add(lblTotalPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 160, 40));

        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/print.png"))); // NOI18N
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        PanelAdd.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 130, 100));

        getContentPane().add(PanelAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 530, 510));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        jLabel6.setText("Codigo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Información de Producto");

        jLabel9.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Categoria:");

        jLabel10.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Nombre:");

        jLabel11.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Codigo:");

        jLabel12.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Disponible:");

        jLabel13.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Venta Por:");

        jLabel14.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Valor:");

        lblInfoCodigo.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        lblInfoCodigo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblInfoNombre.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        lblInfoNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblInfoCategoria.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        lblInfoCategoria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblInfoValor.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        lblInfoValor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblInfoTipoVenta.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        lblInfoTipoVenta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblStock.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        lblStock.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout PanelInformacionProductoLayout = new javax.swing.GroupLayout(PanelInformacionProducto);
        PanelInformacionProducto.setLayout(PanelInformacionProductoLayout);
        PanelInformacionProductoLayout.setHorizontalGroup(
            PanelInformacionProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInformacionProductoLayout.createSequentialGroup()
                .addGroup(PanelInformacionProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelInformacionProductoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelInformacionProductoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblInfoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelInformacionProductoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(PanelInformacionProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelInformacionProductoLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblInfoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelInformacionProductoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblInfoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelInformacionProductoLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(lblInfoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelInformacionProductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelInformacionProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelInformacionProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelInformacionProductoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblInfoTipoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelInformacionProductoLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(lblStock, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelInformacionProductoLayout.setVerticalGroup(
            PanelInformacionProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInformacionProductoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel8)
                .addGap(41, 41, 41)
                .addGroup(PanelInformacionProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelInformacionProductoLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(14, 14, 14))
                    .addGroup(PanelInformacionProductoLayout.createSequentialGroup()
                        .addComponent(lblInfoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(PanelInformacionProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblInfoCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelInformacionProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblInfoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelInformacionProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInfoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelInformacionProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInfoTipoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(PanelInformacionProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStock, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(PanelInformacionProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 360, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoBarrasActionPerformed
  
        
        objProducto = Clproducto.mtdBuscarProducto(txtCodigoBarras.getText());
        
        
        if(objProducto != null){
            
            BigDecimal stock = objProducto.getStock();
            int sto = stock.setScale(0, RoundingMode.DOWN).intValueExact();
            
            lblTitle.setText("Añadir Unidades");
            
            
            lblInfoNombre.setText(objProducto.getNombre());
            lblStock.setText(String.valueOf(sto));
            lblInfoValor.setText(String.valueOf(NumberFormat.getCurrencyInstance(new Locale("es", "CO")).format(objProducto.getValor(/*objProducto.getIdProducto()*/))));
            lblInfoTipoVenta.setText(objProducto.getTipoVenta());
            lblInfoCodigo.setText(objProducto.getCodigoBarras());
            lblInfoCategoria.setText(objProducto.getCategorias().getNombre());
            
            txtCosto.setText(String.valueOf(objProducto.getCosto()));
            
            
            txtCodigoBarras.setText(null);
            
            mtdOcultos(false);
            
            modo_envio = "update";
            
                   
        }else{
            
            
            
            mtdLimpiarLbls();
            
            lblTitle.setText("Añadir Producto");
            
            int resp=JOptionPane.showConfirmDialog(null,"Este Producto No se Encuentra Registrado \n ¿Quieres Registrar el Nuevo Producto?");
            
            if (JOptionPane.OK_OPTION == resp){
                
                 modo_envio = "create";
                 mtdOcultos(true);
                 
            }else{
                this.dispose();
            }
        }
        
        
        

// TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoBarrasActionPerformed

    private void cmbTipoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoVentaActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
            
        
        
        
       objetoIngreso  = new Ingresoproductos();
        
       
        Calendar calendario = Calendar.getInstance();
        Date date = calendario.getTime();
        if(modo_envio.equalsIgnoreCase("update")){
            
            BigDecimal stock = objProducto.getStock();
            int sto = stock.setScale(0, RoundingMode.DOWN).intValueExact();
            
             double cant = Double.parseDouble(txtCantidad.getText());
            
              objProducto.setStock(BigDecimal.valueOf(sto + cant));
            
            if(objProducto.getCosto() != Double.parseDouble(txtCosto.getText())){
                
                double AntValor = sto * objProducto.getCosto();
                double nuevoValor = cant * Double.parseDouble(txtCosto.getText());
                
                double valorActual = (AntValor + nuevoValor) / (sto + cant);
                
                objProducto.setCosto((int) valorActual);
                
            }
            
            objetoIngreso.setCostoIngreso(Double.parseDouble(txtCosto.getText()));
            objetoIngreso.setCantidad((int)cant);
            objetoIngreso.setFecha(date);
            objetoIngreso.setProductos(objProducto);
            objetoIngreso.setFacturas(factura);
            
           
            
            Transaction trns = null;
            Session session = HibernateUtil.getSessionFactory().openSession();
            try {
                trns = session.beginTransaction();
                session.update(objProducto);
                session.save(objetoIngreso);
                session.getTransaction().commit();
                
                JOptionPane.showMessageDialog(null, "Producto Actualizado!","Correcto",JOptionPane.INFORMATION_MESSAGE);
                mtdLimpiarLbls();
                mtdLimpiarCajas();
                
                
            
            } catch (RuntimeException e) {
                e.printStackTrace();
           
            } finally {
                session.close();
            }
            
            
            
            
            
        }else if(modo_envio.equalsIgnoreCase("create")){
            
            boolean servicio = false;
            if(rdbServicio.isSelected()){
                servicio = true;
            }
             Categorias cat = (Categorias) cmbCategoria.getSelectedItem();
            
             objProducto = new models.Productos(cat,txtNombre.getText(), txtCodigoBarras.getText(),Integer.parseInt(txtCosto.getText()) , Integer.parseInt(txtVenta.getText()), BigDecimal.valueOf(Double.parseDouble(txtCantidad.getText())),servicio ,cmbTipoVenta.getSelectedItem().toString(), "", "Activo");
             
            objetoIngreso.setCostoIngreso(Double.parseDouble(txtCosto.getText()));
            objetoIngreso.setCantidad(Integer.parseInt(txtCantidad.getText()));
            objetoIngreso.setFecha(date);
            objetoIngreso.setProductos(objProducto);
            objetoIngreso.setFacturas(factura);
            
            
             
            Transaction trns = null;
            Session session = HibernateUtil.getSessionFactory().openSession();
            try {
                trns = session.beginTransaction();
                session.save(objProducto);
                session.save(objetoIngreso);
                session.getTransaction().commit();
            
                JOptionPane.showMessageDialog(null, "Producto Registrado!","Correcto",JOptionPane.INFORMATION_MESSAGE);
                txtCodigoBarras.setText(null);
                mtdLimpiarCajas();
                
                  
            
            } catch (RuntimeException e) {
                e.printStackTrace();
            
            } finally {
                session.close();
            }
             
        }
           

        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void cmbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoriaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

            Facturas clFactura = new Facturas();
            Facturas objFactura;
            
            objFactura = clFactura.mtdUniqueFactura(factura.getIdFactura());
            
            if(objFactura.getPedidos().size() > 0){
                 this.dispose();
                 new Home_Administracion(usuario).setVisible(true);
            }else{
                     int resp=JOptionPane.showConfirmDialog(null,"Esta Factura No Tiene Productos \n ¿Deseas Cancelar Factura?");

                    if (JOptionPane.OK_OPTION == resp){
                        clFactura.mtdEliminarFactura(objFactura);
                         this.dispose();
                       new Home_Administracion(usuario).setVisible(true);
                    }
            }

       
            
// TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void rdbServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbServicioActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        
            double valorIndividual = 0;
            valorIndividual = Double.parseDouble(txtCosto.getText());
            
            int cantidad = Integer.parseInt(txtCantidad.getText());
            
            lblTotalPedido.setText(String.valueOf(NumberFormat.getCurrencyInstance(new Locale("es", "CO")).format(valorIndividual * cantidad)));
            

        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadKeyPressed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
      
               
                 Map<String,Object> params = new HashMap<String,Object>();
                 
                 params.put("factura", ObjFactura.mtdUniqueFactura(factura.getIdFactura()));
                 
        
                 
                JasperPrint jasperPrint;
        try {
            jasperPrint = JasperFillManager.fillReport("src/reports/ingreso_pedido.jasper",params,new JREmptyDataSource());
            JasperPrintManager.printReport(jasperPrint, false); 
        } catch (JRException ex) {
            Logger.getLogger(frmRegistrarProductos.class.getName()).log(Level.SEVERE, null, ex);
        }finally{ this.dispose(); parent.setVisible(true);}
            
                  

// TODO add your handling code here:
    }//GEN-LAST:event_btnPrintActionPerformed

   
    
    public void mtdLimpiarLbls(){
        lblInfoNombre.setText(null);
        lblStock.setText(null);
        lblInfoValor.setText(null);
        lblInfoTipoVenta.setText(null);
        lblInfoCodigo.setText(null);
        lblInfoCategoria.setText(null);
    }
    
    public void mtdOcultos(boolean var){
        
        lblNombre.setVisible(var);
        txtNombre.setVisible(var);
        lblValorVenta.setVisible(var);
        txtVenta.setVisible(var);
        lblCategoria.setVisible(var);
        cmbCategoria.setVisible(var);
        lblTipoVenta.setVisible(var);
        cmbTipoVenta.setVisible(var);
        rdbServicio.setVisible(var);
        
    }
    
    public void mtdLimpiarCajas(){
        txtNombre.setText(null);
        txtVenta.setText(null);
        txtCantidad.setText(null);
        txtCosto.setText(null);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAdd;
    private javax.swing.JPanel PanelInformacionProducto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnPrint;
    public javax.swing.JComboBox<models.Categorias> cmbCategoria;
    private javax.swing.JComboBox<String> cmbTipoVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblInfoCategoria;
    private javax.swing.JLabel lblInfoCodigo;
    private javax.swing.JLabel lblInfoNombre;
    private javax.swing.JLabel lblInfoTipoVenta;
    private javax.swing.JLabel lblInfoValor;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTipoVenta;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalPedido;
    private javax.swing.JLabel lblValorVenta;
    private javax.swing.JRadioButton rdbServicio;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigoBarras;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtVenta;
    // End of variables declaration//GEN-END:variables
}
