/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.administracion;

import com.mindfusion.keyboard.Theme;
import com.mindfusion.keyboard.VirtualKeyboard;
import java.awt.Button;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JPopupMenu;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;
import models.HibernateUtil;
import org.hibernate.Session;
import org.jvnet.substance.SubstanceLookAndFeel;

/**
 *
 * @author bcristan
 */
public class frmRegistrarCategoria extends javax.swing.JFrame {

    JTextField txtusu = new JTextField(10);
    JPasswordField txtclave = new JPasswordField(10);
    JPopupMenu pop;
    
    private String modo;
    private models.Categorias categoria;
    private Home_Administracion Parent;
    
    public frmRegistrarCategoria(Home_Administracion  p,String modo,models.Categorias objCat) {
        initComponents();
       this.setLocationRelativeTo(this);
        ImageIcon img = new ImageIcon(getClass().getResource("/images/icon_app.png"));
        this.setIconImage(img.getImage().getScaledInstance(180,180, Image.SCALE_SMOOTH));
        this.setTitle("POSystem - Powered by &Source Ltda");
        this.modo = modo;
        this.categoria = objCat;
        this.Parent = p;
        
        txtNombre.setText(objCat.getNombre());
        if(objCat.getTipo()== null){
            
         }else{
             switch(objCat.getTipo()){
                case "Licores":
                     txttipo.setSelectedIndex(0);
                break;  
                case "Sin Stock":
                     txttipo.setSelectedIndex(1);
                break;
                case "Otra":
                     txttipo.setSelectedIndex(2);
                break;

            }
        }

      
        
     
    }
    /**
     * Creates new form CUsuarios
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        parent = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txttipo = new javax.swing.JComboBox<String>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 700));
        setMinimumSize(new java.awt.Dimension(900, 700));
        setPreferredSize(new java.awt.Dimension(900, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logotipo_cliente_small.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 52, 250, 179));

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 416, 41));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 169, 40));

        btnGuardar.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, -1, 61));

        btnSalir.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/exit.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 160, 61));

        javax.swing.GroupLayout parentLayout = new javax.swing.GroupLayout(parent);
        parent.setLayout(parentLayout);
        parentLayout.setHorizontalGroup(
            parentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 264, Short.MAX_VALUE)
        );
        parentLayout.setVerticalGroup(
            parentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 129, Short.MAX_VALUE)
        );

        getContentPane().add(parent, new org.netbeans.lib.awtextra.AbsoluteConstraints(957, 201, -1, -1));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Tipo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 169, 42));

        txttipo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txttipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Licores", "Sin Stock", "Otra" }));
        txttipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttipoActionPerformed(evt);
            }
        });
        getContentPane().add(txttipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 416, 44));

        pack();
    }// </editor-fold>//GEN-END:initComponents
  /*
  * Funcion : Guardar Mesa
    Nota : se utiliza para actualizar e insertar mesa ademas de validacion de la data 
  * Desarrollador :(Brayan cristancho) 
  * Fecha de creacion : 04/08/2018**/
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       
        
            try {
                if (!txtNombre.getText().isEmpty()) {
                    
                    Session sesion = HibernateUtil.getSessionFactory().openSession();
                    if (modo.equalsIgnoreCase("Create")) {
                       categoria = new models.Categorias(txtNombre.getText(), txttipo.getSelectedItem().toString());
                       
                       sesion.beginTransaction();
                        sesion.save(categoria);
                        sesion.getTransaction().commit();
                    } else {
                        categoria.setNombre(txtNombre.getText());
                        categoria.setTipo(txttipo.getSelectedItem().toString());
                        
                        sesion.beginTransaction();
                        sesion.update(categoria);
                        sesion.getTransaction().commit();
                    }
                    
                    sesion.flush();
                    sesion.close();
                    this.dispose();
                    
                    new frmListarCategorias(Parent).setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Complete todos los campos");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error Inesperado");
            }
       

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        new frmListarCategorias(Parent).setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txttipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttipoActionPerformed

    /*validar entero pin */
    public boolean isInteger(String numero) {
        try {
            Integer.parseInt(numero);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel parent;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JComboBox<String> txttipo;
    // End of variables declaration//GEN-END:variables
}
