/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.administracion;

import java.awt.Image;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Categorias;
import models.HibernateUtil;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.jfree.base.modules.DefaultModuleInfo;

/**
 *
 * @author Manuel Rodriguez
 */
public class frmRegistrarCompuesto extends javax.swing.JFrame {

    /**
     * Creates new form frmRegistrarCompuesto
     */
    
  private Home_Administracion Parent;
  public models.Productos producto;
  private List<models.Categorias> listCategorias;
  private List<models.Productos> ListProductos;
  models.Productos ClProducto = new models.Productos();
  private List<models.Subproductos> ArraySubProductos = new ArrayList<>();
  public models.Subproductos subProducto;
  private static DefaultTableModel modelo;
  
  public int totalCosto = 0;

    
    public frmRegistrarCompuesto(Home_Administracion p,models.Productos producto) {
        initComponents();
        this.Parent = p;
        this.producto = producto;
        this.setLocationRelativeTo(this);
        ImageIcon img = new ImageIcon(getClass().getResource("/images/icon_app.png"));
        this.setIconImage(img.getImage().getScaledInstance(180,180, Image.SCALE_SMOOTH));
        this.setTitle("POSystem - Powered by KIM-Solutions");
        txtCosto.setVisible(false);
        
        models.Categorias cate = new models.Categorias();
          listCategorias = cate.listarCategorias();
        for (int i = 0; i < listCategorias.size(); i++) {
                cmbCategoria.addItem(listCategorias.get(i));
          }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        lblValorVenta = new javax.swing.JLabel();
        txtVenta = new javax.swing.JTextField();
        cmbProductos = new javax.swing.JComboBox<>();
        lblCategoria1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        lblCant = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSubproductos = new javax.swing.JTable();
        lblValorVenta2 = new javax.swing.JLabel();
        lblTotalCosto = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        rdbShots = new javax.swing.JRadioButton();
        rdbCoctel = new javax.swing.JRadioButton();
        rdbCubetazo = new javax.swing.JRadioButton();
        lblNombre1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        btnDeleteSubProducto = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 720));
        setMinimumSize(new java.awt.Dimension(1024, 700));
        setPreferredSize(new java.awt.Dimension(1024, 700));

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        jLabel2.setText("Agregar Producto Compuesto");

        txtNombre.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N

        lblNombre.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        lblNombre.setText("NOMBRE");

        lblCategoria.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        lblCategoria.setText("CATEGORIA");

        cmbCategoria.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cmbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriaActionPerformed(evt);
            }
        });

        lblValorVenta.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        lblValorVenta.setText("VALOR VENTA");

        txtVenta.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N

        cmbProductos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cmbProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductosActionPerformed(evt);
            }
        });

        lblCategoria1.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        lblCategoria1.setText("Producto de Composición:");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logotipo_cliente_xsmall.png"))); // NOI18N

        txtCantidad.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N

        lblCant.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        lblCant.setText("Cantidad (ml):");

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/check.png"))); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tblSubproductos.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        tblSubproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Objeto", "Nombre", "Cantidad", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSubproductos);
        if (tblSubproductos.getColumnModel().getColumnCount() > 0) {
            tblSubproductos.getColumnModel().getColumn(0).setMinWidth(0);
            tblSubproductos.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblSubproductos.getColumnModel().getColumn(0).setMaxWidth(0);
            tblSubproductos.getColumnModel().getColumn(1).setResizable(false);
            tblSubproductos.getColumnModel().getColumn(2).setResizable(false);
            tblSubproductos.getColumnModel().getColumn(3).setResizable(false);
        }

        lblValorVenta2.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        lblValorVenta2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValorVenta2.setText("Valor Costo:");

        lblTotalCosto.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        lblTotalCosto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalCosto.setText("$0.0");

        btnGuardar.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        btnGuardar.setText("Guargar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        rdbShots.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        rdbShots.setText("Shots");
        rdbShots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbShotsActionPerformed(evt);
            }
        });

        rdbCoctel.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        rdbCoctel.setText("Coctel");
        rdbCoctel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCoctelActionPerformed(evt);
            }
        });

        rdbCubetazo.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        rdbCubetazo.setText("Pack");
        rdbCubetazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCubetazoActionPerformed(evt);
            }
        });

        lblNombre1.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        lblNombre1.setText("CODIGO");

        txtCodigo.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N

        txtCosto.setText("0");
        txtCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoActionPerformed(evt);
            }
        });

        btnDeleteSubProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/drop.png"))); // NOI18N
        btnDeleteSubProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSubProductoActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCant, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCantidad)
                                .addGap(18, 18, 18)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnDeleteSubProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(lblValorVenta2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblTotalCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCodigo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 82, Short.MAX_VALUE)))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(141, 141, 141)
                                        .addComponent(lblCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(75, 75, 75))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblValorVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(rdbShots)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rdbCoctel)
                                .addGap(194, 194, 194)
                                .addComponent(rdbCubetazo)
                                .addGap(222, 222, 222)))
                        .addGap(75, 75, 75))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblValorVenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCategoria)
                            .addComponent(lblNombre1)
                            .addComponent(lblNombre))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(2, 2, 2)
                .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbShots)
                    .addComponent(rdbCoctel)
                    .addComponent(rdbCubetazo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria1)
                    .addComponent(lblCant))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblValorVenta2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTotalCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDeleteSubProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoriaActionPerformed

    private void cmbProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProductosActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        subProducto = new models.Subproductos();
        
        models.Productos subPro = (models.Productos) cmbProductos.getSelectedItem();
        models.Productos dataSubProducto = (models.Productos) subPro;
        
        subProducto.setProductosBySubproducto(subPro);
        subProducto.setCantidad(BigDecimal.valueOf(Double.parseDouble(txtCantidad.getText())));
        
        ArraySubProductos.add(subProducto);
        
        
        
        DefaultTableModel df = (DefaultTableModel) tblSubproductos.getModel();
        int valor =0;
       if(dataSubProducto.getTipoVenta().equalsIgnoreCase("Peso")){
          
            BigDecimal stockSub = dataSubProducto.getStock();
             int stoPromo = stockSub.setScale(0, RoundingMode.DOWN).intValueExact();
             
             int valorXMl = dataSubProducto.getCosto() / stoPromo;
          
             valor = valorXMl * Integer.parseInt(txtCantidad.getText());
             
           
       }else{
         valor = dataSubProducto.getCosto() * Integer.parseInt(txtCantidad.getText());
        }
        totalCosto +=  valor;
        
        
        df.addRow(new Object[]{subProducto,dataSubProducto.getNombre(),Double.parseDouble(txtCantidad.getText()),valor });
        
        tblSubproductos.setModel(df);
        
       lblTotalCosto.setText(String.valueOf(NumberFormat.getCurrencyInstance(new Locale("es", "CO")).format(totalCosto)));
       txtCosto.setText(String.valueOf(totalCosto));
       txtCantidad.setText("");
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void rdbCoctelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCoctelActionPerformed
     mtdComboPeso();
     lblCant.setText("Cantidad (ml):");// TODO add your handling code here:
    }//GEN-LAST:event_rdbCoctelActionPerformed

    private void rdbShotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbShotsActionPerformed
           
    mtdComboPeso();
    lblCant.setText("Cantidad (ml):");
                
// TODO add your handling code here:
    }//GEN-LAST:event_rdbShotsActionPerformed

    private void rdbCubetazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCubetazoActionPerformed
        mtdComboUnidades();  
        lblCant.setText("Cantidad (und):");// TODO add your handling code here:
    }//GEN-LAST:event_rdbCubetazoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       
        models.Categorias cat = (models.Categorias) cmbCategoria.getSelectedItem();
        
        this.producto.setCategorias(cat);
        this.producto.setCodigoBarras(txtCodigo.getText());
        this.producto.setNombre(txtNombre.getText());
        this.producto.setCosto(Integer.parseInt(txtCosto.getText()));
        this.producto.setValor(Integer.parseInt(txtVenta.getText()));
        this.producto.setServicio(false);
        this.producto.setTipoVenta("Unidad");
        this.producto.setImagen("");
        this.producto.setEstado("Activo");
        this.producto.setStock(BigDecimal.valueOf(0));
        
            Transaction trns = null;
            Session session = HibernateUtil.getSessionFactory().openSession();
            try {
                trns = session.beginTransaction();
                session.save(this.producto);
                session.getTransaction().commit();
            
                 for (models.Subproductos dataSub:ArraySubProductos) {
                    
                    subProducto = new models.Subproductos(this.producto,dataSub.getProductosBySubproducto(),dataSub.getCantidad());
                    
                    trns = session.beginTransaction();
                    session.save(subProducto);
                    session.getTransaction().commit();
                    
                }
                JOptionPane.showMessageDialog(null, "Producto Registrado!","Correcto",JOptionPane.INFORMATION_MESSAGE);
                
                
                
                
                  
            
            } catch (RuntimeException e) {
                e.printStackTrace();
            
            } finally {
                session.flush();
                session.close();
                this.dispose();
                new Home_Administracion().setVisible(true);
            } 
      

// TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoActionPerformed

    private void btnDeleteSubProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSubProductoActionPerformed
        
        int fila = tblSubproductos.getSelectedRow();
        
        if(fila != -1){
            
            models.Subproductos subp = (models.Subproductos) tblSubproductos.getValueAt(fila, 0);
            
           String vl = String.valueOf(tblSubproductos.getValueAt(fila, 3));
            
            totalCosto = totalCosto - Integer.parseInt(vl);
            
            lblTotalCosto.setText(String.valueOf(NumberFormat.getCurrencyInstance(new Locale("es", "CO")).format(totalCosto)));
            txtCosto.setText(String.valueOf(totalCosto));
            
            ArraySubProductos.remove(subp);
            
            DefaultTableModel mod = (DefaultTableModel) tblSubproductos.getModel();
            mod.removeRow(fila);
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "Seleccione un Producto","Infomración",JOptionPane.INFORMATION_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteSubProductoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();  
        new Home_Administracion().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    
    public void mtdComboPeso(){
        
        cmbProductos.removeAllItems();
        
        ListProductos = ClProducto.mtdlistarProductosTipo("Peso");
        for (int i = 0; i < ListProductos.size(); i++) {
                cmbProductos.addItem(ListProductos.get(i));
          }
        
    }
    
    public void mtdComboUnidades(){
        
        cmbProductos.removeAllItems();
        
        ListProductos = ClProducto.mtdlistarProductosTipo("Unidad");
        for (int i = 0; i < ListProductos.size(); i++) {
                cmbProductos.addItem(ListProductos.get(i));
          }
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDeleteSubProducto;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    public javax.swing.JComboBox<models.Categorias> cmbCategoria;
    public javax.swing.JComboBox<models.Productos> cmbProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCant;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCategoria1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblTotalCosto;
    private javax.swing.JLabel lblValorVenta;
    private javax.swing.JLabel lblValorVenta2;
    private javax.swing.JRadioButton rdbCoctel;
    private javax.swing.JRadioButton rdbCubetazo;
    private javax.swing.JRadioButton rdbShots;
    private javax.swing.JTable tblSubproductos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtVenta;
    // End of variables declaration//GEN-END:variables
}
