/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.administracion;

import java.awt.Image;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import models.*;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author Manuel Rodriguez
 */
public class frmRegistrarOperacion extends javax.swing.JFrame {

    /**
     * Creates new form frmRegistrarOperacion
     */
    
    public static Turnos turno;
    public static models.Usuarios admin;
    public Home_Administracion parent;
    public List<models.ConceptosOperaciones> listConceptos;
    private models.DisenoFormularios desing;
    
    public frmRegistrarOperacion(Home_Administracion p) {
      
        
        initComponents();
     
        desing.mtdDisenoPantalla(this);
        
        ImageIcon img = new ImageIcon(getClass().getResource("/images/icon_app.png"));
        this.setIconImage(img.getImage().getScaledInstance(180,180, Image.SCALE_SMOOTH));
        
        
        this.parent = p;
        
        
        models.ConceptosOperaciones concep = new models.ConceptosOperaciones();
          listConceptos = concep.listarConceptos();
        for (int i = 0; i < listConceptos.size(); i++) {
                cmbConceptos.addItem(listConceptos.get(i));
          }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboTipoOperacion = new javax.swing.JComboBox<>();
        txtValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtConcepto = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jBExit1 = new javax.swing.JButton();
        cmbConceptos = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logotipo_cliente_small.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NUEVA OPERACIÓN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 140, 336, 70));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Valor:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, 93, 40));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Observaciones:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, -1, 56));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Concepto:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 180, 50));

        comboTipoOperacion.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        comboTipoOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INGRESO", "SALIDA" }));
        comboTipoOperacion.setToolTipText("");
        comboTipoOperacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(comboTipoOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 360, 520, 50));

        txtValor.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 450, 520, 50));

        txtConcepto.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        jScrollPane1.setViewportView(txtConcepto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 510, 108));

        jButton1.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 670, 149, 100));

        jBExit1.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jBExit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/exit.png"))); // NOI18N
        jBExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExit1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 680, 120, 90));

        cmbConceptos.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        cmbConceptos.setToolTipText("");
        cmbConceptos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbConceptosActionPerformed(evt);
            }
        });
        getContentPane().add(cmbConceptos, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 270, 520, -1));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Tipo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, 140, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExit1ActionPerformed
        this.dispose();
       new Home_Administracion(admin).setVisible(true);
    }//GEN-LAST:event_jBExit1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
        Calendar calendario = Calendar.getInstance();

        Date date = calendario.getTime(); 
        
        ConceptosOperaciones concepto = (ConceptosOperaciones) cmbConceptos.getSelectedItem();
        
        Operaciones objOperacion = new Operaciones(concepto,turno, admin,(String) comboTipoOperacion.getSelectedItem(), Integer.parseInt(txtValor.getText()), date, txtConcepto.getText());
       
        Transaction trns = null;
        Session session = HibernateUtil.getSessionFactory().openSession();
        try {
            trns = session.beginTransaction();
           
            session.save(objOperacion);
            session.getTransaction().commit();
            
            //JOptionPane.showMessageDialog(null, "Operación Registrada Con Exito","Exito",JOptionPane.INFORMATION_MESSAGE);
            
            Map<String,Object> params = new HashMap<String,Object>();
            params.put("fecha", date);
            params.put("operacion", objOperacion);
                 
            JasperPrint jasperPrint;
            try {
                jasperPrint = JasperFillManager.fillReport("src/reports/operaciones.jasper",params,new JREmptyDataSource());
                JasperPrintManager.printReport(jasperPrint, false); 
            } catch (JRException ex) {
                Logger.getLogger(frmRegistrarProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            this.dispose();
            new Home_Administracion(admin).setVisible(true);
            
            
        } catch (RuntimeException e) {
            e.printStackTrace();
        } finally {
            session.flush();
            session.close();
        }
       
        
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbConceptosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbConceptosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbConceptosActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
         this.dispose();
         new Home_Administracion(admin).setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<models.ConceptosOperaciones> cmbConceptos;
    private javax.swing.JComboBox<String> comboTipoOperacion;
    private javax.swing.JButton jBExit1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txtConcepto;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
