/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.administracion;

import com.mindfusion.keyboard.Theme;
import com.mindfusion.keyboard.VirtualKeyboard;
import java.awt.Button;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JPopupMenu;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import models.HibernateUtil;
import org.hibernate.Session;
import org.jvnet.substance.SubstanceLookAndFeel;

/**
 *
 * @author bcristan
 */
public class frmRegistrarMesa extends javax.swing.JFrame {

    JTextField txtusu = new JTextField(10);
    JPasswordField txtclave = new JPasswordField(10);
    JPopupMenu pop;
    
    private Home_Administracion Parent;
    private String modo;
    private models.Mesas mesa;
    
    
    public frmRegistrarMesa(Home_Administracion p, String modo, models.Mesas objMesa) {
        
        initComponents();
        
        this.Parent = p;
        this.modo = modo;
        this.mesa = objMesa;
        
        
        if ("Create".equalsIgnoreCase(modo)) {
            lblEstado.setVisible(false);
            txtEstado.setVisible(false);
        }
        
       txtNumero.setText((objMesa != null && objMesa.getNumero() != null) ? String.valueOf(objMesa.getNumero()) : "");
        
        if(objMesa.getTipo()== null){
           
        }else{
             switch(objMesa.getTipo()){
                case "Mesa":
                     txttipo.setSelectedIndex(0);
                break;  
                case "Barra":
                     txttipo.setSelectedIndex(1);
                break;  
                case "Isla":
                     txttipo.setSelectedIndex(2);
                break;  
            }
        }
        
        if(objMesa.getEstado() == null){
            
         }else{
             switch(objMesa.getEstado()){
                case "Activa":
                     txtEstado.setSelectedIndex(0);
                break;  
                case "Inactiva":
                     txtEstado.setSelectedIndex(1);
                break;  

            }
        }

       
        
        
  
    }
    /**
     * Creates new form CUsuarios
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        txtEstado = new javax.swing.JComboBox<String>();
        txttipo = new javax.swing.JComboBox<String>();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 700));
        setMinimumSize(new java.awt.Dimension(900, 700));
        setPreferredSize(new java.awt.Dimension(900, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logotipo_cliente_small.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 39, 250, 179));

        txtNumero.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 252, 416, 41));

        lblEstado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEstado.setText("Estado:");
        getContentPane().add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 373, 169, 44));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Número:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 258, 169, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Tipo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 312, 169, 42));

        btnGuardar.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, -1, 61));

        txtEstado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activa", "Inactiva" }));
        txtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 373, 416, 44));

        txttipo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txttipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mesa", "Barra", "Isla" }));
        txttipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttipoActionPerformed(evt);
            }
        });
        getContentPane().add(txttipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 311, 416, 44));

        btnSalir.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/exit.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 160, 61));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoActionPerformed

    private void txttipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttipoActionPerformed
  /*
  * Funcion : Guardar Mesa
    Nota : se utiliza para actualizar e insertar mesa ademas de validacion de la data 
  * Desarrollador :(Brayan cristancho) 
  * Fecha de creacion : 04/08/2018**/
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       
        String pin1;
        if (isInteger(txtNumero.getText())) {
            try {
                if (!txtNumero.getText().isEmpty()) {
                    
                    Session sesion = HibernateUtil.getSessionFactory().openSession();
                    if (this.modo.equalsIgnoreCase("Create")) {
                        mesa = new models.Mesas(txtNumero.getText(), txttipo.getSelectedItem().toString(), "Activa");
                        
                        sesion.beginTransaction();
                        sesion.save(mesa);
                        sesion.getTransaction().commit();
                    } else {
                        
                       
                        mesa.setTipo(txttipo.getSelectedItem().toString());
                        mesa.setEstado(txtEstado.getSelectedItem().toString());
                        mesa.setNumero(txtNumero.getText());
                        
                       
                        sesion.beginTransaction();
                        sesion.update(mesa);
                        sesion.getTransaction().commit();
                        
                    }
                    
                    sesion.flush();
                    sesion.close();
                    this.dispose();
                    
                    new frmListarMesas(Parent).setVisible(true);
                    
                } else {
                    JOptionPane.showMessageDialog(null, "Complete todos los campos");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "(Numero mesa) No Disponible"+e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "(Numero) debe ser  numérico");
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        new frmListarMesas(Parent).setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    /*validar entero pin */
    public boolean isInteger(String numero) {
        try {
            Integer.parseInt(numero);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblEstado;
    public javax.swing.JComboBox<String> txtEstado;
    public javax.swing.JTextField txtNumero;
    public javax.swing.JComboBox<String> txttipo;
    // End of variables declaration//GEN-END:variables
}
