/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.administracion;

import forms.frmMesas;
import static forms.login.sesion;
import static forms.login.turno;
import java.awt.Color;
import java.awt.Image;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import models.HibernateUtil;
import models.Usuarios;
import models.Ventas;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.jvnet.substance.SubstanceLookAndFeel;

/**
 *
 * @author Manuel Rodriguez
 */
public class frmUpdateProducto extends javax.swing.JFrame {

    /**
     * Creates new form frmUpdateProducto
     */
    
    private Home_Administracion Parent;
    private models.Productos producto;
    private List<models.Categorias> listCategorias;
    private boolean autorizacion = false;
    public static Usuarios usuario;

    
    public frmUpdateProducto(Home_Administracion P,models.Productos pro) {
        initComponents();
        this.Parent = P;
        this.producto = pro;
        
        this.setLocationRelativeTo(this);
        ImageIcon img = new ImageIcon(getClass().getResource("/images/icon_app.png"));
        this.setIconImage(img.getImage().getScaledInstance(180,180, Image.SCALE_SMOOTH));
        this.setTitle("POSystem - Powered by KIM-Solutions");
        
        
        models.Categorias cate = new models.Categorias();
          listCategorias = cate.listarCategorias();
        
          int p = 0;
          
        for (int i = 0; i < listCategorias.size(); i++) {
            if(this.producto.getCategorias().getIdCategoria() == listCategorias.get(i).getIdCategoria())
                p = i;
                cmbCategoria.addItem(listCategorias.get(i));
          }
        
        txtNombre.setText(this.producto.getNombre());
        txtCosto.setText(String.valueOf(this.producto.getCosto()));
        txtVenta.setText(String.valueOf(this.producto.getValor(/*this.producto.getIdProducto()*/)));
        txtCantidad.setText(String.valueOf(this.producto.getStock()));
        txtCantidad.setEditable(false);
        txtNombre.setEditable(false);
        
        if(this.producto.isServicio() == true)
            rdbServicio.setSelected(true);
        
        cmbCategoria.setSelectedIndex(p);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblValorVenta = new javax.swing.JLabel();
        txtVenta = new javax.swing.JTextField();
        lblCategoria = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        rdbServicio = new javax.swing.JRadioButton();
        btnEditar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnDesbloquear = new javax.swing.JButton();
        btnDesbloquear2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 720));
        setMinimumSize(new java.awt.Dimension(1024, 700));
        setPreferredSize(new java.awt.Dimension(1024, 700));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logotipo_cliente_small.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Editar Producto");

        txtCosto.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel3.setText("VALOR COMPRA");

        lblNombre.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        lblNombre.setText("NOMBRE");

        txtNombre.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N

        lblValorVenta.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        lblValorVenta.setText("VALOR VENTA");

        txtVenta.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N

        lblCategoria.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        lblCategoria.setText("CATEGORIA");

        cmbCategoria.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cmbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriaActionPerformed(evt);
            }
        });

        rdbServicio.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        rdbServicio.setText("Servicio");
        rdbServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbServicioActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/exit.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel4.setText("CANTIDAD");

        txtCantidad.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N

        btnDesbloquear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/desbloquear.png"))); // NOI18N
        btnDesbloquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesbloquearActionPerformed(evt);
            }
        });

        btnDesbloquear2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/desbloquear.png"))); // NOI18N
        btnDesbloquear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesbloquear2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(239, 239, 239))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(234, 234, 234))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(226, 226, 226))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addComponent(btnDesbloquear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCosto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDesbloquear2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmbCategoria, 0, 346, Short.MAX_VALUE)
                        .addComponent(lblCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblValorVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtVenta)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbCategoria)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnDesbloquear2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblValorVenta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCosto, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(txtVenta))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDesbloquear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(rdbServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoriaActionPerformed

    private void rdbServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbServicioActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
       new Home_Administracion(usuario).setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
            
       
        this.producto.setNombre(txtNombre.getText());
        this.producto.setCosto(Integer.parseInt(txtCosto.getText()));
        this.producto.setValor(Integer.parseInt(txtVenta.getText()));
        
        models.Categorias cat = (models.Categorias) cmbCategoria.getSelectedItem();
        this.producto.setCategorias(cat);
        
        boolean servicio = false;
         if(rdbServicio.isSelected()){
           servicio = true;
         }
        this.producto.setServicio(servicio);
        
        if(autorizacion)
            this.producto.setStock(BigDecimal.valueOf(Double.parseDouble(txtCantidad.getText())));
        
            Transaction trns = null;
            Session session = HibernateUtil.getSessionFactory().openSession();
            try {
                trns = session.beginTransaction();
                session.update(this.producto);
                session.getTransaction().commit();
            
                
                JOptionPane.showMessageDialog(null, "Producto Actualizado!","Correcto",JOptionPane.INFORMATION_MESSAGE);
                
                
                this.dispose();
                new frmListadoProductos(Parent).setVisible(true);
               
                  
            
            } catch (RuntimeException e) {
                e.printStackTrace();
            
            } finally {
                session.flush();
                session.close();
            } 
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnDesbloquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesbloquearActionPerformed
        
            JPasswordField pf = new JPasswordField(4);
            int okCxl = JOptionPane.showConfirmDialog(null, pf, "Digite Clave de Gerencia", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

            if (okCxl == JOptionPane.OK_OPTION) {
                
                String password = new String(pf.getPassword());
                
                
                models.Usuarios user = models.Usuarios.validPIN(password,sesion);
        
                    if(user != null){
                        if(user.getEstado().equalsIgnoreCase("Activo")){
                            switch (user.getPerfil()){
                                case "Gerente":
                                    
                                    txtCantidad.setEditable(true);
                                    autorizacion = true;
                                    break;
                                case "Administrador":
                                    
                                    JOptionPane.showMessageDialog(rootPane, "<html>Señor: "+user.getNombres()+" <br>No cuenta con permisos para realizar esta Acción</html>","Información",JOptionPane.INFORMATION_MESSAGE);
                                    break;
                                case "Mesero":
                                    JOptionPane.showMessageDialog(rootPane, "<html>Señor: "+user.getNombres()+" <br>No cuenta con permisos para realizar esta Acción</html>","Información",JOptionPane.INFORMATION_MESSAGE);
                                    break;
                            }
                        }else{
                            JOptionPane.showMessageDialog(rootPane, "Usuario Inactivo","Error",JOptionPane.ERROR_MESSAGE);
                        }
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "No Existe Este Usuario","Error",JOptionPane.ERROR_MESSAGE);
                    }
                
                
            }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnDesbloquearActionPerformed

    private void btnDesbloquear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesbloquear2ActionPerformed
       JPasswordField pf = new JPasswordField(4);
            int okCxl = JOptionPane.showConfirmDialog(null, pf, "Digite Clave de Gerencia", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

            if (okCxl == JOptionPane.OK_OPTION) {
                
                String password = new String(pf.getPassword());
                
                
                models.Usuarios user = models.Usuarios.validPIN(password,sesion);
        
                    if(user != null){
                        if(user.getEstado().equalsIgnoreCase("Activo")){
                            switch (user.getPerfil()){
                                case "Gerente":
                                    
                                    txtNombre.setEditable(true);
                                    autorizacion = true;
                                    break;
                                case "Administrador":
                                    
                                    JOptionPane.showMessageDialog(rootPane, "<html>Señor: "+user.getNombres()+" <br>No cuenta con permisos para realizar esta Acción</html>","Información",JOptionPane.INFORMATION_MESSAGE);
                                    break;
                                case "Mesero":
                                    JOptionPane.showMessageDialog(rootPane, "<html>Señor: "+user.getNombres()+" <br>No cuenta con permisos para realizar esta Acción</html>","Información",JOptionPane.INFORMATION_MESSAGE);
                                    break;
                            }
                        }else{
                            JOptionPane.showMessageDialog(rootPane, "Usuario Inactivo","Error",JOptionPane.ERROR_MESSAGE);
                        }
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "No Existe Este Usuario","Error",JOptionPane.ERROR_MESSAGE);
                    }
                
                
            }  // TODO add your handling code here:
    }//GEN-LAST:event_btnDesbloquear2ActionPerformed

   
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesbloquear;
    private javax.swing.JButton btnDesbloquear2;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnSalir;
    public javax.swing.JComboBox<models.Categorias> cmbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblValorVenta;
    private javax.swing.JRadioButton rdbServicio;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtVenta;
    // End of variables declaration//GEN-END:variables
}
