/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.administracion;

import forms.frmMesas;
import forms.login;
import java.awt.BorderLayout;
import java.awt.Image;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import models.HibernateUtil;
import models.Ingresoproductos;
import models.Pedidos;
import models.Turnos;
import models.Usuarios;
import models.Ventas;
import models.dataChartVentas;
import models.dataIProductos;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JRViewer;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.jvnet.substance.SubstanceLookAndFeel;

/**
 *
 * @author bcristan
 */
public class frmVentas extends javax.swing.JFrame {

    /**
     * Creates new form Home_Gerencia
     */
    
    public Turnos objTurno = new Turnos();
    public static Turnos turnoAbierto;
    public static models.Usuarios admin;
    public Calendar calendario;
    private Home_Administracion Parent;
    public static Usuarios usuario;
    
    public frmVentas(Home_Administracion p) {
        initComponents();
        this.Parent = p;
        this.setLocationRelativeTo(this);
        ImageIcon img = new ImageIcon(getClass().getResource("/images/icon_app.png"));
        this.setIconImage(img.getImage().getScaledInstance(180,180, Image.SCALE_SMOOTH));
        this.setTitle("POSystem - Powered by KIM-Solutions");
        
        Session sesion = HibernateUtil.getSessionFactory().openSession();
        Query q = sesion.createQuery("FROM Ventas WHERE fecha BETWEEN ?1 AND ?2");
        calendario = new GregorianCalendar();
        calendario.setTime(new Date());
        
        q.setString(1, calendario.get(Calendar.YEAR)+"-"+(calendario.get(Calendar.MONTH)+1)+"-01 00:00:00");
        q.setString(2, calendario.get(Calendar.YEAR)+"-"+(calendario.get(Calendar.MONTH)+1)+"-31 23:59:00");
        
        
        ArrayList ventas = (ArrayList) q.list();
        ArrayList<dataChartVentas> dataVentas = new ArrayList();
        
        Vector fechas = new Vector();
        SimpleDateFormat df = new SimpleDateFormat("YYYY-MM-dd");
        for(Object obj : ventas){
            Ventas venta = (Ventas) obj;
            
            String fecha = df.format(venta.getFecha());
            int vendido = venta.getTotal();
            int ganancias = venta.getGanancias();
            
            int data = fechas.indexOf(fecha);
            if(data==-1){
                dataVentas.add(new dataChartVentas(fecha,vendido,ganancias));
                fechas.add(fecha);
            }else{
                dataChartVentas dCV = dataVentas.get(data);
                dCV.setVentas(dCV.getVentas()+vendido);
                dCV.setGanancias(dCV.getGanancias()+ganancias);
                dataVentas.set(data, dCV);
            }
        }
        
        
         try {

            JasperPrint print = JasperFillManager.fillReport("src/reports/chartVentas.jasper", null, new JRBeanCollectionDataSource(dataVentas));

            jPEstadisticas.removeAll();
            jPEstadisticas.setLayout(new BorderLayout());
            jPEstadisticas.repaint();
            jPEstadisticas.add(new JRViewer(print));
            jPEstadisticas.revalidate();
                   

        } catch (JRException e) {
            e.printStackTrace();
            System.exit(1);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jBExit = new javax.swing.JButton();
        jPEstadisticas = new javax.swing.JPanel();
        lblDia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logotipo_cliente_small.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 250, 160));

        jBExit.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jBExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/exit.png"))); // NOI18N
        jBExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitActionPerformed(evt);
            }
        });
        getContentPane().add(jBExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 640, 110, 70));
        getContentPane().add(jPEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 1000, 450));

        lblDia.setFont(new java.awt.Font("Arial", 0, 70)); // NOI18N
        lblDia.setText("Informe Ventas");
        getContentPane().add(lblDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 500, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

  /* Funcion : regresar
    Nota : 
  * Desarrollador :(Brayan cristancho) 
  * Fecha de creacion : 01/08/2018**/
    private void jBExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitActionPerformed
        this.dispose();
       new Home_Administracion(usuario).setVisible(true);
    }//GEN-LAST:event_jBExitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPEstadisticas;
    public javax.swing.JLabel lblDia;
    // End of variables declaration//GEN-END:variables
}
