package models;
// Generated 18/08/2018 10:09:30 AM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 * Categorias generated by hbm2java
 */
public class Categorias  implements java.io.Serializable {


     private Integer idCategoria;
     private String nombre;
     private String tipo;
     private Set productoses = new HashSet(0);

    public Categorias() {
    }

	
    public Categorias(String nombre, String tipo) {
        this.nombre = nombre;
        this.tipo = tipo;
    }
    public Categorias(String nombre, String tipo, Set productoses) {
       this.nombre = nombre;
       this.tipo = tipo;
       this.productoses = productoses;
    }
   
    public Integer getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(Integer idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set productoses) {
        this.productoses = productoses;
    }
    
    public String toString(){
        return this.nombre;
    }
    
    
    
    
    public List<models.Categorias> listarCategorias() {
        List<Categorias> categorias = new ArrayList<Categorias>();
        Transaction trns = null;
        Session session = HibernateUtil.getSessionFactory().openSession();
        try {
            session.getTransaction().begin();
            categorias = session.createQuery("SELECT C FROM Categorias C").list();
            session.getTransaction().commit();
        } catch (RuntimeException e) {
            e.printStackTrace();
        } finally {
            session.flush();
            session.close();
        }
        return categorias;
    }
  

    


}


