package models;
// Generated 29/09/2018 08:57:50 AM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 * ConceptosOperaciones generated by hbm2java
 */
public class ConceptosOperaciones  implements java.io.Serializable {


     private Integer idConceptoOperacion;
     private String nombre;
     private String descripcion;
     private Set operacioneses = new HashSet(0);

    public ConceptosOperaciones() {
    }

	
    public ConceptosOperaciones(String nombre, String descripcion) {
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public ConceptosOperaciones(String nombre, String descripcion, Set operacioneses) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.operacioneses = operacioneses;
    }
   
    public Integer getIdConceptoOperacion() {
        return this.idConceptoOperacion;
    }
    
    public void setIdConceptoOperacion(Integer idConceptoOperacion) {
        this.idConceptoOperacion = idConceptoOperacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getOperacioneses() {
        return this.operacioneses;
    }
    
    public void setOperacioneses(Set operacioneses) {
        this.operacioneses = operacioneses;
    }
    
    public String toString(){
        return this.nombre;
    }
    
    
      public List<models.ConceptosOperaciones> listarConceptos() {
        List<ConceptosOperaciones> conceptos = new ArrayList<ConceptosOperaciones>();
        Session session = HibernateUtil.getSessionFactory().openSession();
        try {
            session.getTransaction().begin();
            conceptos = session.createQuery(" FROM ConceptosOperaciones C").list();
            session.getTransaction().commit();
        } catch (RuntimeException e) {
            e.printStackTrace();
        } finally {
            session.close();
        }
        return conceptos;
    }

       public List<models.ConceptosOperaciones> mtdFiltro(String cadena ) {
        List<ConceptosOperaciones> conceptos = new ArrayList<ConceptosOperaciones>();
        Session session = HibernateUtil.getSessionFactory().openSession();
        try {
            session.getTransaction().begin();
            Query q = session.createQuery("FROM ConceptosOperaciones C WHERE C.nombre LIKE :parametro");
            q.setString("parametro",'%'+cadena+'%');
            conceptos = q.list();
            session.getTransaction().commit();
        } catch (RuntimeException e) {
            e.printStackTrace();
        } finally {
            session.close();
        }
        return conceptos;
    }




}


