package models;
// Generated 18/08/2018 10:09:30 AM by Hibernate Tools 4.3.1



/**
 * Descuentos generated by hbm2java
 */
public class Descuentos  implements java.io.Serializable {


     private Integer idDescuento;
     private Pedidos pedidos;
     private String concepto;
     private int valor;

    public Descuentos() {
    }

    public Descuentos(Pedidos pedidos, String concepto, int valor) {
       this.pedidos = pedidos;
       this.concepto = concepto;
       this.valor = valor;
    }
   
    public Integer getIdDescuento() {
        return this.idDescuento;
    }
    
    public void setIdDescuento(Integer idDescuento) {
        this.idDescuento = idDescuento;
    }
    public Pedidos getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Pedidos pedidos) {
        this.pedidos = pedidos;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }
    public int getValor() {
        return this.valor;
    }
    
    public void setValor(int valor) {
        this.valor = valor;
    }




}


