package models;
// Generated 29/09/2018 08:57:50 AM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 * Facturas generated by hbm2java
 */
public class Facturas  implements java.io.Serializable {


     private Integer idFactura;
     private String codigo;
     private String nombreProveedor;
     private Date fecha;
      private Set ingresoproductoses = new HashSet(0);

    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    

    public Facturas() {
    }

	
    public Facturas(String codigo, String nombreProveedor,Date fecha) {
        this.codigo = codigo;
        this.nombreProveedor = nombreProveedor;
        this.fecha = fecha;
    }
    public Facturas(String codigo, String nombreProveedor,Date fecha, Set ingresoproductoses) {
       this.codigo = codigo;
       this.nombreProveedor = nombreProveedor;
       this.fecha = fecha;
       this.ingresoproductoses = ingresoproductoses;
    }
   
    public Integer getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombreProveedor() {
        return this.nombreProveedor;
    }
    
    public void setNombreProveedor(String nombreProveedor) {
        this.nombreProveedor = nombreProveedor;
    }
    public Set getIngresoproductoses() {
        return this.ingresoproductoses;
    }
    
    public void setIngresoproductoses(Set ingresoproductoses) {
        this.ingresoproductoses = ingresoproductoses;
    }
    
     public ArrayList<Ingresoproductos> getPedidosArray(){
        return new ArrayList(this.getIngresoproductoses());
    }
    
     public int getTotal(){
        int total = 0;
        
        for(Object Objpedido : this.getPedidos()){
            
            Ingresoproductos pedido = (Ingresoproductos) Objpedido;
            
            total += pedido.getCostoIngreso() * pedido.getCantidad();
        }
        
        //DESCUENTOS DE LA VENTA POR CADA PEDIDO
        
        return total;
    }
     
     public ArrayList<Ingresoproductos> getPedidos(){
        ArrayList<Ingresoproductos> pedidos = new ArrayList();
        for(Object o : this.getIngresoproductoses()){
            Ingresoproductos p = (Ingresoproductos) o;
            
                pedidos.add(p);
           
        }
        return pedidos;
    }
     
      public List<models.Facturas> listarFacturas() {
        List<Facturas> fact = new ArrayList<Facturas>();
        Transaction trns = null;
        Session session = HibernateUtil.getSessionFactory().openSession();
        try {
            session.getTransaction().begin();
            fact = session.createQuery("FROM Facturas F").list();
            session.getTransaction().commit();
        } catch (RuntimeException e) {
            e.printStackTrace();
        } finally {
            session.close();
        }
        return fact;
    }

       public List<models.Facturas> mtdFiltro(String cadena ) {
        List<Facturas> fac = new ArrayList<Facturas>();
        Transaction trns = null;
        Session session = HibernateUtil.getSessionFactory().openSession();
        try {
            session.getTransaction().begin();
            Query q = session.createQuery("FROM Facturas F WHERE F.nombreProveedor LIKE :parametro OR F.codigo LIKE :parametro2");
            q.setString("parametro",'%'+cadena+'%');
            q.setString("parametro2",'%'+cadena+'%');
            
            fac = q.list();

            session.getTransaction().commit();
        } catch (RuntimeException e) {
            e.printStackTrace();
        } finally {
            session.close();
        }
        return fac;
    }

       public Facturas mtdUniqueFactura(int factura) {
        
        Facturas fact = new Facturas();
        Transaction trns = null;
        Session session = HibernateUtil.getSessionFactory().openSession();
        try {
            session.getTransaction().begin();
            Query q = session.createQuery("SELECT F FROM Facturas F WHERE id_factura = "+factura);
            
             fact = (models.Facturas) q.uniqueResult();
            session.getTransaction().commit();
        } catch (RuntimeException e) {
            e.printStackTrace();
        } finally {
            session.close();
        }

        return fact;

    }

       public Facturas mtdVerifiqueCode(String codigo) {
        
        Facturas fact = new Facturas();
        Transaction trns = null;
        Session session = HibernateUtil.getSessionFactory().openSession();
        try {
            session.getTransaction().begin();
            Query q = session.createQuery("SELECT F FROM Facturas F WHERE  codigo = "+codigo);
            
             fact = (models.Facturas) q.uniqueResult();
            session.getTransaction().commit();
        } catch (RuntimeException e) {
            e.printStackTrace();
        } finally {
            session.close();
        }

        return fact;

    }

       public boolean mtdEliminarFactura(Facturas fac){
          Session session = HibernateUtil.getSessionFactory().openSession();
        try {
            session.getTransaction().begin();
            session.delete(fac);
            session.getTransaction().commit();
        } catch (RuntimeException e) {
            e.printStackTrace();
        } finally {
            session.close();
        } 
        
        return true;
       }
       




}


