package models;
// Generated 30/08/2018 01:43:28 PM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Date;
import models.Productos;

/**
 * Ingresoproductos generated by hbm2java
 */
public class Ingresoproductos  implements java.io.Serializable {


     private Integer idIngresoProducto;
     private Facturas facturas;
     private Productos productos;
     private int cantidad;
     private Date fecha;
     private double costoIngreso;

    public Ingresoproductos() {
    }

    public Ingresoproductos(Facturas facturas, Productos productos, int cantidad, Date fecha, float costoIngreso) {
       this.facturas = facturas;
       this.productos = productos;
       this.cantidad = cantidad;
       this.fecha = fecha;
       this.costoIngreso = costoIngreso;
    }
   
    public Integer getIdIngresoProducto() {
        return this.idIngresoProducto;
    }
    
    public void setIdIngresoProducto(Integer idIngresoProducto) {
        this.idIngresoProducto = idIngresoProducto;
    }
    public Facturas getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Facturas facturas) {
        this.facturas = facturas;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public double getCostoIngreso() {
        return this.costoIngreso;
    }
    
    public void setCostoIngreso(double costoIngreso) {
        this.costoIngreso = costoIngreso;
    }
    
  




}


