package models;
// Generated 18/08/2018 10:09:30 AM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 * Mesas generated by hbm2java
 */
public class Mesas  implements java.io.Serializable {
     private Integer idMesa;
     private String numero;
     private String tipo;
     private String estado;
     private Set ventases = new HashSet(0);

    public Mesas() {
    }

	
    public Mesas(String numero, String tipo, String estado) {
        this.numero = numero;
        this.tipo = tipo;
        this.estado = estado;
    }
    public Mesas(String numero, String tipo, String estado, Set ventases) {
       this.numero = numero;
       this.tipo = tipo;
       this.estado = estado;
       this.ventases = ventases;
    }
   
    public Integer getIdMesa() {
        return this.idMesa;
    }
    
    public void setIdMesa(Integer idMesa) {
        this.idMesa = idMesa;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getVentases() {
        return this.ventases;
    }
    
    public void setVentases(Set ventases) {
        this.ventases = ventases;
    }
    
    
    
    
    
    
    public List<models.Mesas> listarmesas() {
        
        List<Mesas> mesas = new ArrayList<Mesas>();
        Transaction trns = null;
        Session session = HibernateUtil.getSessionFactory().openSession();
        try {
            session.getTransaction().begin();
            mesas = session.createQuery("SELECT M FROM Mesas M").list();
            session.getTransaction().commit();
        } catch (RuntimeException e) {
            e.printStackTrace();
        } finally {
            session.flush();
            session.close();
        }
        return mesas;
    }
    
    public List<models.Mesas> mtdList(String tipo) {
        
        List<Mesas> mesas = new ArrayList<Mesas>();
        Transaction trns = null;
        Session session = HibernateUtil.getSessionFactory().openSession();
        try {
            session.getTransaction().begin();
            mesas = session.createQuery("SELECT M FROM Mesas M WHERE M.tipo = '"+tipo+"'").list();
            session.getTransaction().commit();
        } catch (RuntimeException e) {
            e.printStackTrace();
        } finally {
            session.flush();
            session.close();
        }
        return mesas;
    }
    
      public models.Mesas mtdGetMesaLlevar() {
        
        models.Mesas mesa = null;
        Transaction trns = null;
        Session session = HibernateUtil.getSessionFactory().openSession();
        try {
            session.getTransaction().begin();
            mesa = (Mesas) session.createQuery("SELECT M FROM Mesas M WHERE M.numero = '00'").uniqueResult();
            session.getTransaction().commit();
        } catch (RuntimeException e) {
            e.printStackTrace();
        } finally {
            session.flush();
            session.close();
        }
        return mesa;
    }
    
    
  public models.Ventas mtdDisponibilidad(int IdMesa,int IdTurno){
      int cantidad = 0;
      
            Ventas mesaOcupada = new Ventas();
        Transaction trns = null;
        Session session = HibernateUtil.getSessionFactory().openSession();
        try {
           session.getTransaction().begin();
            Query q = session.createQuery("FROM Ventas V   WHERE mesa ="+IdMesa+" AND estado = 'Abierta' AND turno ="+IdTurno);
            
            mesaOcupada = (Ventas) q.uniqueResult();
            session.getTransaction().commit();
        } catch (RuntimeException e) {
            e.printStackTrace();
        } finally {
            session.flush();
            session.close();
        }
      
      return mesaOcupada;
  }
    
    
 




}


