package models;
// Generated 18/08/2018 10:09:30 AM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 * Operaciones generated by hbm2java
 */
public class Operaciones  implements java.io.Serializable {


     private Integer idOperacion;
     private ConceptosOperaciones conceptosOperaciones;
     private Turnos turnos;
     private Usuarios usuarios;
     private String tipo;
     private int valor;
     private Date fecha;
     private String concepto;

    public Operaciones() {
    }

    public Operaciones(ConceptosOperaciones conceptosOperaciones, Turnos turnos, Usuarios usuarios, String tipo, int valor, Date fecha, String concepto) {
       this.conceptosOperaciones = conceptosOperaciones;
       this.turnos = turnos;
       this.usuarios = usuarios;
       this.tipo = tipo;
       this.valor = valor;
       this.fecha = fecha;
       this.concepto = concepto;
    }
   
    public Integer getIdOperacion() {
        return this.idOperacion;
    }
    
    public void setIdOperacion(Integer idOperacion) {
        this.idOperacion = idOperacion;
    }
    public ConceptosOperaciones getConceptosOperaciones() {
        return this.conceptosOperaciones;
    }
    
    public void setConceptosOperaciones(ConceptosOperaciones conceptosOperaciones) {
        this.conceptosOperaciones = conceptosOperaciones;
    }
    public Turnos getTurnos() {
        return this.turnos;
    }
    
    public void setTurnos(Turnos turnos) {
        this.turnos = turnos;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public int getValor() {
        return this.valor;
    }
    
    public void setValor(int valor) {
        this.valor = valor;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }
    
    public List<models.Operaciones> mtdListOperaciones(int IdTurno) {
        
        List<Operaciones> Operaciones = new ArrayList<Operaciones>();
        Transaction trns = null;
        Session session = HibernateUtil.getSessionFactory().openSession();
        try {
            session.getTransaction().begin();
            Operaciones = session.createQuery("SELECT O FROM Operaciones O WHERE turno = "+IdTurno).list();
            session.getTransaction().commit();
        } catch (RuntimeException e) {
            e.printStackTrace();
        } finally {
            session.flush();
            session.close();
        }
        return Operaciones;
    }
    
    public List<models.Operaciones> mtdFiltro(String cadena) {
        List<Operaciones> opera = new ArrayList<Operaciones>();
        Transaction trns = null;
        Session session = HibernateUtil.getSessionFactory().openSession();
        try {
            session.getTransaction().begin();
            Query q = session.createQuery("FROM Operaciones P WHERE P.concepto LIKE :parametro");
            q.setString("parametro",'%'+cadena+'%');
            
            opera = q.list();
            session.getTransaction().commit();
        } catch (RuntimeException e) {
            e.printStackTrace();
        } finally {
            session.flush();
            session.close();
        }
        return opera;
    }

    
    


}


