package models;
// Generated 11/09/2018 03:42:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PreciosEspeciales generated by hbm2java
 */
public class PreciosEspeciales  implements java.io.Serializable {


     private Integer idPrecioEspecial;
     private Date fechaInicio;
     private Date fechaFin;
     private String estado;
     private Set productosEspecialeses = new HashSet(0);

    public PreciosEspeciales() {
    }

	
    public PreciosEspeciales(Date fechaInicio, Date fechaFin, String estado) {
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.estado = estado;
    }
    public PreciosEspeciales(Date fechaInicio, Date fechaFin, String estado, Set productosEspecialeses) {
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.estado = estado;
       this.productosEspecialeses = productosEspecialeses;
    }
   
    public Integer getIdPrecioEspecial() {
        return this.idPrecioEspecial;
    }
    
    public void setIdPrecioEspecial(Integer idPrecioEspecial) {
        this.idPrecioEspecial = idPrecioEspecial;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getProductosEspecialeses() {
        return this.productosEspecialeses;
    }
    
    public void setProductosEspecialeses(Set productosEspecialeses) {
        this.productosEspecialeses = productosEspecialeses;
    }




}


