package models;
// Generated 11/09/2018 03:42:42 PM by Hibernate Tools 4.3.1

import models.Productos;




/**
 * ProductosEspeciales generated by hbm2java
 */
public class ProductosEspeciales  implements java.io.Serializable {


     private Integer idProductoEspecial;
     private PreciosEspeciales preciosEspeciales;
     private Productos productos;
     private int valor;

    public ProductosEspeciales() {
    }

    public ProductosEspeciales(PreciosEspeciales preciosEspeciales, Productos productos, int valor) {
       this.preciosEspeciales = preciosEspeciales;
       this.productos = productos;
       this.valor = valor;
    }
   
    public Integer getIdProductoEspecial() {
        return this.idProductoEspecial;
    }
    
    public void setIdProductoEspecial(Integer idProductoEspecial) {
        this.idProductoEspecial = idProductoEspecial;
    }
    public PreciosEspeciales getPreciosEspeciales() {
        return this.preciosEspeciales;
    }
    
    public void setPreciosEspeciales(PreciosEspeciales preciosEspeciales) {
        this.preciosEspeciales = preciosEspeciales;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public int getValor() {
        return this.valor;
    }
    
    public void setValor(int valor) {
        this.valor = valor;
    }




}


