package models;
// Generated 18/08/2018 10:09:30 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer idProducto;
     private Categorias categorias;
     private String nombre;
     private String codigoBarras;
     private int costo;
     private int valor;
     private BigDecimal stock;
     private boolean servicio;
     private String tipoVenta;
     private String imagen;
     private String estado;
     private Set subproductosesForProducto = new HashSet(0);
     private Set subproductosesForSubproducto = new HashSet(0);
     private Set pedidoses = new HashSet(0);
     private Set ingresoproductoses = new HashSet(0);
     private Set productosEspecialeses = new HashSet(0);

   

    public Productos() {
    }

	
    public Productos(Categorias categorias, String nombre, String codigo ,int costo, int valor, BigDecimal stock,boolean servicio, String tipoVenta, String imagen, String estado) {
        this.categorias = categorias;
        this.nombre = nombre;
        this.codigoBarras = codigo;
        this.costo = costo;
        this.valor = valor;
        this.stock = stock;
        this.tipoVenta = tipoVenta;
        this.imagen = imagen;
        this.estado = estado;
        this.servicio = servicio;
    }
    public Productos(Categorias categorias, String nombre, String codigo,int costo, int valor, BigDecimal stock, boolean servicio,String tipoVenta, String imagen, String estado, Set subproductosesForProducto, Set subproductosesForSubproducto, Set pedidoses,Set ingresoproductoses,Set productosEspecialeses) {
       this.categorias = categorias;
       this.nombre = nombre;
       this.codigoBarras = codigo;
       this.costo = costo;
       this.valor = valor;
       this.stock = stock;
       this.tipoVenta = tipoVenta;
       this.imagen = imagen;
       this.estado = estado;
       this.subproductosesForProducto = subproductosesForProducto;
       this.subproductosesForSubproducto = subproductosesForSubproducto;
       this.pedidoses = pedidoses;
       this.servicio = servicio;
       this.ingresoproductoses = ingresoproductoses;
       this.productosEspecialeses = productosEspecialeses;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
     public String getCodigoBarras() {
        return this.codigoBarras;
    }
    
    public void setCodigoBarras(String cod) {
        this.codigoBarras = cod;
    }
    public int getCosto() {
        return this.costo;
    }
    
    public void setCosto(int costo) {
        this.costo = costo;
    }
    public boolean isServicio() {
        return this.servicio;
    }
    
    public void setServicio(boolean serv) {
        this.servicio = serv;
    }
    
    public int getValor() {
        
        int valor = 5000;
        Calendar calendario = Calendar.getInstance();
        
        Date date = calendario.getTime();             
        SimpleDateFormat format_hora_completa = new SimpleDateFormat("HH");
        
        String hora = format_hora_completa.format(date);
        int hora_int = Integer.parseInt(hora);
        System.out.println("id es : "+getIdProducto()+ "la hora: "+hora_int);
        
        
      if(getIdProducto() != null){
        
       if((hora_int >= 20 && hora_int <= 24) || (hora_int >= 0 && hora_int <= 03) ){
           
           switch(getIdProducto()){
                
               //NACIONALES
                case 7:  valor = 5000; break;
                case 10: valor = 5000;break;
                case 11: valor = 5000;break;
                case 12: valor = 5000;break;
                //LINEA CLUB    
                case 8:  valor = 7000; break;
                case 9:  valor = 7000;break;
                case 14: valor = 7000;break;
                case 15: valor = 7000;break;
                //REDS 
                case 13: valor = 7000;break;
                default:
                   valor = this.valor;
                break;
           }
           
          
             
       }else{
           switch(getIdProducto()){
               //NACIONALES
                case 7:  valor = 3500; break;
                case 10: valor = 3500;break;
                case 11: valor = 3500;break;
                case 12: valor = 3500;break;
                //LINEA CLUB    
                case 8:  valor = 4000; break;
                case 9:  valor = 4000;break;
                case 14: valor = 4000;break;
                case 15: valor = 4000;break;
                //REDS 
                case 13: valor = 3500;break;
                default:
                   valor = this.valor;
                break;
           }
       }
      }else{
          valor = this.valor;
      }
        return valor;
    }
    
    public void setValor(int valor) {
        this.valor = valor;
    }
    public BigDecimal getStock() {
        return this.stock;
    }
    
    public void setStock(BigDecimal stock) {
        this.stock = stock;
    }
    public String getTipoVenta() {
        return this.tipoVenta;
    }
    
    public void setTipoVenta(String tipoVenta) {
        this.tipoVenta = tipoVenta;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getSubproductosesForProducto() {
        return this.subproductosesForProducto;
    }
    
    public void setSubproductosesForProducto(Set subproductosesForProducto) {
        this.subproductosesForProducto = subproductosesForProducto;
    }
    public Set getSubproductosesForSubproducto() {
        return this.subproductosesForSubproducto;
    }
    
    public void setSubproductosesForSubproducto(Set subproductosesForSubproducto) {
        this.subproductosesForSubproducto = subproductosesForSubproducto;
    }
    public Set getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set pedidoses) {
        this.pedidoses = pedidoses;
    }
    
     public Set getIngresoproductoses() {
        return this.ingresoproductoses;
    }
    
    public void setIngresoproductoses(Set ingresoproductoses) {
        this.ingresoproductoses = ingresoproductoses;
    }
    
     public Set getProductosEspecialeses() {
        return productosEspecialeses;
    }

    public void setProductosEspecialeses(Set productosEspecialeses) {
        this.productosEspecialeses = productosEspecialeses;
    }
    
    public String toString(){
        return this.nombre;
    }
    
    
    public List<models.Productos> mtdlistarProductos() {
        List<Productos> productos = new ArrayList<Productos>();
        Transaction trns = null;
        Session session = HibernateUtil.getSessionFactory().openSession();
        try {
            session.getTransaction().begin();
            productos = session.createQuery("SELECT P FROM Productos P").list();
            session.getTransaction().commit();
        } catch (RuntimeException e) {
            e.printStackTrace();
        } finally {
            session.flush();
            session.close();
        }
        return productos;
    }
    
    public List<models.Productos> mtdFiltro(String cadena) {
        List<Productos> productos = new ArrayList<Productos>();
        Transaction trns = null;
        Session session = HibernateUtil.getSessionFactory().openSession();
        try {
           session.getTransaction().begin();
            Query q = session.createQuery("FROM Productos P WHERE P.nombre LIKE :parametro");
            q.setString("parametro",'%'+cadena+'%');
            
            productos = q.list();
            session.getTransaction().commit();
        } catch (RuntimeException e) {
            e.printStackTrace();
        } finally {
            session.flush();
            session.close();
        }
        return productos;
    }
    
    
    public List<models.Productos> mtdlistarProductosTipo(String Tipo) {
        List<Productos> productos = new ArrayList<Productos>();
        Transaction trns = null;
        Session session = HibernateUtil.getSessionFactory().openSession();
        try {
            session.getTransaction().begin();
            productos = session.createQuery("SELECT P FROM Productos P WHERE P.tipoVenta = '"+Tipo+"' ").list();
            session.getTransaction().commit();
        } catch (RuntimeException e) {
            e.printStackTrace();
        } finally {
            session.flush();
            session.close();
        }
        return productos;
    }
    
     
     public List<models.Productos> mtdlistarProductosServicio() {
        List<Productos> productos = new ArrayList<Productos>();
        Transaction trns = null;
        Session session = HibernateUtil.getSessionFactory().openSession();
        try {
            session.getTransaction().begin();
            productos = session.createQuery("SELECT P FROM Productos P WHERE P.servicio = 1").list();
            session.getTransaction().commit();
        } catch (RuntimeException e) {
            e.printStackTrace();
        } finally {
            session.flush();
            session.close();
        }
        return productos;
    }
     
    public Productos mtdBuscarProducto(String codigo){
        
        Productos producto = new Productos();
        
         Session session = HibernateUtil.getSessionFactory().openSession();
        
        try {
            session.getTransaction().begin();
            Query q = session.createQuery("SELECT P FROM Productos P WHERE P.codigoBarras = '"+codigo+"'");
            
           producto = (Productos) q.uniqueResult();
           
           session.getTransaction().commit();
            
        } catch (RuntimeException e) {
            e.printStackTrace();
        } finally {
            session.flush();
            session.close();
        }
         
        
        return producto;
        
    }

   
      


}


