package models;
// Generated 18/08/2018 10:09:30 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Subproductos generated by hbm2java
 */
public class Subproductos  implements java.io.Serializable {


     private Integer idSubproducto;
     private Productos productosByProducto;
     private Productos productosBySubproducto;
     private BigDecimal cantidad;

    public Subproductos() {
    }

    public Subproductos(Productos productosByProducto, Productos productosBySubproducto, BigDecimal cantidad) {
       this.productosByProducto = productosByProducto;
       this.productosBySubproducto = productosBySubproducto;
       this.cantidad = cantidad;
    }
   
    public Integer getIdSubproducto() {
        return this.idSubproducto;
    }
    
    public void setIdSubproducto(Integer idSubproducto) {
        this.idSubproducto = idSubproducto;
    }
    public Productos getProductosByProducto() {
        return this.productosByProducto;
    }
    
    public void setProductosByProducto(Productos productosByProducto) {
        this.productosByProducto = productosByProducto;
    }
    public Productos getProductosBySubproducto() {
        return this.productosBySubproducto;
    }
    
    public void setProductosBySubproducto(Productos productosBySubproducto) {
        this.productosBySubproducto = productosBySubproducto;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }




}


