package models;
// Generated 18/08/2018 10:09:30 AM by Hibernate Tools 4.3.1


import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 * Turnos generated by hbm2java
 */
public class Turnos  implements java.io.Serializable {


     private Integer idTurno;
     private Date apertura;
     private Date cierre;
     private int valorInicial;
     private String estado;
     private Set operacioneses = new HashSet(0);
     private Set ventases = new HashSet(0);

    public Turnos() {
    }
    
    @Override
    public String toString() {
        if (this.apertura != null) {
            // Definimos el formato latino estándar (Día/Mes/Año)
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm a");
            return sdf.format(this.apertura); // 👈 Devuelve la fecha formateada como String
        }
        return "Sin fecha";
    }

	
    public Turnos(Date apertura, Date cierre, int valorInicial, String estado) {
        this.apertura = apertura;
        this.cierre = cierre;
        this.valorInicial = valorInicial;
        this.estado = estado;
    }
    public Turnos(Date apertura, Date cierre, int valorInicial, String estado, Set operacioneses, Set ventases) {
       this.apertura = apertura;
       this.cierre = cierre;
       this.valorInicial = valorInicial;
       this.estado = estado;
       this.operacioneses = operacioneses;
       this.ventases = ventases;
    }
   
    public Integer getIdTurno() {
        return this.idTurno;
    }
    
    public void setIdTurno(Integer idTurno) {
        this.idTurno = idTurno;
    }
    public Date getApertura() {
        return this.apertura;
    }
    
    public void setApertura(Date apertura) {
        this.apertura = apertura;
    }
    public Date getCierre() {
        return this.cierre;
    }
    
    public void setCierre(Date cierre) {
        this.cierre = cierre;
    }
    public int getValorInicial() {
        return this.valorInicial;
    }
    
    public void setValorInicial(int valorInicial) {
        this.valorInicial = valorInicial;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getOperacioneses() {
        return this.operacioneses;
    }
    
    public void setOperacioneses(Set operacioneses) {
        this.operacioneses = operacioneses;
    }
    public Set getVentases() {
        return this.ventases;
    }
    
    public void setVentases(Set ventases) {
        this.ventases = ventases;
    }
    
    //@All: Regresa todas las ventas o filtra solo las que tienen valor != 0
     public ArrayList<Ventas> getVentas(){
        ArrayList<Ventas> ventas = new ArrayList();
        for(Object objVen : this.getVentases()){
            Ventas venta = (Ventas) objVen;
            if(venta.getTotal()!=0)
                ventas.add(venta);
        }
        return ventas;
    }
     
    public ArrayList<Ventas> getCortesias(){
        ArrayList<Ventas> ventas = new ArrayList();
        for(Object objVen : this.getVentases()){
            Ventas venta = (Ventas) objVen;
            if(venta.getTotal()==0 && venta.getPedidoses().size()>0)
                ventas.add(venta);
        }
        return ventas;
    }
    
    
    
    public ArrayList<Ventas> getVentasTPago(String tipoPago){
        ArrayList<Ventas> ventas = new ArrayList();
         ArrayList<Ventas> ventasFacturadas = new ArrayList();
        
         Session session = HibernateUtil.getSessionFactory().openSession();

            session.getTransaction().begin();
            ventasFacturadas = (ArrayList<Ventas>) session.createQuery("FROM Ventas V WHERE turno="+getIdTurno()+" AND V.estado = 'Pagada'").list();
        
        session.getTransaction().commit();
        session.clear();
        session.flush();
        session.close();    
        
        for(Object objVen : ventasFacturadas){
            Ventas venta = (Ventas) objVen;
            if(venta.getFormaPago().equalsIgnoreCase(tipoPago))
                ventas.add(venta);
        }
        return ventas;
    }
    
     public ArrayList<Ventas> getVentasAbiertas(){
         
        ArrayList<Ventas> ventasAbiertas = new ArrayList();
        for(Object objVen : this.ventases){
            Ventas venta = (Ventas) objVen;
            if(venta.getEstado().equalsIgnoreCase("Abierta"))
                ventasAbiertas.add(venta);
        }
        return ventasAbiertas;
    }
    
    public int getTotalTPago(String tipoPago){
        int total = 0;
        for(Object objVen : this.ventases){
            Ventas venta = (Ventas) objVen;
            if(venta.getFormaPago().equalsIgnoreCase(tipoPago))
                total += venta.getTotal();
        }
        return total;
    }
    
    public int getTotalProTPago(String tipoPago){
        int total = 0;
        for(Object objVen : this.ventases){
            Ventas venta = (Ventas) objVen;
            if(venta.getFormaPago().equalsIgnoreCase(tipoPago))
                total += venta.getValor_propina();
        }
        return total;
    }

     public models.Turnos mtdListTurno() {

        models.Turnos turno = new models.Turnos();

        Session session = HibernateUtil.getSessionFactory().openSession();

        try {
            session.getTransaction().begin();
            Query q = session.createQuery("SELECT T FROM Turnos T WHERE DATE(T.apertura) = current_date() AND T.estado = 'Abierto'");

           turno = (models.Turnos) q.uniqueResult();
            session.getTransaction().commit();


        } catch (RuntimeException e) {
            e.printStackTrace();
        } finally {
            session.flush();
            session.close();
        }


        return turno;
    }

      public models.Turnos mtdTurnoOne(String fecha) {

        models.Turnos turno = new models.Turnos();

        Session session = HibernateUtil.getSessionFactory().openSession();

        try {
            session.getTransaction().begin();
            Query q = session.createQuery("SELECT T FROM Turnos T WHERE DATE(T.apertura) = '"+fecha+"'");

           turno = (models.Turnos) q.uniqueResult();

            session.getTransaction().commit();

        } catch (RuntimeException e) {
            e.printStackTrace();
        } finally {
            session.flush();
            session.close();
        }


        return turno;
    }
      
      
      public ArrayList<models.Turnos> mtdTurnosAll(String fecha) {

        
         ArrayList<Turnos> turnos = new ArrayList();
        

        Session session = HibernateUtil.getSessionFactory().openSession();

        try {
            session.getTransaction().begin();
            Query q = session.createQuery("SELECT T FROM Turnos T WHERE DATE(T.apertura) = '"+fecha+"'");
            
            
            turnos = (ArrayList<Turnos>) q.list();

            session.getTransaction().commit();

        } catch (RuntimeException e) {
            e.printStackTrace();
        } finally {
            session.flush();
            session.close();
        }


        return turnos;
    }
     
     public models.Turnos mtdTurnoAbierto() {

        models.Turnos turno = new models.Turnos();

        Session session = HibernateUtil.getSessionFactory().openSession();

        try {
            session.getTransaction().begin();
            Query q = session.createQuery("SELECT T FROM Turnos T WHERE T.estado = 'Abierto'");

           turno = (models.Turnos) q.uniqueResult();

           session.getTransaction().commit();

        } catch (RuntimeException e) {
            e.printStackTrace();
        } finally {
            session.flush();
            session.close();
        }


        return turno;
    }
     
      public /*List<models.Turnos>*/ Turnos mtdLastTurno() {

       List<Turnos> turno = new ArrayList<Turnos>();
       Turnos t = new Turnos();

        Session session = HibernateUtil.getSessionFactory().openSession();

        try {
            session.getTransaction().begin();
            Query q = session.createQuery("FROM Turnos T ORDER BY id_turno DESC");
            q.setMaxResults(1);
            
            t = (Turnos) q.uniqueResult();
             session.getTransaction().commit();
        } catch (RuntimeException e) {
            e.printStackTrace();
        } finally {
            session.flush();
            session.close();
        }


        return t;
    }

      public double getTotalVentasFormaPago(String form){
         double total = 0;

         for(Object objVenta : this.getVentasTPago(form)){

             Ventas venta = (Ventas) objVenta;
            total += venta.getTotal();
        }

         return total;
     }
      
       public double getTotalPropinasFormaPago(String form){
         double total = 0;

         for(Object objVenta : this.getVentasTPago(form)){

             Ventas venta = (Ventas) objVenta;
            total += venta.getValor_propina();
        }

         return total;
     }
      
      

     public double getTotalOperaciones(String tipo){
         double total = 0;

         for(Object objOpe : this.operacioneses){
            Operaciones operacion = (Operaciones) objOpe;
            if(operacion.getTipo().equalsIgnoreCase(tipo))
                total += operacion.getValor();

        }


         return total;
     }

     public ArrayList<Operaciones> getOperaciones(String tipo){
         ArrayList<Operaciones> ingresos = new ArrayList();
         
         for(Object objOpe : this.operacioneses){
            Operaciones operacion = (Operaciones) objOpe;
            if(operacion.getTipo().equalsIgnoreCase(tipo))
                ingresos.add(operacion);
        }
         return ingresos;
     }

     public double getTotalVentas(){
         double total = 0;

         for(Object objVenta : this.getVentases()){

             Ventas venta = (Ventas) objVenta;
            total += venta.getTotal();
        }

         return total;
     }

      public double getTotalCaja(){
         double total = 0;

         total = getValorInicial() + getTotalVentasFormaPago("Efectivo") + getTotalOperaciones("Ingreso") + getTotalPropinasFormaPago("Efectivo");

         total = total - getTotalOperaciones("Salida");

         return total;
     }
      
      public double getTotalPropinas(){
         double total = 0;

         for(Object objVenta : this.getVentases()){

             Ventas venta = (Ventas) objVenta;
            total += venta.getValor_propina();
        }

         return total;
     }
      
      public double getSumatoria(int ventas, int propinas){
         double total = 0;

         total = ventas + propinas;

         return total;
     }

      



}


