package models;
// Generated 18/08/2018 10:09:30 AM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 * Ventas generated by hbm2java
 */
public class Ventas  implements java.io.Serializable {


     private Integer idVenta;
     private Mesas mesas;
     private Turnos turnos;
     private Usuarios usuarios;
     private Date fecha;
     private String formaPago;
     private Double valor_propina  = 0.0;

    public Double getValor_propina() {
        return valor_propina;
    }

    public void setValor_propina(Double valor_propina) {
        this.valor_propina = valor_propina;
    }
     private String estado;
     private Set pedidoses = new HashSet(0);

    public Ventas() {
    }

	
    public Ventas(Mesas mesas, Turnos turnos, Usuarios usuarios, Date fecha, String formaPago, String estado) {
        this.mesas = mesas;
        this.turnos = turnos;
        this.usuarios = usuarios;
        this.fecha = fecha;
        this.formaPago = formaPago;
        this.estado = estado;
    }
    public Ventas(Mesas mesas, Turnos turnos, Usuarios usuarios, Date fecha, String formaPago, String estado, Set pedidoses) {
       this.mesas = mesas;
       this.turnos = turnos;
       this.usuarios = usuarios;
       this.fecha = fecha;
       this.formaPago = formaPago;
       this.estado = estado;
       this.pedidoses = pedidoses;
    }
    
       public Ventas(Mesas mesas, Turnos turnos, Usuarios usuarios, Date fecha, String formaPago, String estado, Set pedidoses,Double valor_propina) {
       this.mesas = mesas;
       this.turnos = turnos;
       this.usuarios = usuarios;
       this.fecha = fecha;
       this.formaPago = formaPago;
       this.estado = estado;
       this.pedidoses = pedidoses;
       this.valor_propina = valor_propina;
    }
   
    public Integer getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(Integer idVenta) {
        this.idVenta = idVenta;
    }
    public Mesas getMesas() {
        return this.mesas;
    }
    
    public void setMesas(Mesas mesas) {
        this.mesas = mesas;
    }
    public Turnos getTurnos() {
        return this.turnos;
    }
    
    public void setTurnos(Turnos turnos) {
        this.turnos = turnos;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getFormaPago() {
        return this.formaPago;
    }
    
    public void setFormaPago(String formaPago) {
        this.formaPago = formaPago;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set pedidoses) {
        this.pedidoses = pedidoses;
    }
    
    public void addPedido(Pedidos p){
        this.pedidoses.add(p);
    }

    public ArrayList<Pedidos> getProductos(){
        return new ArrayList(this.pedidoses);
    }
    
    public ArrayList<Pedidos> getPedidos(boolean print){
        ArrayList<Pedidos> pedidos = new ArrayList();
        for(Object o : this.pedidoses){
            Pedidos p = (Pedidos) o;
            if(print && p.isImpreso())
                pedidos.add(p);
            else if(!print && !p.isImpreso())
                    pedidos.add(p);
        }
        return pedidos;
    }
    
    
    public ArrayList<Pedidos> getPedidosAll(){
        ArrayList<Pedidos> pedidos = new ArrayList();
        for(Object o : this.pedidoses){
            Pedidos p = (Pedidos) o;
              pedidos.add(p);
        }
        return pedidos;
    }
    
    public void sendPrint(Session sesion){
        
       
        sesion.getTransaction().begin();
        for(Pedidos p : this.getPedidos(false)){
            p.setImpreso(true);
            sesion.update(p);
        }
        sesion.getTransaction().commit();
        
    }
    
    public int getTotal(){
        int total = 0;
        
        for(Pedidos pedido : this.getProductos()){
            total += pedido.getValor();
        }
        
        //DESCUENTOS DE LA VENTA POR CADA PEDIDO
        
        return total;
    }
    
    
    public double calcularPropina(){
        
        double propina = 0;
        
         propina = this.getTotal() * 0.10;
        
        return propina;
        
    }
    
    public double getTotalConServicio(double valorServicio, int totalVenta){
        
        double totalVentaServicio = 0;
        
        totalVentaServicio = (int) (valorServicio + totalVenta);
        
        return totalVentaServicio;
        
    }
    
    
    public int getGanancias(){
        int compras = 0;
        int ventas = 0;
        
        for(Pedidos pedido : this.getProductos()){
            ventas += pedido.getValor();
            compras += pedido.getCompra()*pedido.getCantidad();
        }
        
        return ventas-compras;
    }
    
    public List<models.Ventas> mtdListVentas(int mesero) {
        
        List<Ventas> ventas = new ArrayList<Ventas>();
        Transaction trns = null;
        Session session = HibernateUtil.getSessionFactory().openSession();
        try {
            session.getTransaction().begin();
            ventas = session.createQuery("SELECT V FROM Ventas V WHERE V.usuarios = "+mesero+" AND V.estado = 'Abierta' ").list();
            session.getTransaction().commit();
        } catch (RuntimeException e) {
            e.printStackTrace();
        } finally {
            session.close();
        }
        return ventas;
    }
    
    public boolean mtdUniqueVenta(int IdVenta) {
        
        Ventas venta = new Ventas();
        Transaction trns = null;
        Session session = HibernateUtil.getSessionFactory().openSession();
        try {
            session.getTransaction().begin();
            Query q = session.createQuery("SELECT V FROM Ventas V WHERE id_venta = "+IdVenta);
            
             venta = (models.Ventas) q.uniqueResult();
            session.getTransaction().commit();
        } catch (RuntimeException e) {
            e.printStackTrace();
        } finally {
            session.close();
        }
        
        if(venta != null){
            //System.out.println("Si Existe");
            return true;
            
        }else{
            //System.out.println("No Existe");
            return false;
        }
       
    }


}


