/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;

import models.HibernateUtil;
import models.Ingresoproductos;
import models.Pedidos;
import models.Productos;
import models.Turnos;
import models.Ventas;
import models.dataIProductos;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;

import org.hibernate.Query;
import org.hibernate.Session;

/**
 *
 * @author Javier
 */
public class demoPrint extends javax.swing.JFrame {

    /**
     * Creates new form demoPrint
     */
    public demoPrint() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Print Factura");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Session sesion = HibernateUtil.getSessionFactory().openSession();
        //sesion.getTransaction().begin();
        Calendar calendario = Calendar.getInstance();
        Query q;
        Date fecha = calendario.getTime();      
        
        ArrayList<dataIProductos> productos = new ArrayList();
        
        q = sesion.createQuery("FROM Ventas");
        ArrayList listadoVentas= (ArrayList) q.list();
        
        for(Object obj : listadoVentas){
            Ventas venta = (Ventas) obj;
            
            for( Object o : venta.getPedidoses()){
                Pedidos p = (Pedidos) o;
                BigDecimal stock = p.getProducto().getStock();
                int sto = stock.setScale(0, RoundingMode.DOWN).intValueExact();
                
                
                int i = 0; boolean ingreso = false;
                for(dataIProductos dIP : productos){
                    if(dIP.getProductoM().getIdProducto().equals(p.getProducto().getIdProducto())){
                        
                        SimpleDateFormat formato = new SimpleDateFormat("y-MM-dd");
                        String fVenta = formato.format(venta.getFecha());
                        String hoy = formato.format(fecha);
                        if(fVenta.equalsIgnoreCase(hoy)){
                            dIP.setSalida(dIP.getSalida()+p.getCantidad());
                            dIP.setBase(dIP.getBase()+p.getCantidad());
                        }
                            
                        ingreso = true;
                        break;
                    }
                    i++;
                }
                if(!ingreso){
                    productos.add(new dataIProductos(p.getProducto().getNombre() ,p.getProducto(), sto+p.getCantidad(), 0,p.getCantidad(),sto));
                }
                
                //SERVICIOS
                
                
            }
            
            
        }
        
        q = sesion.createQuery("SELECT I FROM Ingresoproductos I WHERE I.fecha= :fecha");
        q.setDate("fecha", fecha);
        ArrayList listado = (ArrayList) q.list();
        
        for(Object obj : listado){
            Ingresoproductos iProducto = (Ingresoproductos) obj;
            
            int i = 0; boolean ingreso = false;
            for(dataIProductos dIP : productos){
                if(dIP.getProductoM().getIdProducto().equals(iProducto.getProductos().getIdProducto())){
                    dIP.setIngreso(dIP.getIngreso()+iProducto.getCantidad());
                    ingreso = true;
                    break;
                }
                i++;
            }
            
            BigDecimal stock = iProducto.getProductos().getStock();
            int sto = stock.setScale(0, RoundingMode.DOWN).intValueExact();
            
            if(!ingreso){
                productos.add(new dataIProductos(iProducto.getProductos().getNombre() ,iProducto.getProductos(), sto-iProducto.getCantidad(), iProducto.getCantidad(),0,sto));
            }
            
        }
        
        
        
        
        Map<String,Object> params = new HashMap<String,Object>();
        params.put("fecha", fecha);
        
        //params.put("Pedidos", venta.getPedidoses());
        
        try{
            //se procesa el archivo jasper
            JasperPrint jasperPrint = JasperFillManager.fillReport("/reports/ingreso_productos.jasper",params,new JRBeanCollectionDataSource(productos));
            //impresion de reporte
            // TRUE: muestra la ventana de dialogo "preferencias de impresion"
            //JasperPrintManager.printReport(jasperPrint, false);   
            
            //se procesa el archivo jasper
            //jasperPrint = JasperFillManager.fillReport("src\\reports\\pedidos.jasper",params,new JREmptyDataSource());
            //impresion de reporte
            // TRUE: muestra la ventana de dialogo "preferencias de impresion"
            JasperPrintManager.printReport(jasperPrint, true);   
            
        }catch (JRException ex){
            jTextArea1.setText(jTextArea1.getText()+ex.getMessage()+"\n");
            //JOptionPane.showMessageDialog(rootPane, "Error iReport: " + ex.getMessage());
            //System.err.println( "Error iReport: " + ex.getMessage() );
        }catch(Exception ex){
            jTextArea1.setText(jTextArea1.getText()+ex.getMessage()+"\n");
        }finally{
            //venta.sendPrint(sesion);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(demoPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(demoPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(demoPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(demoPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new demoPrint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
