/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.Image;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import models.*;

/**
 *
 * @author Manuel Rodriguez
 */
public class frmAplicarDescuento extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    public itemOrder parent;
    public static itemOrder objUpdate;
    public Pedidos pedido;
    public String tipo_descuento;
    public Pedidos newPedido = new Pedidos();
    public Descuentos objDescuento;
    
    public void setTipoDescuento(String tipo){
        this.tipo_descuento = tipo;
    }
    
    public String getTipoDescuento(){
        return this.tipo_descuento;
    }
    
    public frmAplicarDescuento(itemOrder p,Pedidos ped) {
        
        this.parent = p;
        this.pedido = ped;
        initComponents();
        this.setLocationRelativeTo(this);
        ImageIcon img = new ImageIcon(getClass().getResource("/images/icon_app.png"));
        this.setIconImage(img.getImage().getScaledInstance(180,180, Image.SCALE_SMOOTH));
        
        lblProducto.setText(pedido.getProducto().getNombre());
        lblValAnterior.setText(String.valueOf(NumberFormat.getCurrencyInstance(new Locale("es", "CO"))
        .format(pedido.getProducto().getValor(/*pedido.getProducto().getIdProducto()*/))));
        
        btnAdministracion.setText("<html>Autorizado <br> Administrador</html>");
        btnPropietario.setText("<html>Autorizado <br> Propietario</html>");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnConfirmacion = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblValor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblProducto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblValAnterior = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnPropietario = new javax.swing.JButton();
        btnAdministracion = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 650));
        setMinimumSize(new java.awt.Dimension(600, 650));
        setPreferredSize(new java.awt.Dimension(600, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridLayout(4, 3, 6, 6));

        btn7.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        btn7.setText("7");
        btn7.setMinimumSize(null);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn7);

        btn8.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        btn8.setText("8");
        btn8.setMinimumSize(null);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn8);

        btn9.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        btn9.setText("9");
        btn9.setMinimumSize(null);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel1.add(btn9);

        btn4.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        btn4.setText("4");
        btn4.setMinimumSize(null);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4);

        btn5.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        btn5.setText("5");
        btn5.setMinimumSize(null);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5);

        btn6.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        btn6.setText("6");
        btn6.setMinimumSize(null);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn6);

        btn1.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        btn1.setText("1");
        btn1.setMinimumSize(null);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1);

        btn2.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        btn2.setText("2");
        btn2.setMinimumSize(null);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2);

        btn3.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        btn3.setText("3");
        btn3.setMinimumSize(null);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3);

        btn0.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        btn0.setText("0");
        btn0.setMinimumSize(null);
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel1.add(btn0);

        btnConfirmacion.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        btnConfirmacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/check.png"))); // NOI18N
        btnConfirmacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmacionActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirmacion);

        btnSalir.setFont(new java.awt.Font("Calibri", 0, 40)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/exit.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 430, 280));

        lblValor.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        lblValor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 280, 65));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logotipo_cliente_small.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 150));

        lblProducto.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        lblProducto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProducto.setText("TITULO");
        getContentPane().add(lblProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 310, 50));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Valor Anterior:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 160, 40));

        lblValAnterior.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        lblValAnterior.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValAnterior.setText("54545454");
        getContentPane().add(lblValAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 140, 40));

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel2.setText("Digite Nuevo Valor:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 160, 30));

        btnClear.setFont(new java.awt.Font("Calibri", 0, 40)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/remove.png"))); // NOI18N
        btnClear.setMaximumSize(new java.awt.Dimension(83, 50));
        btnClear.setMinimumSize(new java.awt.Dimension(83, 50));
        btnClear.setPreferredSize(new java.awt.Dimension(83, 50));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 140, 60));

        btnPropietario.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        btnPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropietarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnPropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 150, 60));

        btnAdministracion.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        btnAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministracionActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdministracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 150, 60));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel4.setText("Descuento a:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 110, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        lblValor.setText(lblValor.getText()+"7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        lblValor.setText(lblValor.getText()+"8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        lblValor.setText(lblValor.getText()+"9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        lblValor.setText(lblValor.getText()+"4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        lblValor.setText(lblValor.getText()+"5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        lblValor.setText(lblValor.getText()+"6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        lblValor.setText(lblValor.getText()+"1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        lblValor.setText(lblValor.getText()+"2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        lblValor.setText(lblValor.getText()+"3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        lblValor.setText(lblValor.getText()+"0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
       this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnConfirmacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmacionActionPerformed
       
        if(getTipoDescuento() == null){
            JOptionPane.showMessageDialog(null, "Elija un tipo de Descuento","Información",JOptionPane.INFORMATION_MESSAGE);
        
        }else{
            
            double nuevoValor = Double.valueOf(lblValor.getText());
            
            pedido.setDescuento(pedido.getProducto().getValor(/*pedido.getProducto().getIdProducto()*/)-(int) nuevoValor);
            pedido.setConceptoDesc(getTipoDescuento());
            
            parent.parentP.mtdAplicarDescuento(pedido, objUpdate,(int) nuevoValor);
            this.dispose();
            
        }
// TODO add your handling code here:
        
    }//GEN-LAST:event_btnConfirmacionActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        lblValor.setText("");   // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministracionActionPerformed
        setTipoDescuento("Autorizado por administrador"); 
        btnPropietario.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_btnAdministracionActionPerformed

    private void btnPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropietarioActionPerformed
        setTipoDescuento("Autorizado por Propietario");        // TODO add your handling code here:
        btnAdministracion.setEnabled(false);
    }//GEN-LAST:event_btnPropietarioActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAdministracion;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnConfirmacion;
    private javax.swing.JButton btnPropietario;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblValAnterior;
    private javax.swing.JLabel lblValor;
    // End of variables declaration//GEN-END:variables
}
