/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import forms.administracion.Home_Administracion;
import java.awt.Color;
import java.awt.Image;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import models.*;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import org.hibernate.*;
import org.jvnet.substance.SubstanceLookAndFeel;


/**
 *
 * @author Javier
 */
public class frmConfirmacionPin extends javax.swing.JFrame {
    
    private int count=0;
    
    private java.awt.Frame parentP;
    
    
    public models.Ventas venta;

    public Ventas getVenta() {
        return venta;
    }

    public void setVenta(Ventas venta) {
        this.venta = venta;
    }
    public Pedidos pedido;
    
    
    public String modo_acceso;
    
    public static Session sesion;
    private Turnos turno;

    public Turnos getTurno() {
        return turno;
    }

    public void setTurno(Turnos turno) {
        this.turno = turno;
    }
    
    /**
     * Creates new form login
     */
    
    public frmConfirmacionPin(java.awt.Frame parent,Turnos turno,Ventas vent){
        
        sesion = HibernateUtil.getSessionFactory().openSession();
        initComponents();
        this.parentP = parent;
        this.turno = turno;
        this.venta = vent;
        this.setLocationRelativeTo(this);
        this.setResizable(false);
        ImageIcon img = new ImageIcon(getClass().getResource("/images/icon_app.png"));
        this.setIconImage(img.getImage().getScaledInstance(180,180, Image.SCALE_SMOOTH));
        this.setTitle("POSystem - Confirmación de Usuario");
    }
    
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_7 = new javax.swing.JButton();
        jButton_8 = new javax.swing.JButton();
        jButton_9 = new javax.swing.JButton();
        jButton_4 = new javax.swing.JButton();
        jButton_5 = new javax.swing.JButton();
        jButton_6 = new javax.swing.JButton();
        jButton_1 = new javax.swing.JButton();
        jButton_2 = new javax.swing.JButton();
        jButton_3 = new javax.swing.JButton();
        jButton_0 = new javax.swing.JButton();
        jBDelete = new javax.swing.JButton();
        jBExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPassField = new javax.swing.JPasswordField();
        jLblInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(500, 650));
        setMinimumSize(new java.awt.Dimension(500, 650));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridLayout(4, 3, 6, 6));

        jButton_7.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jButton_7.setText("7");
        jButton_7.setMinimumSize(null);
        jButton_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_7);

        jButton_8.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jButton_8.setText("8");
        jButton_8.setMinimumSize(null);
        jButton_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_8);

        jButton_9.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jButton_9.setText("9");
        jButton_9.setMinimumSize(null);
        jButton_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_9);

        jButton_4.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jButton_4.setText("4");
        jButton_4.setMinimumSize(null);
        jButton_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_4);

        jButton_5.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jButton_5.setText("5");
        jButton_5.setMinimumSize(null);
        jButton_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_5);

        jButton_6.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jButton_6.setText("6");
        jButton_6.setMinimumSize(null);
        jButton_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_6);

        jButton_1.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jButton_1.setText("1");
        jButton_1.setMinimumSize(null);
        jButton_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_1);

        jButton_2.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jButton_2.setText("2");
        jButton_2.setMinimumSize(null);
        jButton_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_2);

        jButton_3.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jButton_3.setText("3");
        jButton_3.setMinimumSize(null);
        jButton_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_3);

        jButton_0.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jButton_0.setText("0");
        jButton_0.setMinimumSize(null);
        jButton_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_0ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_0);

        jBDelete.setFont(new java.awt.Font("Calibri", 0, 40)); // NOI18N
        jBDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/remove.png"))); // NOI18N
        jBDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jBDelete);

        jBExit.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jBExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/exit.png"))); // NOI18N
        jBExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitActionPerformed(evt);
            }
        });
        jPanel1.add(jBExit);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 298, 310, 280));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logotipo_cliente_small.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jPassField.setColumns(5);
        jPassField.setFont(new java.awt.Font("Archive", 0, 48)); // NOI18N
        jPassField.setToolTipText("");
        jPassField.setEnabled(false);
        jPassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassFieldActionPerformed(evt);
            }
        });
        jPassField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPassFieldKeyPressed(evt);
            }
        });
        getContentPane().add(jPassField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 255, 70));

        jLblInfo.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLblInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblInfo.setText("Ingrese su PIN");
        jLblInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 198, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_9ActionPerformed
        // TODO add your handling code here:
        setPassword(9);
    }//GEN-LAST:event_jButton_9ActionPerformed

    private void jButton_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_4ActionPerformed
        // TODO add your handling code here:
        setPassword(4);
    }//GEN-LAST:event_jButton_4ActionPerformed

    private void jButton_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_1ActionPerformed
        // TODO add your handling code here:
        setPassword(1);
    }//GEN-LAST:event_jButton_1ActionPerformed

    private void jPassFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPassFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassFieldKeyPressed

    private void jBExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitActionPerformed
        // TODO add your handling code here:
       this.dispose();
    }//GEN-LAST:event_jBExitActionPerformed

    private void jButton_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_0ActionPerformed
        // TODO add your handling code here:
        setPassword(0);
    }//GEN-LAST:event_jButton_0ActionPerformed

    private void jButton_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_2ActionPerformed
        // TODO add your handling code here:
        setPassword(2);
    }//GEN-LAST:event_jButton_2ActionPerformed

    private void jButton_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_3ActionPerformed
        // TODO add your handling code here:
        setPassword(3);
    }//GEN-LAST:event_jButton_3ActionPerformed

    private void jButton_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_5ActionPerformed
        // TODO add your handling code here:
        setPassword(5);
    }//GEN-LAST:event_jButton_5ActionPerformed

    private void jButton_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_6ActionPerformed
        // TODO add your handling code here:
        setPassword(6);
    }//GEN-LAST:event_jButton_6ActionPerformed

    private void jButton_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_7ActionPerformed
        // TODO add your handling code here:
        setPassword(7);
    }//GEN-LAST:event_jButton_7ActionPerformed

    private void jButton_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_8ActionPerformed
        // TODO add your handling code here:
        setPassword(8);
    }//GEN-LAST:event_jButton_8ActionPerformed

    private void jBDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeleteActionPerformed
        // TODO add your handling code here:
        setPassword(-1);
    }//GEN-LAST:event_jBDeleteActionPerformed

    private void jPassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassFieldActionPerformed

    /**
     * @param args the command line arguments
     */
  
    private void setPassword(int number){
        String pass = new String(jPassField.getPassword());
        
        if(number<0 && pass.length()>0){
            pass = pass.substring(0, pass.length()-1);
        }else if(number>=0)
            pass = pass+number;
        
        jPassField.setText(pass);
        
        
        if(pass.length()>3){ //Al tercer digito ingresado
            //VERIFICAMOS CLAVE DE ACCESO
            Usuarios user = Usuarios.validPIN(pass,sesion);
        
            if(user != null){
                if(user.getEstado().equalsIgnoreCase("Activo")){
                    switch (user.getPerfil()){
                        case "Mesero":
                            
                           
                            try {
                                     Transaction trns = null;
                                     Session session = HibernateUtil.getSessionFactory().openSession();
                                     
                                    /*if(getVenta().getUsuarios().getIdUsuario() != user.getIdUsuario()){
                                        
                                        getVenta().setUsuarios(user);
                                        
                                        trns = session.beginTransaction();
                                        session.update(getVenta());
                                        session.getTransaction().commit();
                                    }*/
                                 
                                 
                                 
                                    
                                 Map<String,Object> params = new HashMap<String,Object>();
                                 Ventas v = (Ventas) session.get(models.Ventas.class, getVenta().getIdVenta());
                                 params.put("Venta",v );
                                 //params.put("Pedido", this.pedido);
                                        

                                    try{

                                    JasperPrint jasperPrintPedido = JasperFillManager.fillReport("src\\reports\\pedidos.jasper",params,new JREmptyDataSource());
                                    JasperPrintManager.printReport(jasperPrintPedido, false);   

                                    }catch (JRException ex){
                                        JOptionPane.showMessageDialog(parentP, "Error iReport: " + ex.getMessage());
                                        System.err.println( "Error iReport: " + ex.getMessage() );
                                    }finally{
                                      v.sendPrint(session);
                                    }

                                //session.evict(getVenta()); 
                                session.close();
                                
                                this.dispose();
                               
                                this.parentP.dispose();
                                
                               
                                
                                
                                frmMesas formMesas = new frmMesas(new Ventas(),turno,user,"Mesero"); 
                                formMesas.setVisible(true);
                                
                            } catch (RuntimeException e) {
                                e.printStackTrace();
                            } 
                           
                           
                             break;

                        case "Gerente":
                            break;

                        case "Administrador":
                            
                               try {
                                     Transaction trns = null;
                                     Session session = HibernateUtil.getSessionFactory().openSession();
                                     
                                    /*if(getVenta().getUsuarios() != user){
                                        
                                        getVenta().setUsuarios(user);
                                        
                                        trns = session.beginTransaction();
                                        session.update(getVenta());
                                        session.getTransaction().commit();
                                    }*/
                                 
                                 
                                 
                                    
                                 Map<String,Object> params = new HashMap<String,Object>();
                                  Ventas v = (Ventas) session.get(models.Ventas.class, getVenta().getIdVenta());
                                 params.put("Venta", v);
                                 //params.put("Pedido", this.pedido);
                                        

                                    try{

                                    JasperPrint jasperPrintPedido = JasperFillManager.fillReport("src\\reports\\pedidos.jasper",params,new JREmptyDataSource());
                                    JasperPrintManager.printReport(jasperPrintPedido, false);   

                                    }catch (JRException ex){
                                        JOptionPane.showMessageDialog(parentP, "Error iReport: " + ex.getMessage());
                                        System.err.println( "Error iReport: " + ex.getMessage() );
                                    }finally{
                                    v.sendPrint(session);
                                    }

                                 
                                session.close();
                                
                                this.dispose();
                               
                                this.parentP.dispose();
                                
                               
                                
                                
                                frmMesas formMesas = new frmMesas(new Ventas(),turno,user,"Administrador"); 
                                formMesas.setVisible(true);
                                
                            } catch (RuntimeException e) {
                                e.printStackTrace();
                            } 
                            
                            
                            break;
                    }

                    this.dispose();
                }else{
                    jLblInfo.setForeground(Color.red);
                    jLblInfo.setText("Usuario Inactivo");
                    jPassField.setText("");
                }
            }else if(pass.length()==5){
                jLblInfo.setText("Código Incorrecto");
                jLblInfo.setForeground(Color.red);
                jPassField.setText("");
            }else{
                jLblInfo.setText("Ingrese su PIN");
                jLblInfo.setForeground(Color.white);
            }
        }
            
            
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDelete;
    private javax.swing.JButton jBExit;
    private javax.swing.JButton jButton_0;
    private javax.swing.JButton jButton_1;
    private javax.swing.JButton jButton_2;
    private javax.swing.JButton jButton_3;
    private javax.swing.JButton jButton_4;
    private javax.swing.JButton jButton_5;
    private javax.swing.JButton jButton_6;
    private javax.swing.JButton jButton_7;
    private javax.swing.JButton jButton_8;
    private javax.swing.JButton jButton_9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblInfo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassField;
    // End of variables declaration//GEN-END:variables
}
