/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import models.*;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author Manuel Rodriguez
 */
public class frmServicios extends javax.swing.JFrame {

    /**
     * Creates new form frmServicios
     */
    
    public mainMesero parent;
    private List<Productos> ListadoProductos;
    public Pedidos pedido;
    public Servicios servicio;
    
    Productos objProducto = new Productos();
    
    public frmServicios(mainMesero p,Pedidos pedido) {
        
        initComponents();
        this.parent =p;
        this.pedido = pedido;
        
        this.setLocationRelativeTo(this);
        ImageIcon img = new ImageIcon(getClass().getResource("/images/icon_app.png"));
        this.setIconImage(img.getImage().getScaledInstance(180,180, Image.SCALE_SMOOTH));
        this.setTitle("POSystem - Powered by &Source Ltda");
        
        mtdAgregarServicios();
    }
    
   
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollServicios = new javax.swing.JScrollPane();
        PanelServicios = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(658, 600));
        setMinimumSize(new java.awt.Dimension(658, 600));
        setPreferredSize(new java.awt.Dimension(658, 600));
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ScrollServicios.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ScrollServicios.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        PanelServicios.setLayout(new java.awt.GridLayout(0, 1));
        ScrollServicios.setViewportView(PanelServicios);

        getContentPane().add(ScrollServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 575, 360));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logotipo_cliente_small.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        jLabel2.setText("Elegir Adicional");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 260, 60));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/back.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 90, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
 this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    public void mtdAgregarServicios(){
        
        ListadoProductos = new ArrayList<>();
        ListadoProductos = objProducto.mtdlistarProductosServicio();
        
       frmServicios form = this;
        
        for (Productos dataProducto:ListadoProductos) {
            
            JButton btnServ = new JButton(dataProducto.getNombre());
            
             btnServ.addActionListener(new ActionListener() { 
                public void actionPerformed(ActionEvent e) {
                    
                    
                    parent.mtdGuardarPedido(pedido, dataProducto,"Con Servicio");
                    form.dispose();
                    
                    
                  
                }});
               
            
            
            PanelServicios.add(btnServ);
            PanelServicios.revalidate();
            PanelServicios.repaint();
        }
        
        
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelServicios;
    private javax.swing.JScrollPane ScrollServicios;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
