/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import models.Mesas;
import models.Usuarios;
import models.Ventas;

/**
 *
 * @author Manuel Rodriguez
 */
public class frmVentasAbiertas extends javax.swing.JFrame {
    
    
    private java.awt.Frame parentP;
    public Usuarios mesero;
    public List<Ventas> ListadoVentas;
    
    Ventas objVenta = new Ventas();
    
    /**
     * Creates new form frmVentasAbiertas
     */
    public frmVentasAbiertas(java.awt.Frame parent,Usuarios mes) {
        
        initComponents();
        this.mesero = mes;
        this.parentP = parent;
        this.setLocationRelativeTo(this);
        this.setResizable(false);
        ImageIcon img = new ImageIcon(getClass().getResource("/images/icon_app.png"));
        this.setIconImage(img.getImage().getScaledInstance(180,180, Image.SCALE_SMOOTH));
        this.setTitle("POSystem - Ordenes Abiertas");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        btnSalir.setForeground(new Color(218, 0, 128));
        lblMesero.setText(this.mesero.getNombres()+" "+this.mesero.getApellidos());
        
        mtdVentasAbiertas();
    }
    
    
    public void mtdVentasAbiertas(){
        
        ListadoVentas = new ArrayList<>();
        ListadoVentas = objVenta.mtdListVentas(this.mesero.getIdUsuario());
        
        for (Ventas dataVenta: ListadoVentas) {
            
            JButton btnVenta = new JButton("<html>"+dataVenta.getMesas().getTipo()+" "+dataVenta.getMesas().getNumero()+ "<br>"+dataVenta.getFormaPago()+"<br>"+dataVenta.getMesas().getEstado()+" </html>");
            
            btnVenta.setMaximumSize(new Dimension(80,80));
            
            PanelVentasAbiertas.add(btnVenta);
            PanelVentasAbiertas.revalidate();
            PanelVentasAbiertas.repaint();
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PanelVentasAbiertas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblMesero = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelVentasAbiertas.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(PanelVentasAbiertas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 690, 470));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logotipo_cliente_small.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 240, -1));

        lblMesero.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        lblMesero.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(lblMesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 220, 40));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        jLabel3.setText("Mesero:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 130, 50));

        btnSalir.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 580, 110, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        this.parentP.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelVentasAbiertas;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMesero;
    // End of variables declaration//GEN-END:variables
}
