/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import org.jvnet.substance.SubstanceLookAndFeel;


/**
 *
 * @author Javier
 */
public class inputDigit extends javax.swing.JDialog {
    private int count=0;
    /**
     * Creates new form login
     */
    public inputDigit(java.awt.Frame parent, boolean modal) {
        super(parent,modal);
        initComponents();
        this.setLocationRelativeTo(this);
        this.setResizable(false);
        ImageIcon img = new ImageIcon(getClass().getResource("/images/icon_app.png"));
        this.setIconImage(img.getImage().getScaledInstance(180,180, Image.SCALE_SMOOTH)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_7 = new javax.swing.JButton();
        jButton_8 = new javax.swing.JButton();
        jButton_9 = new javax.swing.JButton();
        jButton_4 = new javax.swing.JButton();
        jButton_5 = new javax.swing.JButton();
        jButton_6 = new javax.swing.JButton();
        jButton_1 = new javax.swing.JButton();
        jButton_2 = new javax.swing.JButton();
        jButton_3 = new javax.swing.JButton();
        jButton_0 = new javax.swing.JButton();
        jBDelete = new javax.swing.JButton();
        jBExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLblInfo = new javax.swing.JLabel();
        jTCant = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(570, 560));
        setMinimumSize(new java.awt.Dimension(570, 560));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(570, 560));

        jPanel1.setLayout(new java.awt.GridLayout(4, 3, 6, 6));

        jButton_7.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jButton_7.setText("7");
        jButton_7.setMinimumSize(null);
        jButton_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_7);

        jButton_8.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jButton_8.setText("8");
        jButton_8.setMinimumSize(null);
        jButton_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_8);

        jButton_9.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jButton_9.setText("9");
        jButton_9.setMinimumSize(null);
        jButton_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_9);

        jButton_4.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jButton_4.setText("4");
        jButton_4.setMinimumSize(null);
        jButton_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_4);

        jButton_5.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jButton_5.setText("5");
        jButton_5.setMinimumSize(null);
        jButton_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_5);

        jButton_6.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jButton_6.setText("6");
        jButton_6.setMinimumSize(null);
        jButton_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_6);

        jButton_1.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jButton_1.setText("1");
        jButton_1.setMinimumSize(null);
        jButton_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_1);

        jButton_2.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jButton_2.setText("2");
        jButton_2.setMinimumSize(null);
        jButton_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_2);

        jButton_3.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jButton_3.setText("3");
        jButton_3.setMinimumSize(null);
        jButton_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_3);

        jButton_0.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jButton_0.setText("0");
        jButton_0.setMinimumSize(null);
        jButton_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_0ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_0);

        jBDelete.setFont(new java.awt.Font("Calibri", 0, 40)); // NOI18N
        jBDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/remove.png"))); // NOI18N
        jBDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jBDelete);

        jBExit.setFont(new java.awt.Font("Leelawadee", 0, 40)); // NOI18N
        jBExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/exit.png"))); // NOI18N
        jBExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitActionPerformed(evt);
            }
        });
        jPanel1.add(jBExit);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logotipo_cliente_small.png"))); // NOI18N

        jLblInfo.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLblInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblInfo.setText("Ingrese Cantidad");
        jLblInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTCant.setFont(new java.awt.Font("Leelawadee UI", 0, 48)); // NOI18N
        jTCant.setEnabled(false);
        jTCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTCant, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jTCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLblInfo)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_9ActionPerformed
        // TODO add your handling code here:
        setPassword(9);
    }//GEN-LAST:event_jButton_9ActionPerformed

    private void jButton_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_4ActionPerformed
        // TODO add your handling code here:
        setPassword(4);
    }//GEN-LAST:event_jButton_4ActionPerformed

    private void jButton_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_1ActionPerformed
        // TODO add your handling code here:
        setPassword(1);
    }//GEN-LAST:event_jButton_1ActionPerformed

    private void jBExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBExitActionPerformed

    private void jButton_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_0ActionPerformed
        // TODO add your handling code here:
        setPassword(0);
    }//GEN-LAST:event_jButton_0ActionPerformed

    private void jButton_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_2ActionPerformed
        // TODO add your handling code here:
        setPassword(2);
    }//GEN-LAST:event_jButton_2ActionPerformed

    private void jButton_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_3ActionPerformed
        // TODO add your handling code here:
        setPassword(3);
    }//GEN-LAST:event_jButton_3ActionPerformed

    private void jButton_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_5ActionPerformed
        // TODO add your handling code here:
        setPassword(5);
    }//GEN-LAST:event_jButton_5ActionPerformed

    private void jButton_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_6ActionPerformed
        // TODO add your handling code here:
        setPassword(6);
    }//GEN-LAST:event_jButton_6ActionPerformed

    private void jButton_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_7ActionPerformed
        // TODO add your handling code here:
        setPassword(7);
    }//GEN-LAST:event_jButton_7ActionPerformed

    private void jButton_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_8ActionPerformed
        // TODO add your handling code here:
        setPassword(8);
    }//GEN-LAST:event_jButton_8ActionPerformed

    private void jBDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeleteActionPerformed
        // TODO add your handling code here:
        setPassword(-1);
    }//GEN-LAST:event_jBDeleteActionPerformed

    private void jTCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCantActionPerformed

    
    private void setPassword(int number){
        String pass = jTCant.getText();
        
        if(number<0 && pass.length()>0){
            pass = pass.substring(0, pass.length()-1);
        }else if(number>=0)
            pass = pass+number;
        
        jTCant.setText(pass);     
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDelete;
    private javax.swing.JButton jBExit;
    private javax.swing.JButton jButton_0;
    private javax.swing.JButton jButton_1;
    private javax.swing.JButton jButton_2;
    private javax.swing.JButton jButton_3;
    private javax.swing.JButton jButton_4;
    private javax.swing.JButton jButton_5;
    private javax.swing.JButton jButton_6;
    private javax.swing.JButton jButton_7;
    private javax.swing.JButton jButton_8;
    private javax.swing.JButton jButton_9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblInfo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTCant;
    // End of variables declaration//GEN-END:variables
}
