/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import antlr.StringUtils;
import java.awt.Color;
import java.awt.Image;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import models.*;
import org.jvnet.substance.SubstanceLookAndFeel;

/**
 *
 * @author Javier
 */
public class itemOrder extends javax.swing.JPanel {

    /**
     * Creates new form itemOrder
     */
    
    public mainMesero parentP;
    public itemOrder parentDescuento;
    public static Productos producto;
    public static double totalVenta;
    public  Pedidos objetoPedido;
    public String modo_acceso = "normal";
    
    public void setModo_Acceso(String mod){
        this.modo_acceso = mod;
    }
    
    public String getModo_Acceso(){
        return this.modo_acceso;
    }
    
    
    public itemOrder(mainMesero parent) {
        
        parentP = parent;
        
        this.parentDescuento = this;
        initComponents();
        //JFrame.setDefaultLookAndFeelDecorated(true);
        //SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.BusinessSkin");
        this.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(97, 97, 97)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblValorUnitario = new javax.swing.JLabel();
        lblNombreProducto = new javax.swing.JLabel();
        lblTotalPedido = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(450, 80));
        setMinimumSize(new java.awt.Dimension(450, 80));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(450, 80));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblValorUnitario.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        lblValorUnitario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblValorUnitario.setText("25000");
        add(lblValorUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 30));

        lblNombreProducto.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        lblNombreProducto.setText("Nombre");
        add(lblNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 30));

        lblTotalPedido.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        lblTotalPedido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalPedido.setText("$2.500");
        add(lblTotalPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 140, 30));

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/pencil.png"))); // NOI18N
        btnEdit.setMaximumSize(new java.awt.Dimension(30, 30));
        btnEdit.setMinimumSize(new java.awt.Dimension(30, 30));
        btnEdit.setPreferredSize(new java.awt.Dimension(30, 30));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 60, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        
       
           parentP.setEnabled(false);
        
           frmEditarPedido.objUpdate = this;
           frmEditarPedido.UpdatePedido = this.objetoPedido;
           frmEditarPedido frmNew =  new frmEditarPedido(this.parentP);
           frmNew.setVisible(true); 
           
            frmNew.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
            // Cuando frmCantidad se destruya o se cierre, mainMesero vuelve a la vida
            parentP.setEnabled(true); 
            parentP.toFront(); // La trae al frente automáticamente
            }});
           
        
        
        
        
        //JOptionPane.showMessageDialog(null, "el: "+this.producto.getNombre());        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed
    
    public void mtdUbicarInformacion(Pedidos objPedido){
        
        
        lblNombreProducto.setText(producto.getNombre()+" x("+objPedido.getCantidad()+")");
        lblValorUnitario.setText(String.valueOf(NumberFormat.getCurrencyInstance(new Locale("es", "CO"))
        .format(objPedido.getProducto().getValor(/*objPedido.getProducto().getIdProducto()*/))));
        lblTotalPedido.setText(String.valueOf(NumberFormat.getCurrencyInstance(new Locale("es", "CO"))
        .format(objPedido.getValor())));
        
        totalVenta += objPedido.getValor();
        
       parentP.setTotalVenta(totalVenta);
       
      
        
    }
    
     public void mtdUbicarInformacionConDescuento(Pedidos objPedido,int valorNew){
        
        
        lblNombreProducto.setText(producto.getNombre()+" x("+objPedido.getCantidad()+")");
        lblValorUnitario.setText(String.valueOf(NumberFormat.getCurrencyInstance(new Locale("es", "CO"))
        .format(valorNew)));
        lblTotalPedido.setText(String.valueOf(NumberFormat.getCurrencyInstance(new Locale("es", "CO"))
        .format(objPedido.getValor())));
        
        totalVenta += objPedido.getValor();
        
       parentP.setTotalVenta(totalVenta);
        
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblTotalPedido;
    private javax.swing.JLabel lblValorUnitario;
    // End of variables declaration//GEN-END:variables
}
