/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;



import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import javax.swing.*;
import models.*;
import models.Ventas;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.jvnet.substance.SubstanceLookAndFeel;

/**
 *
 * @author Javier
 */
public class mainMesero extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    
    private List<Categorias> ListadoCategorias;
    private List<Productos> ListadoProductos;
    public List<Pedidos> arrayPedido = new ArrayList<>();
    Categorias objCategoria = new Categorias();
    private Ventas Venta;
    private Turnos turno;
    public static models.Usuarios usuario;

    public Turnos getTurno() {
        return turno;
    }

    public void setTurno(Turnos turno) {
        this.turno = turno;
    }
    
    public Ventas getVenta() {
        return Venta;
    }

    public void setVenta(Ventas Venta) {
        this.Venta = Venta;
    }
    
    public static Pedidos pedido = new Pedidos();
    public Servicios servicio;
    
    public Mesas mesa;
    public double totalVenta = 0;
    
    public void setMesa(Mesas mes) {
        this.mesa = mes;
    }
    public Mesas getMesa() {
        return this.mesa;
    }
    
    public void setTotalVenta(double tVenta) {
        this.totalVenta = tVenta;
    }
    public double getTotalVenta() {
        return this.totalVenta;
    }
    
    public frmMesas Parent;
    private models.DisenoFormularios desing;
    
    public mainMesero(frmMesas p,Turnos turn,Ventas venta) {
        
        this.Parent = p;
        this.turno = turn;
        this.Venta = venta;
        
        
        initComponents();

        desing.mtdDisenoPantalla(this);
        
        ImageIcon img = new ImageIcon(getClass().getResource("/images/icon_app.png"));
        this.setIconImage(img.getImage().getScaledInstance(180,180, Image.SCALE_SMOOTH));
      
        
        arrayPedido = venta.getPedidosAll();
        
        if(arrayPedido.size() > 0){
            
            txtPedidos.setText("ESTA VENTA TIENE "+arrayPedido.size()+ " PEDIDOS");
            
            for (Pedidos dataPedido:arrayPedido) {
                itemOrder io = new itemOrder(this);


                    itemOrder.producto = dataPedido.getProducto();
                    itemOrder.totalVenta = getTotalVenta();

                    io.mtdUbicarInformacion(dataPedido);
                    io.objetoPedido = dataPedido;
                    
                    PanelListadoPedidos.add(io);
                    PanelListadoPedidos.revalidate();
                    PanelListadoPedidos.repaint();
            }
        }else{
            txtPedidos.setText("ESTA VENTA NO TIENE PEDIDOS");
        }
        
        //jBSave.setVisible(false);
        jPCategories.removeAll();
        mtdCat();
        jPCategories.setVisible(true);
        
       
        
        //jBSave.setBackground(new Color(0, 156, 222));
        //jBSave.setForeground(new Color(0, 156, 222));
        
        //btnImprimir.setBackground(new Color(218, 0, 128));
        //btnImprimir.setForeground(new Color(218, 0, 128));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jpnSuperior = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblMesa = new javax.swing.JLabel();
        jpnMain = new javax.swing.JPanel();
        ScrollCategorias = new javax.swing.JScrollPane();
        jPCategories = new javax.swing.JPanel();
        jPOrder = new javax.swing.JPanel();
        jBClearOrder = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        ScrollPedidos = new javax.swing.JScrollPane();
        PanelListadoPedidos = new javax.swing.JPanel();
        lblTotalVenta = new javax.swing.JLabel();
        txtPedidos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(82, 81, 82));
        setMaximumSize(new java.awt.Dimension(1024, 700));
        setMinimumSize(new java.awt.Dimension(1024, 700));
        setPreferredSize(new java.awt.Dimension(1024, 700));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 7, 0};
        layout.rowHeights = new int[] {0, 12, 0};
        getContentPane().setLayout(layout);

        jpnSuperior.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        jpnSuperior.setLayout(new java.awt.GridLayout(1, 3, 50, 0));

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/back.png"))); // NOI18N
        lblTitle.setText(" CATEGORIAS");
        lblTitle.setToolTipText("");
        lblTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTitleMouseClicked(evt);
            }
        });
        jpnSuperior.add(lblTitle);

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpnSuperior.add(lblLogo);

        lblMesa.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        lblMesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMesa.setText("ITEMS");
        jpnSuperior.add(lblMesa);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 754;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(54, 10, 0, 0);
        getContentPane().add(jpnSuperior, gridBagConstraints);

        jpnMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        jpnMain.setLayout(new java.awt.GridLayout(1, 2));

        ScrollCategorias.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        ScrollCategorias.setToolTipText("");
        ScrollCategorias.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPCategories.setAutoscrolls(true);
        jPCategories.setMaximumSize(new java.awt.Dimension(500, 400));
        jPCategories.setMinimumSize(new java.awt.Dimension(500, 400));
        jPCategories.setName(""); // NOI18N
        jPCategories.setPreferredSize(new java.awt.Dimension(500, 400));
        jPCategories.setLayout(new java.awt.GridLayout(0, 2, 2, 2));
        ScrollCategorias.setViewportView(jPCategories);

        jpnMain.add(ScrollCategorias);

        jPOrder.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPOrder.setMaximumSize(new java.awt.Dimension(450, 300));
        jPOrder.setMinimumSize(new java.awt.Dimension(450, 300));
        jPOrder.setPreferredSize(new java.awt.Dimension(450, 300));
        jPOrder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBClearOrder.setBackground(new java.awt.Color(82, 81, 82));
        jBClearOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/trash.png"))); // NOI18N
        jBClearOrder.setMaximumSize(new java.awt.Dimension(80, 80));
        jBClearOrder.setMinimumSize(new java.awt.Dimension(80, 80));
        jBClearOrder.setPreferredSize(new java.awt.Dimension(80, 80));
        jBClearOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBClearOrderActionPerformed(evt);
            }
        });
        jPOrder.add(jBClearOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 78, -1));

        btnImprimir.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        btnImprimir.setText("CONFIRMAR PEDIDO");
        btnImprimir.setFocusPainted(false);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        jPOrder.add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 430, 90));

        ScrollPedidos.setMaximumSize(new java.awt.Dimension(465, 445));
        ScrollPedidos.setMinimumSize(new java.awt.Dimension(465, 445));
        ScrollPedidos.setPreferredSize(new java.awt.Dimension(465, 445));

        PanelListadoPedidos.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        PanelListadoPedidos.setMaximumSize(new java.awt.Dimension(455, 435));
        PanelListadoPedidos.setMinimumSize(new java.awt.Dimension(455, 435));
        PanelListadoPedidos.setPreferredSize(new java.awt.Dimension(455, 435));
        PanelListadoPedidos.setLayout(new java.awt.GridLayout(0, 1));
        ScrollPedidos.setViewportView(PanelListadoPedidos);

        jPOrder.add(ScrollPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 460, 360));
        jPOrder.add(lblTotalVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 230, 50));

        txtPedidos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPedidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPOrder.add(txtPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 300, 70));

        jpnMain.add(jPOrder);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 880;
        gridBagConstraints.ipady = 310;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 30, 0);
        getContentPane().add(jpnMain, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        
            //this.dispose();
            
            if(this.Venta.getPedidosAll().size() > 0){
            
            
            btnImprimir.setVisible(false);
            pedido.setVenta(getVenta());   
            
            this.dispose();
            frmMesas formMesas = new frmMesas(new Ventas(),turno,usuario,usuario.getPerfil()); 
            formMesas.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null,"No cuenta con pedidos, agregue o elimine la venta");
            }
                               
            //SE SUPRIME LA GENERACION DEL REPORTE DE COMANDA 
            /*frmConfirmacionPin formConfirmacion = new frmConfirmacionPin(this,turno,Venta);
     
            formConfirmacion.setVisible(true);
            formConfirmacion.modo_acceso = "venta";  
            formConfirmacion.setVenta(getVenta());
            
            try {
                                     Transaction trns = null;
                                     Session session = HibernateUtil.getSessionFactory().openSession();
                                     
                                    /*if(getVenta().getUsuarios().getIdUsuario() != user.getIdUsuario()){
                                        
                                        getVenta().setUsuarios(user);
                                        
                                        trns = session.beginTransaction();
                                        session.update(getVenta());
                                        session.getTransaction().commit();
                                    }
                                 
                                 
                                 
                                    
                                 Map<String,Object> params = new HashMap<String,Object>();
                                 Ventas v = (Ventas) session.get(models.Ventas.class, getVenta().getIdVenta());
                                 params.put("Venta",v );
                                 //params.put("Pedido", this.pedido);
                                        

                                    try{

                                    JasperPrint jasperPrintPedido = JasperFillManager.fillReport("src\\reports\\pedidos.jasper",params,new JREmptyDataSource());
                                    JasperPrintManager.printReport(jasperPrintPedido, false);   
                                    
                                    }catch (JRException ex){
                                        JOptionPane.showMessageDialog(this, "Error iReport: " + ex.getMessage());
                                        System.err.println( "Error iReport: " + ex.getMessage() );
                                    }finally{
                                      v.sendPrint(session);
                                    }

                                //session.evict(getVenta()); 
                                session.flush();
                                session.close();
                                
                                
                                
                                this.dispose();
                                frmMesas formMesas = new frmMesas(new Ventas(),turno,usuario,usuario.getPerfil()); 
                                formMesas.setVisible(true);
                               
                              
                                
                            } catch (RuntimeException e) {
                                e.printStackTrace();
                            }*/
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void jBClearOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBClearOrderActionPerformed

        
        int resp=JOptionPane.showConfirmDialog(null,"Si Eliminas esta venta cancelaras todos los pedidos incluidos en ella \n ¿Estas Seguro que deseas eliminar esta venta?");
        if (JOptionPane.OK_OPTION == resp){
                    Transaction trns = null;
                    Session session = HibernateUtil.getSessionFactory().openSession();
                    try {
                        
                         
                        trns = session.beginTransaction();
                        for (Object Ped: getVenta().getPedidoses()) {
                            
                            Pedidos dataPedido = (Pedidos) Ped;
                            
                            
                            if(dataPedido.getProducto().getSubproductosesForProducto().size() > 0){
                            
                            
                            
                                
                                for (Object objSubProducto : dataPedido.getProducto().getSubproductosesForProducto() ) {

                                        models.Subproductos dataSubProducto = (models.Subproductos) objSubProducto;
                                        
                                        
                                        
                                        BigDecimal stockSub = dataSubProducto.getProductosBySubproducto().getStock();
                                        int stoSub = stockSub.setScale(0, RoundingMode.DOWN).intValueExact();

                                        BigDecimal cantADescontar = dataSubProducto.getCantidad();
                                        int cntDes = cantADescontar.setScale(0, RoundingMode.DOWN).intValueExact();

                                        int cantidadTotalDescuento = cntDes * dataPedido.getCantidad();

                                        dataSubProducto.getProductosBySubproducto().setStock(BigDecimal.valueOf(stoSub + cantidadTotalDescuento));


                                        session.update(dataSubProducto.getProductosBySubproducto());

                                }
                                
                        
                                //SUMAR LAS UNIDADES SOLICITADAS AL STOCK DEL PRODUCTO EN PROMOCIÓN

                                BigDecimal stockPromo = dataPedido.getProducto().getStock();
                                int stoPromo = stockPromo.setScale(0, RoundingMode.DOWN).intValueExact();

                                dataPedido.getProducto().setStock(BigDecimal.valueOf(stoPromo - dataPedido.getCantidad()));

                               
                        

                        }else{
                            
                            
                            BigDecimal stock = dataPedido.getProducto().getStock();
                            int sto = stock.setScale(0, RoundingMode.DOWN).intValueExact();
                            
                            dataPedido.getProducto().setStock(BigDecimal.valueOf(sto + dataPedido.getCantidad()));
                            
                        }
                            session.update(dataPedido.getProducto());
                            
                            
                        }
                        
                        
                        session.delete(getVenta());
                        trns.commit();
                        PanelListadoPedidos.removeAll();
                       session.clear();
                       session.flush();
                       session.close();
                        
                        

                   }catch (RuntimeException ex) {
                        System.out.println(ex.getMessage());
                    }finally {
                        this.dispose();
                        
                            String cadena = "mesero";
                            if(Venta.getUsuarios().getPerfil().equalsIgnoreCase("administrador"))
                             cadena = "Administrador";
                                    
                                frmMesas formMesas = new frmMesas(new Ventas(),turno,Venta.getUsuarios(),cadena); 
                                 formMesas.setVisible(true);
                    }
                    
                    
        }
        //else{
         //System.out.println("No selecciona una opción afirmativa");
        //}    
        
        
                           /**/
        
                // TODO add your handling code here:
    }//GEN-LAST:event_jBClearOrderActionPerformed

    private void lblTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTitleMouseClicked

        
        if(lblTitle.getText().equalsIgnoreCase("CATEGORIAS")){
        String cadena = "mesero";
            if(Venta.getUsuarios().getPerfil().equalsIgnoreCase("administrador"))
              cadena = "Administrador";
            
            
            this.dispose();
            frmMesas formMesas = new frmMesas(new Ventas(),turno,Venta.getUsuarios(),cadena); 
            formMesas.setVisible(true);
            
            
        }else{
        
        lblTitle.setText("CATEGORIAS");

        jPCategories.removeAll();
        mtdCat();
        jPCategories.setVisible(true);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_lblTitleMouseClicked

    /**
     * @param args the command line arguments
     */
   
    
    public void mtdCat(){
        
        mainMesero  p = this;
        
        lblTitle.setText("CATEGORIAS");
       
        ListadoCategorias = new ArrayList<>();
        ListadoCategorias = objCategoria.listarCategorias();
       
       
        for (Categorias dataCategoria: ListadoCategorias) {
          
            
            // Concatenamos las etiquetas HTML con el nombre dinámico del producto
            JButton btnCat = new JButton("<html><body style='text-align: center;'><b>" + dataCategoria.getNombre() + "</b></body></html>");

            // Tu línea de la fuente se mantiene impecable
            btnCat.setFont(new java.awt.Font("Arial", 0, 20)); 

            // 💡 TIP EXTRA: Asegúrate de que el texto se mantenga centrado en el botón
            btnCat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            
            
            
            
            btnCat.addActionListener(new ActionListener() { 
                public void actionPerformed(ActionEvent e) {
                    
                   // ListadoProductos =  dataCategoria.getProductoses();
                        lblTitle.setText("PRODUCTOS");
                        jPCategories.removeAll();
                        
                    for (Object obj : dataCategoria.getProductoses()) {
                        
                        Productos dataProducto = (Productos) obj;
                    
                            // Concatenamos las etiquetas HTML con el nombre dinámico del producto
                            JButton btnPro = new JButton("<html><body style='text-align: center;'><b>" + dataProducto.getNombre() + "</b></body></html>");

                            // Tu línea de la fuente se mantiene impecable
                            btnPro.setFont(new java.awt.Font("Arial", 0, 18)); 
                            btnPro.setFocusPainted(false);

                            // 💡 TIP EXTRA: Asegúrate de que el texto se mantenga centrado en el botón
                            btnPro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                         
                             btnPro.addActionListener(new ActionListener() { 
                                public void actionPerformed(ActionEvent e) {
                                    
                                    
                                  p.setEnabled(false);  
                                    
                                  frmCantidad formCantidad = new frmCantidad(p,Venta);
                                  
                                    formCantidad.setVisible(true);
                                    formCantidad.setResizable(false);
                                    formCantidad.setProducto(dataProducto);
                                    formCantidad.setTotalVenta(getTotalVenta());
                                    
                                    frmCantidad.modo_acceso = "create";
                                    frmCantidad.objUpdate = null;
                                    
                                    mainMesero.pedido = new Pedidos();
                                    
                                    formCantidad.addWindowListener(new java.awt.event.WindowAdapter() {
                                    @Override
                                    public void windowClosed(java.awt.event.WindowEvent e) {
                                    // Cuando frmCantidad se destruya o se cierre, mainMesero vuelve a la vida
                                    mainMesero.this.setEnabled(true); 
                                    mainMesero.this.toFront(); // La trae al frente automáticamente
                                    }});
                                    
                                   
                                }
                             });
                            
                            
                            jPCategories.add(btnPro);
                        }
                    
                    jPCategories.revalidate();
                    jPCategories.repaint();
                        
                        
                } 
            } );
            
            jPCategories.add(btnCat);
            jPCategories.revalidate();
            jPCategories.repaint();
        }
    }
    
    
    public void mtdGuardarPedido(Pedidos pedido,Productos productoServicio,String TipoRegistro){
            
      
        Transaction trns = null;
        Session session = HibernateUtil.getSessionFactory().openSession();

            try {
                
                trns = session.beginTransaction();
                session.save(pedido);
                trns.commit();
                    
                    itemOrder io = new itemOrder(this);


                    itemOrder.producto = pedido.getProducto();
                    itemOrder.totalVenta = getTotalVenta();

                    if(totalVenta == 0){
                    setTotalVenta(pedido.getValor());
                    }else{
                    setTotalVenta(pedido.getValor() + getTotalVenta());
                    }
                    
                    io.mtdUbicarInformacion(pedido);
                    io.objetoPedido = pedido;
                    
                    PanelListadoPedidos.add(io);
                    PanelListadoPedidos.revalidate();
                    PanelListadoPedidos.repaint();
                    
                    getVenta().addPedido(pedido);
                    
                    if(TipoRegistro.equalsIgnoreCase("Con Servicio")){
                        
                        servicio = new Servicios(pedido, productoServicio, pedido.getCantidad());
                         
                        trns = session.beginTransaction();
                        session.save(servicio);
                        trns.commit();
                        
                        
                        BigDecimal stockServicio = servicio.getProducto().getStock();
                       int stoServicio = stockServicio.setScale(0, RoundingMode.DOWN).intValueExact();
                       
                       servicio.getProducto().setStock(BigDecimal.valueOf(stoServicio - servicio.getCantidad()));
                       
                        trns = session.beginTransaction();
                        session.update(servicio.getProducto());
                        trns.commit();
                       
                    }
                    
                    
                    
                    if(pedido.getProducto().getSubproductosesForProducto().size() > 0){
                        trns = session.beginTransaction();
                        for (Object objSubProducto : pedido.getProducto().getSubproductosesForProducto() ) {
                            
                            models.Subproductos dataSubProducto = (models.Subproductos) objSubProducto;
                            
                                BigDecimal stockSub = dataSubProducto.getProductosBySubproducto().getStock();
                                int stoSub = stockSub.setScale(0, RoundingMode.DOWN).intValueExact();

                                BigDecimal cantADescontar = dataSubProducto.getCantidad();
                                int cntDes = cantADescontar.setScale(0, RoundingMode.DOWN).intValueExact();
                                
                                int cantidadTotalDescuento = cntDes * pedido.getCantidad();
                                
                                dataSubProducto.getProductosBySubproducto().setStock(BigDecimal.valueOf(stoSub - cantidadTotalDescuento));
                                
                                
                                session.update(dataSubProducto.getProductosBySubproducto());
                                
                        }
                        trns.commit();
                        
                        //SUMAR LAS UNIDADES SOLICITADAS AL STOCK DEL PRODUCTO EN PROMOCIÓN
                        
                        BigDecimal stockPromo = pedido.getProducto().getStock();
                        int stoPromo = stockPromo.setScale(0, RoundingMode.DOWN).intValueExact();

                        pedido.getProducto().setStock(BigDecimal.valueOf(stoPromo + pedido.getCantidad()));
                        
                        session.beginTransaction();
                        session.update(pedido.getProducto());
                        session.getTransaction().commit();
                        
                        
                    }else{
                    
                           
                        BigDecimal stock = pedido.getProducto().getStock();
                        int sto = stock.setScale(0, RoundingMode.DOWN).intValueExact();

                        pedido.getProducto().setStock(BigDecimal.valueOf(sto - pedido.getCantidad()));

                        trns = session.beginTransaction();
                        session.update(pedido.getProducto());
                        trns.commit(); 
                    }
                    
                
              

            }catch (RuntimeException ex) {
                System.out.println(ex.getMessage());
            }finally {
                session.evict(pedido); 
                session.flush();
                session.close();
            }
            
        //lblTotal.setText(String.valueOf(NumberFormat.getCurrencyInstance(new Locale("es", "CO")).format(totalVenta))); 
    }
    
    public void mtdEditarPedido(Pedidos pedido,itemOrder objForm,int CantidadAnterior){
        
        Transaction trns = null;
        Session session = HibernateUtil.getSessionFactory().openSession();
            
            if(pedido.getCantidad() == 0){
                
                try {
                
                    
                        if(pedido.getProducto().getSubproductosesForProducto().size() > 0){
                            
                            
                            
                                trns = session.beginTransaction();
                                for (Object objSubProducto : pedido.getProducto().getSubproductosesForProducto() ) {

                                        models.Subproductos dataSubProducto = (models.Subproductos) objSubProducto;
                                        
                                        
                                        
                                        BigDecimal stockSub = dataSubProducto.getProductosBySubproducto().getStock();
                                        int stoSub = stockSub.setScale(0, RoundingMode.DOWN).intValueExact();

                                        BigDecimal cantADescontar = dataSubProducto.getCantidad();
                                        int cntDes = cantADescontar.setScale(0, RoundingMode.DOWN).intValueExact();

                                        int cantidadTotalDescuento = cntDes * CantidadAnterior;

                                        dataSubProducto.getProductosBySubproducto().setStock(BigDecimal.valueOf(stoSub + cantidadTotalDescuento));


                                        session.update(dataSubProducto.getProductosBySubproducto());

                                }
                                trns.commit();
                        
                                //SUMAR LAS UNIDADES SOLICITADAS AL STOCK DEL PRODUCTO EN PROMOCIÓN

                                BigDecimal stockPromo = pedido.getProducto().getStock();
                                int stoPromo = stockPromo.setScale(0, RoundingMode.DOWN).intValueExact();

                                pedido.getProducto().setStock(BigDecimal.valueOf(stoPromo - CantidadAnterior));

                               
                        

                        }else{    

                                BigDecimal stock = pedido.getProducto().getStock();
                                int sto = stock.setScale(0, RoundingMode.DOWN).intValueExact();

                                pedido.getProducto().setStock(BigDecimal.valueOf(sto + CantidadAnterior));
                        }
                        
                        
                        Set pedidos = getVenta().getPedidoses();

                        for (Iterator<Pedidos> iterator = pedidos.iterator(); iterator.hasNext();) {
                        Pedidos p =  iterator.next();
                        if (p.getIdPedido()== pedido.getIdPedido()) {
                            iterator.remove();
                        }       
                        }

                        getVenta().setPedidoses(pedidos);


                        trns = session.beginTransaction();
                        session.update(pedido.getProducto());
                        session.delete(pedido);
                        trns.commit();

                } catch (RuntimeException e) {
                e.printStackTrace();
                }
                    
                
                PanelListadoPedidos.remove(objForm);
                PanelListadoPedidos.revalidate();
                PanelListadoPedidos.repaint();
                
            }else{
                
                    try {
                        pedido.setImpreso(false);
                        trns = session.beginTransaction();
                        session.update(pedido);
                        trns.commit();

                         PanelListadoPedidos.remove(objForm);

                          itemOrder io = new itemOrder(this);

                            itemOrder.producto = pedido.getProducto();
                            itemOrder.totalVenta = getTotalVenta();
                            io.mtdUbicarInformacion(pedido);
                            io.objetoPedido = pedido;

                         PanelListadoPedidos.add(io);
                         PanelListadoPedidos.revalidate();
                         PanelListadoPedidos.repaint();

                        

                    }catch (RuntimeException ex) {
                        ex.printStackTrace();
                    }
                
                if(CantidadAnterior > pedido.getCantidad()){
                   
                    int diff = CantidadAnterior - pedido.getCantidad();
                    
                    try {
                        
                        if(pedido.getProducto().getSubproductosesForProducto().size() > 0){
                            
                                 trns = session.beginTransaction();
                                for (Object objSubProducto : pedido.getProducto().getSubproductosesForProducto() ) {

                                        models.Subproductos dataSubProducto = (models.Subproductos) objSubProducto;
                                        
                                        
                                        
                                        BigDecimal stockSub = dataSubProducto.getProductosBySubproducto().getStock();
                                        int stoSub = stockSub.setScale(0, RoundingMode.DOWN).intValueExact();

                                        BigDecimal cantADescontar = dataSubProducto.getCantidad();
                                        int cntDes = cantADescontar.setScale(0, RoundingMode.DOWN).intValueExact();

                                        int cantidadTotalDescuento = cntDes * diff;

                                        dataSubProducto.getProductosBySubproducto().setStock(BigDecimal.valueOf(stoSub + cantidadTotalDescuento));


                                        session.update(dataSubProducto.getProductosBySubproducto());

                                }
                                trns.commit();
                        
                                //SUMAR LAS UNIDADES SOLICITADAS AL STOCK DEL PRODUCTO EN PROMOCIÓN

                                BigDecimal stockPromo = pedido.getProducto().getStock();
                                int stoPromo = stockPromo.setScale(0, RoundingMode.DOWN).intValueExact();

                                pedido.getProducto().setStock(BigDecimal.valueOf(stoPromo - pedido.getCantidad()));

                               
                        

                        }else{
                    
                            BigDecimal stock = pedido.getProducto().getStock();
                            int sto = stock.setScale(0, RoundingMode.DOWN).intValueExact();

                            pedido.getProducto().setStock(BigDecimal.valueOf(sto + diff));

                            
                        }
                        
                            trns = session.beginTransaction();
                            session.update(pedido.getProducto());
                            trns.commit();
                    } catch (RuntimeException e) {
                    e.printStackTrace();
                    } 
                   
                   
                }else{
                   int diff = pedido.getCantidad() - CantidadAnterior;
                    
                    try {
                        
                        if(pedido.getProducto().getSubproductosesForProducto().size() > 0){
                            
                                 trns = session.beginTransaction();
                                for (Object objSubProducto : pedido.getProducto().getSubproductosesForProducto() ) {

                                        models.Subproductos dataSubProducto = (models.Subproductos) objSubProducto;
                                        
                                        
                                        
                                        BigDecimal stockSub = dataSubProducto.getProductosBySubproducto().getStock();
                                        int stoSub = stockSub.setScale(0, RoundingMode.DOWN).intValueExact();

                                        BigDecimal cantADescontar = dataSubProducto.getCantidad();
                                        int cntDes = cantADescontar.setScale(0, RoundingMode.DOWN).intValueExact();

                                        int cantidadTotalDescuento = cntDes * diff;

                                        dataSubProducto.getProductosBySubproducto().setStock(BigDecimal.valueOf(stoSub - cantidadTotalDescuento));


                                        session.update(dataSubProducto.getProductosBySubproducto());

                                }
                                trns.commit();
                        
                                //SUMAR LAS UNIDADES SOLICITADAS AL STOCK DEL PRODUCTO EN PROMOCIÓN

                                BigDecimal stockPromo = pedido.getProducto().getStock();
                                int stoPromo = stockPromo.setScale(0, RoundingMode.DOWN).intValueExact();

                                pedido.getProducto().setStock(BigDecimal.valueOf(stoPromo + diff));

                               
                        

                        }else{
                            BigDecimal stock = pedido.getProducto().getStock();
                            int sto = stock.setScale(0, RoundingMode.DOWN).intValueExact();

                            pedido.getProducto().setStock(BigDecimal.valueOf(sto - diff));
                        }
                    trns = session.beginTransaction();
                    session.update(pedido.getProducto());
                    trns.commit();

                    } catch (RuntimeException e) {
                    e.printStackTrace();
                    } 
                }
       
                    
           }
        session.evict(pedido);                
        session.flush();
        session.close();
    }
    
    public void mtdAplicarDescuento(Pedidos pedido,itemOrder objForm,int NuevoValor){
        
        /*pedido.setValor(NuevoValor * pedido.getCantidad());
        
        
        Transaction trns = null;
        Session session = HibernateUtil.getSessionFactory().openSession();
        
        try {
            pedido.setImpreso(false);
            trns = session.beginTransaction();
            session.update(pedido);
            trns.commit();
            
            PanelListadoPedidos.remove(objForm);

            itemOrder io = new itemOrder(this);

              itemOrder.producto = pedido.getProducto();
              itemOrder.totalVenta = getTotalVenta();
              io.mtdUbicarInformacion(pedido);
              io.objetoPedido = pedido;

            PanelListadoPedidos.add(io);
            PanelListadoPedidos.revalidate();
            PanelListadoPedidos.repaint();

            JOptionPane.showMessageDialog(null, "Descuento Aplicado");

        } catch (RuntimeException e) {
            e.printStackTrace();
        }finally{
        session.flush();
        session.close();
        }*/
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelListadoPedidos;
    private javax.swing.JScrollPane ScrollCategorias;
    private javax.swing.JScrollPane ScrollPedidos;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton jBClearOrder;
    private javax.swing.JPanel jPCategories;
    private javax.swing.JPanel jPOrder;
    private javax.swing.JPanel jpnMain;
    private javax.swing.JPanel jpnSuperior;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMesa;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalVenta;
    private javax.swing.JLabel txtPedidos;
    // End of variables declaration//GEN-END:variables
}
